planetarium/NineChronicles.Headless

NineChronicles.Standalone.Tests/GraphTypes/GraphQLTestBase.cs
NineChronicles.Standalone.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Standalone.Tests/GraphTypes/StandaloneSubscriptionTest.cs

This PR removes warnings related to async feature in the test project. it also synchronizes Lib9c to the latest.

Cleaning the test project and sync lib9c

---

NineChronicles.Standalone.Executable/Program.cs

Process should be killed when node services were failed to execute.

Exit program when catches error

---

Libplanet.Standalone/Hosting/LibplanetNodeService.cs
Libplanet.Standalone/Hosting/LibplanetNodeServiceProperties.cs
Libplanet.Standalone/Libplanet.Standalone.csproj
NineChronicles.Standalone.Executable/Program.cs
NineChronicles.Standalone/Properties/NineChroniclesNodeServiceProperties.cs

Prerequisites: <https://github.com/planetarium/lib9c/pull/45>.
To use Libplanet's [delayed renderers][1], upgrades it to 0.10.0-dev.20200904141108.  Also added the `Confirmations` configuration.
[1]: https://github.com/planetarium/libplanet/pull/980

Upgrade Libplanet to 0.10.0-dev.20200904141108

---

Libplanet.Standalone/Hosting/LibplanetNodeService.cs
NineChronicles.Standalone/Controllers/GraphQLController.cs
NineChronicles.Standalone/NineChroniclesNodeService.cs
NineChronicles.Standalone/Requests/CheckPeerRequest.cs

Added new HttpRequest `/check-peer` that returns 200 if the target peer exists, otherwise 400.

Add HttpRequest to find specific peer on network

---

NineChronicles.Standalone/ActionEvaluationHub.cs
NineChronicles.Standalone/ActionEvaluationPublisher.cs

To match IRenderer interface, some changes are made to broadcasting methods.
Please see also: https://github.com/planetarium/NineChronicles.RPC.Shared/pull/3

Refactor RPC interfaces

---

.editorconfig
Libplanet.Standalone/Libplanet.Standalone.csproj
NineChronicles.Standalone.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Standalone.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Standalone/NineChroniclesNodeService.cs

This PR adds configuration for `AuthorizedMinersState` introduced by https://github.com/planetarium/lib9c/pull/60

Configuration BlockPolicySource for AuthorizedMinersState

---

Libplanet.Standalone.Tests/Hosting/LibplanetNodeServiceTest.cs
Libplanet.Standalone/Hosting/LibplanetNodeService.cs
Libplanet.Standalone/Libplanet.Standalone.csproj
NineChronicles.Standalone.Tests/GraphTypes/GraphQLTestBase.cs
NineChronicles.Standalone/ActionEvaluationHub.cs
NineChronicles.Standalone/ActionEvaluationPublisher.cs
NineChronicles.Standalone/ExceptionRenderer.cs
NineChronicles.Standalone/NineChroniclesNodeService.cs

This patch implement interface for reporting errors via RPC, and send `NetworkException` when no any peers in node's routing table even the seed peers were given.
Please see also https://github.com/planetarium/NineChronicles.RPC.Shared/pull/5 and https://github.com/planetarium/NineChronicles.RPC.Shared/pull/6.

Report error via RPC when no any peers in routing table with seed peers given

---

Libplanet.Standalone/Hosting/LibplanetNodeService.cs
Libplanet.Standalone/Hosting/LibplanetNodeServiceProperties.cs
NineChronicles.Standalone.Tests/GraphTypes/StandaloneSubscriptionTest.cs
NineChronicles.Standalone/GraphTypes/NodeExceptionType.cs
NineChronicles.Standalone/GraphTypes/StandaloneSubscription.cs
NineChronicles.Standalone/NodeException.cs
NineChronicles.Standalone/StandaloneContext.cs
NineChronicles.Standalone/StandaloneServices.cs

This patch implement interface for reporting errors via GraphQL, and send NodeException subscription when no any peers in node's routing table even the seed peers were given.

Report error via GraphQL when no any peers in routing table with seed peers given 

---

NineChronicles.Standalone.Executable/Program.cs
NineChronicles.Standalone/Properties/NineChroniclesNodeServiceProperties.cs
README.md

This PR changes `--mpt` options to `--no-mpt` and makes MPT the default implementation to use in the state store.

Flip switch for MPT

---

.github/workflows/pull_request.yml
.github/workflows/push.yml
Libplanet.Standalone.Tests/Libplanet.Standalone.Tests.csproj
Libplanet.Standalone/Libplanet.Standalone.csproj
NineChronicles.Standalone.Tests/NineChronicles.Standalone.Tests.csproj

As I closed the PR #87 by mistake, I open a new PR again.
See also:
- planetarium/lib9c#110
- PR planetarium/lib9c#126
- PR https://github.com/planetarium/nekoyume-unity/pull/2876

Reference Libplanet inside Lib9c instead of NuGet (retake)

---

NineChronicles.Standalone/GraphTypes/ValidationQuery.cs

Sleep 3 seconds when receiving validation snapshot metadata query.
Note: This PR is temporary workaround, should be replaced with retry logic.

temp) validation sleep

---

Libplanet.Standalone/Hosting/LibplanetNodeService.cs

Continued from #141.  As NineChronicles.Executable only prints logs equal to or higher than debug-level, I changed the log level of raw render events to debug (from verbose).

As verbose-level logs are ignored, log raw render events in debug-level

---

NineChronicles.Standalone.Tests/Common/ServiceBuilder.cs
NineChronicles.Standalone.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Standalone.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Standalone/GraphTypes/NodeStatus.cs
NineChronicles.Standalone/GraphTypes/StandaloneMutation.cs
NineChronicles.Standalone/GraphTypes/StandaloneQuery.cs
NineChronicles.Standalone/GraphTypes/TxIdType.cs
NineChronicles.Standalone/NineChroniclesNodeService.cs
NineChronicles.Standalone/StandaloneContext.cs
NineChronicles.Standalone/StandaloneServices.cs

This PR adds TxId of created tx for `transferAsset()` mutation.
and, it also adds `stagedTxIds ` field to `nodeStatus` to query current staged transactions. (it can be useful when checking tx is applied).

Add txId for transferAsset()

---

Libplanet.Standalone/Hosting/DevLibplanetNodeService.cs
Libplanet.Standalone/Hosting/LibplanetNodeService.cs
Libplanet.Standalone/Hosting/LibplanetNodeServiceProperties.cs
Libplanet.Standalone/NodeException.cs
NineChronicles.Standalone.Tests/GraphTypes/StandaloneSubscriptionTest.cs
NineChronicles.Standalone/GraphTypes/NodeExceptionType.cs
NineChronicles.Standalone/GraphTypes/StandaloneSubscription.cs
NineChronicles.Standalone/StandaloneContext.cs
NineChronicles.Standalone/StandaloneServices.cs

Additionally, it became not to use `RPCException` in graphql. Now uses `NodeExceptionType` instead.

Throw error via graphql when tip is stale

---

Libplanet.Standalone/Hosting/LibplanetNodeService.cs

This PR loosen internal checks in `LibplanetNodeSerivce` and makes them wait until `.Swarm` is ready.

Loosen checks in LibplanetNodeService

---

NineChronicles.Standalone.Executable/LoggerConfigurationExtensions.cs
NineChronicles.Standalone.Executable/Program.cs
README.md

It provides a new option to configure `LoggerConfiguration.MinimumLevel`, `--log-minimum-level`.

feat(cli): add --log-minimum-level option to configure

---

.github/workflows/pull_request.yml
.github/workflows/push.yml

We can remove the build step because the build is done in the test step.

Remove build step from Actions

---

Libplanet.Standalone/Hosting/LibplanetNodeService.cs

fix: call _preloadStatusHandlerAction when peer is none

---

Libplanet.Standalone.Tests/Hosting/LibplanetNodeServiceTest.cs
NineChronicles.Standalone/ReorgPolicy.cs

This should be merged *after* <https://github.com/planetarium/lib9c/pull/220> & <https://github.com/planetarium/libplanet/pull/1102> are merged.

Catch up Libplanet's upstream & limit block size

---

Libplanet.Standalone.Tests/Hosting/LibplanetNodeServiceTest.cs
Libplanet.Standalone/Hosting/DevLibplanetNodeService.cs
Libplanet.Standalone/Hosting/LibplanetNodeService.cs
Libplanet.Standalone/Hosting/LibplanetNodeServiceProperties.cs
NineChronicles.Standalone.Executable/Program.cs
NineChronicles.Standalone.Tests/Common/ServiceBuilder.cs
NineChronicles.Standalone.Tests/GraphTypes/GraphQLTestBase.cs
NineChronicles.Standalone.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Standalone.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Standalone/NineChroniclesNodeService.cs
NineChronicles.Standalone/Properties/NineChroniclesNodeServiceProperties.cs
README.md

It deprecates the option of whether to use the MPT state store or not.

feat(mpt): treat only MPT state store

---

NineChronicles.Standalone.Executable/NineChronicles.Standalone.Executable.csproj
NineChronicles.Standalone.Executable/Program.cs
README.md

It supports [AWS Cognito credentials](https://aws.amazon.com/ko/cognito/).
To use this feature, you *MUST* use only one crendtial method between basic credential (i.e., access key & secret key) and Cognito credential (i.e., Cognito identity).

feat(logging): support Cognito identity credential

---

Dockerfile

This PR removes unnecessary parameters when building the 9c-headless image and enables the Docker container to run on EC2 without an elastic IP and use the TURN server.

remove host and port

---

NineChronicles.Headless/Controllers/GraphQLController.cs

It used to throw `NullReferenceException` when `NineChroniclesNodeService` instance is null. Now returns 409 instead so sender can handle.

Check NineChroniclesNodeService for HttpRequests

---

.github/workflows/deploy_ghpackages_docker.yml

This PR updates the repository name in github packages workflow from "standalone" to "headless"

update ghpackages repo name

---

NineChronicles.Headless.Tests/GraphQLTestUtils.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/CollectionMapTypeTest.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
NineChronicles.Headless/GraphTypes/StateQuery.cs
NineChronicles.Headless/GraphTypes/States/AvatarStateType.cs
NineChronicles.Headless/GraphTypes/States/Models/CollectionMapType.cs
NineChronicles.Headless/GraphTypes/States/Models/Item/ConsumableType.cs
NineChronicles.Headless/GraphTypes/States/Models/Item/CostumeType.cs
NineChronicles.Headless/GraphTypes/States/Models/Item/DecimalStatType.cs
NineChronicles.Headless/GraphTypes/States/Models/Item/Enum/ElementalTypeEnumType.cs
NineChronicles.Headless/GraphTypes/States/Models/Item/Enum/ItemSubTypeEnumType.cs
NineChronicles.Headless/GraphTypes/States/Models/Item/Enum/ItemTypeEnumType.cs
NineChronicles.Headless/GraphTypes/States/Models/Item/Enum/StatTypeEnumType.cs
NineChronicles.Headless/GraphTypes/States/Models/Item/EquipmentType.cs
NineChronicles.Headless/GraphTypes/States/Models/Item/InventoryType.cs
NineChronicles.Headless/GraphTypes/States/Models/Item/ItemBaseType.cs
NineChronicles.Headless/GraphTypes/States/Models/Item/MaterialType.cs
NineChronicles.Headless/GraphTypes/States/Models/Mail/MailBoxType.cs
NineChronicles.Headless/GraphTypes/States/Models/Mail/MailType.cs
NineChronicles.Headless/GraphTypes/States/Models/Quest/QuestListType.cs
NineChronicles.Headless/GraphTypes/States/Models/Quest/QuestRewardType.cs
NineChronicles.Headless/GraphTypes/States/Models/Quest/QuestType.cs
NineChronicles.Headless/GraphTypes/States/Models/World/WorldInformationType.cs
NineChronicles.Headless/GraphTypes/States/Models/World/WorldType.cs

It provides [`Lib9c.Model.State.AvatarState`][lib9c-avatar-state] as GraphQL API.
I added a test for only `CollectionMapType` because I thought other types are covered from tests of graphql-dotnet/graphql-dotnet. For instance, `StatTypeEnumType` is actually the alias of `EnumerationGraphType<StatType>` and if I wrote its test code, it will just check that `new StatTypeEnumType().Serialize(StatType.*)` evaluate as the capital of the enum. I thought there is no duty to test them because they should be tested in `GraphQL.Tests` and guaranteed. If it seems that I am thinking in an incorrect way or you feel like to want discussion for this, please leave a comment.
[lib9c-avatar-state]: https://github.com/planetarium/lib9c/blob/main/Lib9c/Model/State/AvatarState.cs

feat(gql): add avatar state query

---

NineChronicles.Headless/GraphTypes/StateQuery.cs
NineChronicles.Headless/GraphTypes/States/RankingInfoType.cs
NineChronicles.Headless/GraphTypes/States/RankingMapStateType.cs

It should be mereed after #216 merged.
It provides GraphQL API for `RankingState`, `RankingMapState`.

feat(gql): add ranking state query

---

NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless/NineChroniclesNodeService.cs
NineChronicles.Headless/StandaloneServices.cs
README.md

It provides `--is-authorized-miner` flag for *authorized miner* mode. The mode makes miner mine only blocks that authorized miner should mine.

feat: provide authorized miner mode

---

NineChronicles.Headless.Tests/GraphTypes/GraphQLTestBase.cs
NineChronicles.Headless/GraphTypes/GraphTypeAuthorizationExtensions.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs

It fixes a bug where some fields of `StandaloneQuery` doesn't work conditionally.

fix(graphql): correct query authorization conditionally

---

NineChronicles.Headless/NineChroniclesNodeService.cs

It fixes a bug that it didn't detect the index of the block to mine correctly. It was appeared since #234.

fix: correct index to mine by authorized miner

---

NineChronicles.Headless.Executable/Program.cs

Currently, it loads the `Guid` used in `AWSSink` and store it every run. Maybe it may make the `Guid` if `NineChronicles.Headless` killed after short time. Also it hasn't covered the situtation. I believe This pull request resolves them.

fix(logging): cover situation that guid is broken

---

.github/workflows/deploy_ghpackages_docker.yml
.github/workflows/push_docker_image.yml

This PR removes automated push to `planetariumhq/ninechronicles-headless:latest` to hide pre-release versions.

Hide development versions

---

Libplanet.Headless/Hosting/LibplanetNodeServiceProperties.cs
NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless.Tests/Common/ServiceBuilder.cs
NineChronicles.Headless/NineChroniclesNodeService.cs
README.md

The introduced `--log-action-renders` option enforces action renderings to be logged whether `--rpc-server` is turned on or off.  However, this can cause the significant performance impact (see also: <https://github.com/planetarium/libplanet/pull/970> & <https://github.com/planetarium/libplanet/pull/883>), so this is turned off by default.

Introduce --log-action-renders option

---

Docs/SECURE_MODE.md

It resolves #253. It adds `Docs/SECURE_MODE.md` document which describes about `--graphql-secret-token-path` introduced at #230.

docs: add secure mode document

---

NineChronicles.Headless.Executable/AWSSink.cs
NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj
NineChronicles.Headless.Executable/Program.cs

Currently, there is a problem with memory leaks because of `AWSSink._queue`. There was a time which couldn't handle `LogEvent`s well so the capacity of the `Queue<T>` used by _queue, became more and more, up to 4GB in my case.
This pull request tries to resolve the problem by handling the events at the correct time well with `PeriodicBatchSink`. You can see the sink's more information in [serilog/serilog-sinks-periodicbatching](https://github.com/serilog/serilog-sinks-periodicbatching). I opened this because the test in local was better than now when monitoring with memory profiler. I believe it will make the memory leak problem better but I'm not sure that it can fix all memory leaks well 🤔 .
If you want to test this in your local, make sure you must run with `--aws-*` options.

feat: send cloudwatch logs periodically

---

NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless.Tests/GraphQLStartupTest.cs
NineChronicles.Headless/GraphQLService.cs
NineChronicles.Headless/Properties/GraphQLNodeServiceProperties.cs
README.md

It introduces `--no-cors` option for users to want to run with *Access-Control-Allow-Origin* header (i.e., without being restricted with CORS policy).

feat: introduce `--no-cors` option

---

NineChronicles.Headless/NineChroniclesNodeService.cs

Prevent `NullReferenceException` with empty authorized miner state in block policy.

Fix NullReferenceException with empty authorized miner state

---

Libplanet.Headless.Tests/Libplanet.Headless.Tests.csproj
Libplanet.Headless/Libplanet.Headless.csproj
NineChronicles.Headless.Common.ruleset
NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj
NineChronicles.Headless.Tests/NineChronicles.Headless.Tests.csproj
NineChronicles.Headless/NineChronicles.Headless.csproj

This pull request makes the below projects to use static code analysis to achieve #302.
- `Libplanet.Headless`
- `Libplanet.Headless.Tests`
- `NIneChronicles.Headless`
- `NIneChronicles.Headless.Tests`
- `NIneChronicles.Headless.Executable`
But this pull request doesn't update codes by the all rules and they have been ignored. It expects they should be removed from `NineChronicles.Headless.Common.ruleset` and resolved step by step.

build: use static code analysis tool

---

Libplanet.Headless/Libplanet.Headless.csproj
NineChronicles.Headless/NineChronicles.Headless.csproj

This pull request bumps their target framework into `netcoreapp3.1` because [`netcoreapp3.0` was dead](https://devblogs.microsoft.com/dotnet/net-core-3-0-end-of-life/).

build: bump target framework to `netcoreapp3.1'

---

NineChronicles.Headless.Executable.Tests/Commands/ValidationCommandTest.cs
NineChronicles.Headless.Executable.Tests/IO/StringIOConsole.cs
NineChronicles.Headless.Executable.Tests/NineChronicles.Headless.Executable.Tests.csproj
NineChronicles.Headless.Executable.sln
NineChronicles.Headless.Executable/Commands/ValidationCommand.cs
NineChronicles.Headless.Executable/IO/IConsole.cs
NineChronicles.Headless.Executable/IO/StandardConsole.cs
NineChronicles.Headless.Executable/Program.cs

This pull request introduces new sub-command, `validation`, a command group of commands to validate _Libplanet_'s types (e.g. `PrivateKey`, `PublicKey`).
New commands:
- `NineChronicles.Headless.Executable validation private-key <PRIVATE-KEY>`
- `NineChronicles.Headless.Executable validation public-key <PUBLIC-KEY>`
These commands are introduced to replace GraphQL API `validationQuery`.

feat(cli): implement `validation'  subcommand

---

README.md

This PR adds the [GraphQL documentation link](https://planetarium.github.io/NineChronicles.Headless/) for NineChronicles Headless.
I've also added a `Table of Contents` for better navigation.

add graphql documentation link

---

NineChronicles.Headless/Controllers/GraphQLController.cs

This PR disables notifications due to spamming on reorg. we should add filters for reorg before uncomment them.

Disable action notifications to avoid spamming on reorg

---

Libplanet.Headless/Hosting/LibplanetNodeService.cs

This PR takes `monorocksdb` as an option for `--store-type`.
After this PR, `monorocksdb` will take the [original rocksdb(MonoRocksDBStore)](https://github.com/planetarium/libplanet/blob/main/Libplanet.RocksDBStore/MonoRocksDBStore.cs) and `rocksdb` will take the [new rocksdb](https://github.com/planetarium/libplanet/blob/main/Libplanet.RocksDBStore/RocksDBStore.cs).

support-monorocksdb

---

NineChronicles.Headless.Executable/Commands/KeyCommands.cs
NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless.Executable/Utils/ConsolePasswordReader.cs
NineChronicles.Headless.Executable/Utils/Utils.cs
README.md

This pull request introduces `key` subcommand to handle `IKeyStore` in command line. This uses the copy of `Libplanet.Tools`' `key` subcommand. They should be replaced if https://github.com/planetarium/libplanet/pull/1210 accepted.

feat(cli): introduce `key` subcommand

---

NineChronicles.Headless/GraphTypes/States/Models/Item/DecimalStatType.cs

It fixes #358 by resolving `DecimalStat.Type` manually because `DecimalStat.Type` is field, not property.

fix(graphql): resolve manually for field

---

NineChronicles.Headless.Executable.Tests/Commands/KeyCommandTest.cs
NineChronicles.Headless.Executable.Tests/KeyStore/InMemoryKeyStore.cs
NineChronicles.Headless.Executable/Commands/KeyCommands.cs
NineChronicles.Headless.Executable/Program.cs

It introduces a new option `--no-passphrase` to remove key without passphrase. I also suggested to https://github.com/planetarium/libplanet/issues/1213.

feat(cli): add `--no-passphrase` option into `key` command

---

Libplanet.Headless/Hosting/LibplanetNodeService.cs

In some situation swarm is started repeatedly where it is already running. This patch prevents it by removing loop in `Service.StartAsync()`.

Prevent swarm restarting

---

NineChronicles.Headless.Executable.Tests/Commands/ChainCommandTest.cs
NineChronicles.Headless.Executable.Tests/Store/IStoreExtensionsTest.cs
NineChronicles.Headless.Executable.Tests/Store/StoreTypeExtensionsTest.cs
NineChronicles.Headless.Executable/Store/StoreType.cs
NineChronicles.Headless.Executable/Store/StoreTypeExtensions.cs

#354 introduced `monorocksdb` but `chain tip` subcommand didn't apply it. It resolves the issue.

fix: support monorocksdb also in `chain tip` command

---

.github/workflows/deploy_gh_pages.yml

The workflow `deploy_gh_pages` was introduced in https://github.com/planetarium/NineChronicles.Headless/pull/331. Since https://github.com/planetarium/NineChronicles.Headless/pull/331, the `actions/checkout` action hasn't had `submodules` input and `actions/setup-node` action has had incorrect input. This pull request fixes it.

ci(gh-actions): fix invalid action input

---

NineChronicles.Headless.Executable.Tests/Commands/ValidationCommandTest.cs
NineChronicles.Headless.Executable.Tests/IO/StringIOConsole.cs
NineChronicles.Headless.Tests/Controllers/GraphQLControllerTest.cs
NineChronicles.Headless.Tests/GraphQLTestUtils.cs
NineChronicles.Headless.Tests/GraphTypes/AuthenticationMutationTest.cs
NineChronicles.Headless.Tests/GraphTypes/GraphQLTestBase.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Headless.Tests/ISessionExtensionsTest.cs
NineChronicles.Headless.Tests/InMemorySession.cs
NineChronicles.Headless.Tests/InMemorySessionTest.cs
NineChronicles.Headless.Tests/Middleware/AuthenticationValidationMiddlewareTest.cs
NineChronicles.Headless.Tests/NineChronicles.Headless.Tests.csproj
NineChronicles.Headless.Tests/SessionTest.cs
NineChronicles.Headless/Controllers/GraphQLController.cs
NineChronicles.Headless/GraphQLService.cs
NineChronicles.Headless/GraphTypes/ActionMutation.cs
NineChronicles.Headless/GraphTypes/ActivationStatusMutation.cs
NineChronicles.Headless/GraphTypes/AuthenticationMutation.cs
NineChronicles.Headless/GraphTypes/KeyStoreMutation.cs
NineChronicles.Headless/GraphTypes/Notification.cs
NineChronicles.Headless/GraphTypes/NotificationType.cs
NineChronicles.Headless/GraphTypes/StandaloneMutation.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs
NineChronicles.Headless/ISessionExtensions.cs
NineChronicles.Headless/Middleware/AuthenticationValidationMiddleware.cs
NineChronicles.Headless/UserContextBuilder.cs

It resolves #316.
This pull request makes it manage private key by session (i.e. user), with key store as account backend.
Since this pull request, it will have [Moq](https://github.com/moq/moq4) to mock services, as a dependency.

feat(graphql): use private key in session

---

.github/auto_assign.yml

Hello @planetarium/9c-backend, I suggest to use *auto-assign* bot to automate assign reviewers and assignees.

ci: add auto-assign bot

---

NineChronicles.Headless.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Headless/GraphTypes/StandaloneMutation.cs

This PR adds new field(`transfer()`) to the mutation to replacing `transferGold()` that calculated transaction nonce automatically. (it's very handy but it also easy to make mistakes.)
it closes #387

Replace transferGold() with transfer()

---

Libplanet.Headless/Hosting/LibplanetNodeService.cs
Libplanet.Headless/Hosting/LibplanetNodeServiceProperties.cs
NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless.Tests/Common/ServiceBuilder.cs
NineChronicles.Headless.Tests/GraphTypes/GraphQLTestBase.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs

This PR provides an option `--static-peer` which takes a list of peers to maintain, which will provide minimal countermeasures against eclipse attack.

Maintain given static peers

---

NineChronicles.Headless.Executable/Store/IStoreExtensions.cs
NineChronicles.Headless.Executable/Store/NoOpStateStore.cs
NineChronicles.Headless/BlockChainExtensions.cs
NineChronicles.Headless/GraphTypes/BlockHeaderType.cs
NineChronicles.Headless/GraphTypes/NodeStatus.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs

The submodule *Lib9c* should be bumped to the merge commit after <https://github.com/planetarium/lib9c/pull/328> is merged.
~The build currently fails because *Libplanet.Exploerer*, which is one of its dependencies, depends on *Libplanet* on the NuGet Gallery instead of *Lib9c/.Libplanet/Libplanet* project.  This should be rebased after <https://github.com/planetarium/libplanet/pull/1197> is merged and the version of *Libplanet.Explorer*'s dependency to *Libplanet* is upgraded.~ This was addressed by <https://github.com/planetarium/libplanet/pull/1244> & #445, and now it's no problem.
---
Follow up Libplanet's recent change: block hashes are now represented using `BlockHash` (instead of `BlockHash<SHA256>`).
See also:
https://github.com/planetarium/libplanet/issues/1192 …

Represent block hashes using `BlockHash` instead of `HashDigest<SHA256>`

---

NineChronicles.Headless/GraphTypes/StandaloneMutation.cs

This PR fixes #442 by changing the previous `AddressType` to `StringGraphType` so that `graphdoc` can read the default value as a string.

convert address type to string for graphdoc

---

Libplanet.Headless/Hosting/LibplanetNodeService.cs

This PR converts `LibplanetNodeService` from `IHostedService` implementation (direct) to `BackgroundService` to fix a bug where it blocks other services due to `StartAsync()` hasn't end before stopping.

Make LibplanetNodeService to BackgroundService

---

NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/TransferNCGHistoryTypeTest.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
NineChronicles.Headless/GraphTypes/TransferNCGHistoryType.cs
NineChronicles.Headless/TransferNCGHistory.cs

This pull request introduces `query.transferNCGHistories` query to show the list of histories of NCG transfer event.

feat(graphql): add `transferNCGHistories` query

---

Libplanet.Headless/Hosting/LibplanetNodeService.cs
Libplanet.Headless/ReducedStore.cs

In order to workaround the issue addressed in <https://github.com/planetarium/libplanet/issues/1313>, I added `ReducedStore` which omits `TxSuccess.UpdatedStates` at all.

ReducedStore

---

Libplanet.Headless/Hosting/LibplanetNodeService.cs
Libplanet.Headless/ReducedStore.cs

- Bumps lib9c (libplanet).
- Cherry pick https://github.com/planetarium/NineChronicles.Headless/commit/f2200628f6723b2fc57db5fae1c2406c7b909ca5 to use `ReducedStore` to save disk usage.

Hotfix (as v100048)

---

Libplanet.Headless/Hosting/LibplanetNodeService.cs
Libplanet.Headless/Hosting/LibplanetNodeServiceProperties.cs
NineChronicles.Headless.Tests/Common/ServiceBuilder.cs
NineChronicles.Headless.Tests/GraphTypes/GraphQLTestBase.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs

This patch use static peer implemented in Libplanet, and remove previous static peer checking task. Use `--static-peer {peer}` to use this option.

Use static peer in Liplanet

---

NineChronicles.Headless/GraphTypes/StandaloneMutation.cs

This PR forces `stageTx()` mutation to broadcast staged tx right away.

Fix to broadcast right away

---

Libplanet.Headless/Hosting/LibplanetNodeService.cs

This PR addresses an issue where `BlockRecvTimeout` was unintentionally incorrectly set to `BlockDownloadTimeout`.

Fix timeout property

---

Libplanet.Headless/BlockChainExtensions.cs
NineChronicles.Headless/BlockChainService.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs

This PR fixes a bug where `stateQuery`(and `BlockChainService` for gRPC) had ignored delayed renderer.
To accomplish it, I added `BlockChainExtensions` to provide `GetDelayedRenderer<T>()` for `BlockChain<T>`.

Fixes delayed rendering ignored

---

Libplanet.Headless/Hosting/LibplanetNodeService.cs
Libplanet.Headless/Hosting/LibplanetNodeServiceProperties.cs
NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs
README.md

Add `--minimum-broadcast-target` to the command line argument. Its default value is 10.

Configurable minimum broadcast target

---

NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs

This PR fixes a bug where the monster collection subscription wasn't updated when the monster collection had been terminated.

Fixes a bug for terminated monster collection

---

Libplanet.Headless/Hosting/LibplanetNodeService.cs
Libplanet.Headless/Hosting/LibplanetNodeServiceProperties.cs
NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs

Used `string` instead of `enum` because `LibplanetNodeServiceProperties<T>` is generic class and it's very annoying.

Add option for determining behavior when the chain's tip is stale

---

NineChronicles.Headless/GraphTypes/TransactionHeadlessQuery.cs
NineChronicles.Headless/GraphTypes/TxResult.cs
NineChronicles.Headless/GraphTypes/TxResultType.cs
NineChronicles.Headless/GraphTypes/TxStatusType.cs

Since libplanet 0.13. introduce new API `TxExecution` for transaction execution summary. This PR implement support `TxExecution` on GraphQL Query.

Introduce transaction result query

---

NineChronicles.Headless/NineChroniclesNodeService.cs

This PR bumps lib9c to introduce https://github.com/planetarium/lib9c/pull/551.
And it also adds a condition for a non-auth miner to skip auth block.

Prepare v100064

---

NineChronicles.Headless.Executable/appsettings.json

Should be merged after related [Lib9c PR](https://github.com/planetarium/lib9c/pull/558).
Additional logging information added to `Libplanet` as general QoL improvement.
Logging format `outputTemplate` in `appsettings.json` updated to relfect the changes in `Libplanet`.
---
[Libplanet PR](https://github.com/planetarium/libplanet/pull/1433)
[Lib9c PR](https://github.com/planetarium/lib9c/pull/558)
[NineChronicles.Headless PR](https://github.com/planetarium/NineChronicles.Headless/pull/626)

Libplanet logging change

---

.github/workflows/build.yml
NineChronicles.Headless.Executable.Tests/Commands/ChainCommandTest.cs
NineChronicles.Headless.Executable.Tests/Commands/Key/ConversionCommandTest.cs
NineChronicles.Headless.Executable.Tests/Commands/ValidationCommandTest.cs
NineChronicles.Headless.Executable/Commands/ChainCommand.cs
NineChronicles.Headless.Tests/Middleware/GraphQLSchemaMiddlewareTest.cs

Bunch of broken tests under Windows environment involving `\n` and `\r\n` fixed. Should now pass in both Linux and Windows.

Tests involving crlf made OS independent

---

NineChronicles.Headless/GraphTypes/ActivationStatusQuery.cs

Restore activation backward code for launcher E2E test & development node.

Restore activation backward

---

NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/ArenaInfoTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/WeeklyArenaStateTypeTest.cs
NineChronicles.Headless/GraphTypes/ActionMutation.cs
NineChronicles.Headless/GraphTypes/States/ArenaInfoType.cs
NineChronicles.Headless/NineChroniclesNodeService.cs
NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs
README.md

This PR bumps lib9c and adds `--tx-quota-per-signer` to apply https://github.com/planetarium/lib9c/pull/600.
And, it also resolves to compile errors on GraphQL query and mutation by reflecting removed props.

Bump lib9c

---

NineChronicles.Headless/GraphTypes/States/ArenaInfoType.cs

This PR bumps lib9c and restores AgentAddress and AvatarName for `ArenaInfoType`.

Restore GraphQL API

---

Dockerfile

This PR installs the `jq` processor in the `NineChronicles.Headless` Docker image so that it can be used as `Libplanet Explorer`'s backend on k8s.

install jq processor

---

NineChronicles.Headless.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Headless/GraphTypes/ActionMutation.cs

This PR reverts the `rankingMapAddress` parameter of `HackAndSlash` mutation in GQL back to `v100074` (Ref: https://github.com/planetarium/NineChronicles.Headless/blob/rc-v100074-b/NineChronicles.Headless/GraphTypes/ActionMutation.cs#L123-L127) to resolve https://github.com/planetarium/NineChronicles.Headless/issues/722.

add rankingMapAddress back to HAS mutation

---

NineChronicles.Headless.Executable.Tests/Commands/ChainCommandTest.cs
NineChronicles.Headless.Executable/Commands/ChainCommand.cs

This PR adds a chain `inspect` command to `print each block's mining time and tx stats (total tx, hack and slash, ranking battle, mimisbrunnr) of a given chain in csv format.`
Usage: 
- `dotnet run --project ./NineChronicles.Headless.Executable/ [COMMAND] [SUB-COMMAND] [STORE-TYPE] [STORE-PATH] [OFFSET] [LIMIT]`
Example Command:
- `dotnet run --project ./NineChronicles.Headless.Executable/ chain inspect rocksdb C:\Users\kidon\Desktop\9c-main-partition 2304922 10`
Example Output
```
Block Index,Mining Time (sec),Total Tx #,HAS #,RankingBattle #,Mimisbrunnr #
2304923,23.71,56,44,3,0
2304924,12.57,37,30,2,0
2304925,15.96,12,6,2,0
2304926,14.22,76,50,4,0
2304927,21.63,25,15,1,0
2304928,26.12,24,14,1,0
2304929,7.01,1,0,0,0
2304930,3.90,18,10,3,0
2304931,10.71,44,28,1,0
2304932,15.30,4,2,0,0 …
```

add chain inspect command

---

NineChronicles.Headless.Tests/DumbTransferAction.cs
NineChronicles.Headless.Tests/GraphTypes/TransactionHeadlessQueryTest.cs
NineChronicles.Headless/GraphTypes/TransactionHeadlessQuery.cs

Previously, we inquired in the store to check if the transaction was staged. However, this method was difficult to find a transaction when it was stale in the store. Therefore, we changed the chain to find the staged chain.
Now, return the value STAGING properly when the transaction is staged.

fix: find transaction from chain instead store

---

NineChronicles.Headless/Controllers/GraphQLController.cs

This PR extends key length from the game launcher to avoid `ArgumentOutOfRangeException` when the given key is shorter than 32 bytes.

Fix key length error

---

.github/workflows/build.yml
Dockerfile
Libplanet.Headless.Tests/Libplanet.Headless.Tests.csproj
Libplanet.Headless/Hosting/LibplanetNodeService.cs
Libplanet.Headless/Libplanet.Headless.csproj
NineChronicles.Headless.Executable.Tests/NineChronicles.Headless.Executable.Tests.csproj
NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj
NineChronicles.Headless.Tests/Controllers/GraphQLControllerTest.cs
NineChronicles.Headless.Tests/GraphQLStartupTest.cs
NineChronicles.Headless.Tests/GraphQLTestUtils.cs
NineChronicles.Headless.Tests/NineChronicles.Headless.Tests.csproj
NineChronicles.Headless/ActionEvaluationPublisher.cs
NineChronicles.Headless/Controllers/GraphQLController.cs
NineChronicles.Headless/HostBuilderExtensions.cs
NineChronicles.Headless/NineChronicles.Headless.csproj

This PR reverts #859 to downgrade from .NET 6 to .NET Core 3.1 due to performance degradation (more specifically, NineChronicles.Headless seems to have huge memory leak under .NET 6 env).

Revert 859

---

NineChronicles.Headless/GraphTypes/StandaloneQuery.cs

Since #556, `stateQuery` became to ignore `hash` argument and to use the latest tip hash from the delayed renderer in force.
This pull request fixes the bug to use `hash` argument correctly.

fix(graphql): correct `stateQuery`'s `hash` argument logic

---

NineChronicles.Headless.Tests/GraphTypes/TransactionHeadlessQueryTest.cs
NineChronicles.Headless/GraphTypes/TransactionHeadlessQuery.cs

feat(graphql): provide `nonce` argument when creating unsigned transaction

---

NineChronicles.Headless/BlockChainService.cs

- Set missing blockHash set.
- Avoid nre when value is null.

Avoid NRE in GetStateBulk

---

Dockerfile.arm64v8
Libplanet.Headless.Tests/Libplanet.Headless.Tests.csproj
NineChronicles.Headless.Executable.Tests/NineChronicles.Headless.Executable.Tests.csproj
NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj
NineChronicles.Headless.Tests/NineChronicles.Headless.Tests.csproj

This PR enables to build a Docker image(linux/amd64) from Apple Silicon (a.k.a. M1). To archive this, I added dedicated Dockerfile(`Dockerfile.arm64v8`) has different two things than regular `Dockerfile`.
1. `Dockerfile.arm64v8` uses `mcr.microsoft.com/dotnet/sdk:3.1-bullseye-arm64v8` instead of `mcr.microsoft.com/dotnet/sdk:3.1`. 
2. `Dockerfile.arm64v8` has `--platform linux/amd64` flags on `FROM` statement for runtime image.
Also, removing target platform redirection was needed because I still want to use 3.1 SDK on Apple Silicon.

Docker build for Apple Silicon

---

NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless/HostBuilderExtensions.cs
NineChronicles.Headless/NineChronicles.Headless.csproj
NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs
NineChronicles.Headless/Properties/RpcNodeServiceProperties.cs

`MagicOnion` supports to open `MagicOnion` RPC services' endpoints as HTTP1 with `MagicOnion.Server.HttpGateway` package. With them, we can run general HTTP1 tools like locust.
This pull request introduces 3 options:
- `--rpc-http-server`
- `--rpc-http-listen-port`
- `--rpc-http-listen-host`
To turn on this feature, it requires `--rpc-server` flag option.

Support options for gRPC HTTP1 endpoint

---

NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj

In .NET, there are two GC modes, *Workstation* and *Server*. You can see the difference between them at https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/workstation-server-gc.
This pull request makes the headless application to use Server GC mode.

Use `Server Garbage Collection` mode

---

NineChronicles.Headless/GraphQLService.cs
NineChronicles.Headless/Middleware/HttpCaptureMiddleware.cs

Originally there was no way to see GraphQL requests' bodies. This pull request makes the headless application capture all requests' bodies with its path and method.

Capture HTTP requests

---

NineChronicles.Headless.Executable.Tests/Commands/TxCommandTest.cs
NineChronicles.Headless.Tests/Common/Fixtures.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/ShardedShopStateV2TypeTest.cs
NineChronicles.Headless/GraphTypes/StateQuery.cs
NineChronicles.Headless/GraphTypes/States/Models/Order/OrderBaseType.cs
NineChronicles.Headless/GraphTypes/States/Models/Order/OrderDigestType.cs
NineChronicles.Headless/GraphTypes/States/ShardedShopStateV2Type.cs

Hi. I've faced the issue that the query `shop` does not returns any products. And I've been noticed that the `Shop` is not using any more and it's products are migrated to `ShardedShop` according to your working logs.
So I made a new query `shardedShop` to get products from `ShardedShop`. This query helps user get the `ShardedShop` they wants using parameters `itemSubType` and `nonce`. And I also added `ShopItemType.expiredBlockIndex` to know products' time to live.
@ipdae would you mind if I requested a review about this PR? I think this PR can resolve #508.
Thanks.

Add `shardedShop` in `stateQuery`.

---

NineChronicles.Headless/Middleware/HttpCaptureMiddleware.cs

It was failed in other middleware because the buffer was already read by `HttpCaptureMiddleware`.

fix(graphql): seek HTTP request buffer to begin

---

NineChronicles.Headless/Middleware/HttpCaptureMiddleware.cs

From #1046 PR...
I'm not sure that this pull request can solve all issues about RPC messaging but I tested it and played the game well after injecting DLLs based on the current branch.
I looked at messages the HTTP/2 seems harmed in logs and the game (local node mode) couldn't enter because RPC messaging doesn't work well. So I made it touch request body buffer only `HTTP/1.1` protocol and it seems succeeded.

fix(graphql): prevent to harm HTTP/2 (RPC) messages

---

.devcontainer/devcontainer.json

This turns on [docker-from-docker][1] in VS Code devcontainer so that we can build Docker images inside GitHub Codespaces.
[1]: https://github.com/microsoft/vscode-dev-containers/blob/main/script-library/docs/docker.md

Enable docker-from-docker in VS Code devcontainer

---

NineChronicles.Headless.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Headless/GraphTypes/ActionMutation.cs

To reduce transactions, those using the GraphQL endpoint can now add Play Count to boost their rewards.  The new Play Count variable is not required and defaults to 1.  Also added an action to Charge AP using GraphQL, which should close issue #968

Tarog star update graphql actions

---

NineChronicles.Headless.Executable/Program.cs

`Libplanet.Blockchain.Policies.VolatileStagePolicy` uses 180 minutes as default tx lifetime but the headless' option's default value was 60. This pull request makes 180 minutes, 3 hours as default value.

feat(cli): use default tx lifetime

---

NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless/GraphQLService.cs
NineChronicles.Headless/HostBuilderExtensions.cs
NineChronicles.Headless/Properties/GraphQLNodeServiceProperties.cs
NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs
NineChronicles.Headless/Properties/RpcNodeServiceProperties.cs

This pull request will close #1031, #1032.
It is not good practice to call the `UseKerstel` method twice times. It reset the previous state after calling it the second time. This pull request moves all initialization to `GraphQLService`.
And `--rpc-http-listen-host` and `--rpc-http-listen-port` are meaningless so this pull request removes them.

Correct `--rpc-http-server` option feature

---

.github/workflows/push_docker_image.yml

This makes the GitHub Actions to build & push a Docker image for each Git tag push, with a human-readable image tag name.  For example, if a tag named `v123456` is pushed, GitHub Actions will build and push the following tags and manifests:
- `planetariumhq/ninechronicles-headless:v123456-amd64` (tag)
- `planetariumhq/ninechronicles-headless:v123456-arm64v8` (tag)
- `planetariumhq/ninechronicles-headless:v123456` (manifest)
Note that `planetariumhq/ninechronicles-headless:git-*` tags will be still pushed too, but they are triggered by `branch` push events (not `tag` pushes).

Build Docker images for every tag

---

NineChronicles.Headless.Executable/Store/StoreTypeExtensions.cs

Currently, there is an issue that seems like a memory leak because the headless application goes to use more and more memory and meets OOM crash. When I researched about it with dotMemory snapshot. There were two problems. One was to keep the `RocksDB` instance on unmanaged memory by `_blockDbCache` and `_txDbCache`. And another one was to keep `BattleLog` and `AvatarState` in `RankingBattle` actions.
`_blockDbCache` and `_txDbCache` are variables typed as `LRUCache<TKey, TValue>` and it manages the cache nodes with parameterized cache size but it became a memory issue because the default cache size was 100 and it means 100 RocksDB instances will be alive over 100 days (there is a DB by an epoch, 1 day). Each `RocksDB` instance takes some memory for its index and filters. So the set of …

Decrease `RocksDBStore`'s `dbConnectionCacheSize` option

---

NineChronicles.Headless/GraphTypes/StandaloneMutation.cs

This PR adds an exception from `ValidateNextBlockTx` to error contexts for `StageTxV2()` mutation to help debug.

Add inner exception information for StageTxV2

---

Libplanet.Headless/Hosting/LibplanetNodeService.cs
Libplanet.Headless/Libplanet.Headless.csproj

Supports migration for RocksDB which removes column family. Please check https://github.com/planetarium/libplanet/pull/1862 for details.

Bump lib9c & Add store migration support

---

.github/workflows/release.yaml

Besides _v\*_ tag pushes, now every push to _rc-v\*_ branches also trigger Submodule Updater.
Note that this patch is almost equivalent to <https://github.com/planetarium/lib9c/pull/920> & <https://github.com/planetarium/NineChronicles/pull/1329>.

Trigger Submodule Updater on every push to rc-v* branches

---

Dockerfile
Dockerfile.amd64
Dockerfile.arm64v8

Currently, it doesn't install the `curl` package because the base image already has it. But we always want to stay in the state prepared for .NET 6 except for only the target framework. In the .NET 6 image, it doesn't have the `curl` package so this pull request makes it install the package manually.

Install curl

---

NineChronicles.Headless/GraphTypes/StandaloneMutation.cs

This prevents InvalidOperationException which occurs when trying to return null value on NonNullGraphType.
```
System.InvalidOperationException: Cannot return null for a non-null type. Field: stageTxV2, Type: TxId!.
at GraphQL.Execution.ExecutionStrategy.ValidateNodeResult(ExecutionContext context, ExecutionNode node) in /_/src/GraphQL/Execution/ExecutionStrategy.cs:line 566
at GraphQL.Execution.ExecutionStrategy.CompleteNode(ExecutionContext context, ExecutionNode node) in /_/src/GraphQL/Execution/ExecutionStrategy.cs:line 480
```
- ["Input errors", GraphQL.NET (Accessed 2022.02.25 KST)](https://graphql-dotnet.github.io/docs/getting-started/errors/#input-errors)

Prevent returning null on stageTxV2 mutation

---

NineChronicles.Headless.Executable/Commands/ActionCommand.cs

This pull request makes the `action *` commands print the raw action into stdout, not file as default. If the file path is not given, it will print the raw action into stdout. So the compatibility will be stayed.

feat(cli): print raw action into stdout as default

---

NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
NineChronicles.Headless/GraphTypes/ActionQuery.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs

This pull request introduces `actionQuery` query to generate actions with GraphQL API.
```graphql
query {
actionQuery {
stake(amount: BigInt!): ByteString;
claimStakeReward(avatarAddress: Address!): ByteString;
}
}
```

Introduce `query.actionQuery`

---

NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
NineChronicles.Headless/GraphTypes/ActionQuery.cs

Originally `ActionQuery`'s fields returned `IAction.PlainValue` not `PolymorphicAction<T>.PlainValue`. It makes users process one more time to wrap it. This pull request makes the fields return `PolymorphicAction<T>.PlainValue`.

Correct `ActionQuery`

---

NineChronicles.Headless/NineChroniclesNodeService.cs
NineChronicles.Headless/Properties/NetworkType.cs

Since this pull request, you can run headless without authorized mining.

Allow running headless without authorized mining

---

NineChronicles.Headless.Executable.Tests/Commands/KeyCommandTest.cs
NineChronicles.Headless.Executable.Tests/IO/StringIOConsole.cs
NineChronicles.Headless.Executable/Commands/KeyCommand.cs
NineChronicles.Headless.Executable/IO/IConsole.cs
NineChronicles.Headless.Executable/IO/StandardConsole.cs
NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/ScenarioTest.cs
NineChronicles.Headless.Tests/GraphTypes/TransactionHeadlessQueryTest.cs
NineChronicles.Headless/GraphTypes/ActionQuery.cs
NineChronicles.Headless/GraphTypes/CurrencyType.cs
NineChronicles.Headless/GraphTypes/StandaloneMutation.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
NineChronicles.Headless/GraphTypes/TransactionHeadlessQuery.cs

- resolve #1271 
- Import KeyCommand from Libplanet.
- Deprecate base64 using Transaction API.
- Update Transaction API with action query.

Update Transaction API with actionQuery Compatibility

---

NineChronicles.Headless.Executable.Tests/Commands/ActionCommandTest.cs
NineChronicles.Headless.Executable.Tests/Commands/TxCommandTest.cs
NineChronicles.Headless.Executable/Commands/ActionCommand.cs
NineChronicles.Headless.Executable/Commands/TxCommand.cs

The next direction should be focused on the `actionQuery` GraphQL API, but this pull request provides action commands related to `Stake` now.

Provides action commands related to `Stake`

---

NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/ScenarioTest.cs
NineChronicles.Headless/GraphTypes/ActionQuery.cs
NineChronicles.Headless/GraphTypes/CurrencyType.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs

- Fix hardcoded `NCG currency`. because NCG minter is different for each network settings.

Fix invalid currency in transferAsset action query

---

NineChronicles.Headless/GraphTypes/States/Models/Table/StakeRegularRewardSheetType.cs

When the table sheet exists, if the `orderedList` should be `[]`, empty array. And its elements also should be something not `null`. So this pull request fixes `StakeRegularRewardsSheet` type.

fix(graphql): correct non-nullable types

---

Libplanet.Headless/Hosting/LibplanetNodeService.cs
Libplanet.Headless/Hosting/LibplanetNodeServiceProperties.cs
NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless.Tests/Common/ServiceBuilder.cs
NineChronicles.Headless.Tests/GraphTypes/GraphQLTestBase.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs

Program's `staticPeerStrings` argument now replaced with `consensusPeerStrings` which represents the list of peers joining PBFT consensus.

Configurable consensus peer

---

NineChronicles.Headless.Executable/Commands/TxCommand.cs

This commit was merged into the `previewnet` branch as hotfix through #1335. It was a hotfix so I opened a new pull request to apply it also to other branches.

Cherry-pick: Remove useless output

---

NineChronicles.Headless/GraphTypes/TransactionHeadlessQuery.cs
NineChronicles.Headless/GraphTypes/TxResult.cs
NineChronicles.Headless/GraphTypes/TxResultType.cs

This pull request introduces new fields `exceptionName` and `exceptionMetadata` in `TxResultType`.
```graphql
type TxResultType {
txStatus: TxStatus!
blockIndex: Long
blockHash: String
+ exceptionName: String
+ exceptionMetadata: String
}
```

Introduce `TxResultType.exception..` fields

---

NineChronicles.Headless.Tests/GraphTypes/States/Models/CrystalMonsterCollectionMultiplierRowTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/CrystalMonsterCollectionMultiplierSheetTypeTest.cs
NineChronicles.Headless/GraphTypes/StateQuery.cs
NineChronicles.Headless/GraphTypes/States/Models/Table/CrystalMonsterCollectionMultiplierRowType.cs
NineChronicles.Headless/GraphTypes/States/Models/Table/CrystalMonsterCollectionMultiplierSheetType.cs

It introduces `query.stateQuery.crystalMonsterCollectionMultiplierSheet`.
```graphql
query {
stateQuery {
crystalMonsterCollectionMultiplierSheet {
orderedList {
level
multiplier
}
}
}
}
```

feat(graphql): introduce `CrystalMonsterCollectionMultiplierSheet` type

---

NineChronicles.Headless.Tests/Common/Fixtures.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/AvatarStateTypeTest.cs
NineChronicles.Headless/GraphTypes/StateQuery.cs
NineChronicles.Headless/GraphTypes/States/AgentStateType.cs
NineChronicles.Headless/GraphTypes/States/AvatarStateType.cs

This pull request introduces the `int`-typed `AvatarStateType.index` field to present the index among its agent's avatar addresses. Please see also fixtures and the test. Also I'm not sure about naming, so if you have an opinion, feel free to comment.

feat(graphql): introduce `AvatarStateType.index` field

---

Libplanet.Headless/Hosting/LibplanetNodeService.cs
NineChronicles.Headless.Executable.Tests/Commands/ChainCommandTest.cs
NineChronicles.Headless.Executable.Tests/Store/IStoreExtensionsTest.cs
NineChronicles.Headless.Executable.Tests/Store/StoreTypeExtensionsTest.cs
NineChronicles.Headless.Executable/Commands/ChainCommand.cs
NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless.Executable/Store/StoreType.cs
NineChronicles.Headless.Executable/Store/StoreTypeExtensions.cs
README.md

resolves #1438 
---
Add `memory` type into `--store-type` option to use `MemoryStore` as blockchain data storage.
- I did not add MemoryStore to `ChainCommandTest` type test because MemoryStore vanishes when it is disposed.
- See comment in `ChainCommandTest.cs`

Add `MemoryStore` to `--store-type` option

---

NineChronicles.Headless.Executable.Tests/Commands/ChainCommandTest.cs
NineChronicles.Headless.Executable/Commands/ChainCommand.cs

This PR adds a `chain command` that prunes the `states` of the 9c store (similar to `NineChronicles.Snapshot`).
With this command, downloading a new snapshot when the `states` size is too large is no longer needed.
One issue is that this command takes close to `30 mins` to complete in our current 9c store, which has an initial `states` size of about `4GB`. I'll add a more detailed issue on the `libplanet` repo.

Add `prune-states` command

---

NineChronicles.Headless.Executable/Commands/GenesisCommand.cs
README.md
config.json.example

The old genesis command needs bunch of outdated configs and files.
This PR enhances genesis command.
- Removes unused configs and restruct `config.json`.
- Write genesis instruction in `README`

Rebuild genesis command

---

NineChronicles.Headless.Executable.Tests/Commands/GenesisCommandTest.cs

This PR makes `GenesisCommandTest` passes.
- Apply new genesis config structure to unittest
- Only `DataConfig` is required, so change expected exception result of one testcase.
Sorry for breaking integrities 🙏

Make GenesisCommandTest passes: resolve #1487

---

NineChronicles.Headless.Tests/GraphTypes/TransactionHeadlessQueryTest.cs
NineChronicles.Headless/GraphTypes/TransactionHeadlessQuery.cs

This PR reverts the `transactionResult` query that was changed in https://github.com/planetarium/NineChronicles.Headless/pull/1492 to use the original query format. Therefore, services using this query won't have to make adjustments.
```
query{
transaction{
transactionResult(txId:"0b72e3a5ddedee0d65e42720da345b5475a5b1e6d6496dfa777233bc9fac885f"){
txStatus
exceptionName
}
}
}
```
P.S. https://github.com/planetarium/NineChronicles.Headless/blob/development/NineChronicles.Headless/GraphTypes/TxResultType.cs and https://github.com/planetarium/NineChronicles.Headless/blob/development/NineChronicles.Headless/GraphTypes/TxStatusType.cs should be deprecated or deleted so I'll create a separate issue.

use explorer graphtype for txResult and txStatus

---

Libplanet.Headless/Hosting/LibplanetNodeServiceProperties.cs
Libplanet.Headless/ReducedStore.cs
NineChronicles.Headless.Executable/Commands/ActionCommand.cs
NineChronicles.Headless.Tests/Common/Fixtures.cs
NineChronicles.Headless.Tests/Common/ServiceBuilder.cs
NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/GraphQLTestBase.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneSubscriptionTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/AgentStateTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/FungibleAssetValueTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/StakeStateTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/TransferNCGHistoryTypeTest.cs
NineChronicles.Headless/DifferentAppProtocolVersionEncounter.cs
NineChronicles.Headless/GraphQLServiceExtensions.cs
NineChronicles.Headless/HostBuilderExtensions.cs
NineChronicles.Headless/NineChroniclesNodeService.cs

[Recently, maximum supply cap and total supply tracking was introduced in `Currency` in Libplanet.](https://github.com/planetarium/libplanet/pull/2200) This introduced changes in `IAccountStateDelta` interface and how `Currency` is defined. [lib9c#1308](https://github.com/planetarium/lib9c/pull/1308) incorporates the API changes to lib9c, and this PR applies the changes to NineChronicles.Headless.
Resolution order: planetarium/libplanet#2225 -> planetarium/lib9c#1308 -> planetarium/NineChronicles.Headless#1497 & planetarium/NineChronicles#1838

Bump lib9c and incorporate `Currency` API changes

---

Libplanet.Headless/Hosting/LibplanetNodeServiceProperties.cs
Libplanet.Headless/ReducedStore.cs
NineChronicles.Headless.Executable/Commands/ActionCommand.cs
NineChronicles.Headless.Tests/Common/Fixtures.cs
NineChronicles.Headless.Tests/Common/ServiceBuilder.cs
NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/GraphQLTestBase.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneSubscriptionTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/AgentStateTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/FungibleAssetValueTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/StakeStateTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/TransferNCGHistoryTypeTest.cs
NineChronicles.Headless/DifferentAppProtocolVersionEncounter.cs
NineChronicles.Headless/GraphQLServiceExtensions.cs
NineChronicles.Headless/HostBuilderExtensions.cs
NineChronicles.Headless/NineChroniclesNodeService.cs

This reverts commit 693c0e59f33fe0dccfd8d696c609776386f3417b, reversing
changes made to 216da5b93ffb17ce72bb7a6b082a919fa4d5ed3f.
~Also, this PR should be bumped after https://github.com/planetarium/lib9c/pull/1342~ bumped by https://github.com/planetarium/NineChronicles.Headless/pull/1526/commits/a1d763ebedc523a0c7d9cd7047d6d6efbe8f592a.

Revert "Merge pull request #1497 from tkiapril/lib9c-pr-1308"

---

NineChronicles.Headless.Tests/GraphTypes/States/Models/AgentStateTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/AvatarStateTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/StakeStateTypeTest.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
NineChronicles.Headless/GraphTypes/StateQuery.cs
NineChronicles.Headless/GraphTypes/States/AgentStateType.cs
NineChronicles.Headless/GraphTypes/States/AvatarStateType.cs
NineChronicles.Headless/GraphTypes/States/StakeStateType.cs
NineChronicles.Headless/GraphTypes/States/StateContext.cs

This pull request make `StakeStateType.claimableBlockIndex` return the block index branched by the `BlockPolicySource.V100290ObsoleteBlockIndex` like lib9c `StakeState.IsClaimable` does.
I requested reviews to @longfin and @sonohoshi because they reviewed lib9c PR https://github.com/planetarium/lib9c/pull/1303 (for `StakeStateType.claimableBlockIndex`)
And I request reviews to @ipdae and @area363 too because they are very familiar with GraphQL codes. (for `StateContext.BlockIndex` part)

Branch `StakeStateType.claimableBlockIndex` by block index

---

NineChronicles.Headless/GraphTypes/KeyStoreMutation.cs
NineChronicles.Headless/GraphTypes/KeyStoreType.cs
NineChronicles.Headless/GraphTypes/StandaloneMutation.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs

This pull request is related with #1567 discussion.
I think we should recommend to use `planet key` command to handle private key. This pull request deprecates the GraphQL fields and types:
- `KeyStoreType` type
- `KeyStoreMutation` type
- `mutation.keyStore` field
- `query.keyStore` field

feat(graphql): deprecate GraphQL APIs to handle private key

---

NineChronicles.Headless.Executable/Configuration.cs
NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless.Executable/appsettings.json
README.md

Now we can use `appsettings.json` to run headless.
`appsettings.json` can be local file or web storage like S3.
We have to pass a bunch of command line options to run headless server so far and this is very inconvenient work.
Read headless launch options from `appsettings.json`.
The old CLI options are still alive and this will overwrite options from `appsettings.json`
---
Related issue: https://github.com/planetarium/NineChronicles.Headless/issues/1556

Use appsettings file to run headless server

---

NineChronicles.Headless.Executable.Tests/ProgramTest.cs

The ports set in `appsettings.json` and `ProgramTest.cs` are conflicted to fail connection test.
I moved unittest port to so anyone who runs their own local full node can run unittest without any problem.

Change test port not to conflict with 'appsettings.json'

---

NineChronicles.Headless.Executable/Commands/ChainCommand.cs

This PR partially addresses https://github.com/planetarium/NineChronicles.Headless/issues/1575.
It removes the `stateKeyValueStore.ListKeys()` method which took really long (approximately 1 hour) when tested on a state store that's around 600GB.
This method is only used for debugging so it doesn't affect the actual command.

remove ListKeys method in `PruneStates`

---

NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs

There is a bug where the `query.transferNCGHistories` GraphQL query returns histories of the latest `transfer_asset*` action. That means it returns only `transfer_asset3`'s histories though `transfer_asset2` can be still used yet.
This pull request bumps Lib9c to use https://github.com/planetarium/lib9c/pull/1407 and applies it.

Make `transferNCGHistories` use common interface of `transfer_asset*` actions

---

NineChronicles.Headless/ActionEvaluationPublisher.cs

This PR adjusts two parts on `ActionEvaluationPublisher`.
- Fixed a bug where action rendering had been stacked 
- Forced asynchronous broadcasting to avoid delaying whole block synchronization.

Fix ActionEvalautionPublisher for concurrency

---

NineChronicles.Headless.Executable/Commands/ReplayCommand.cs

This pull request resolves #1632.
The `replay` command has the `blocks` commend inside.
You can replay blocks!
```cs
[Command(Description = "Evaluate blocks and check state root hash")]
public int Blocks(
[Option('s', Description = "An absolute path of block storage.(rocksdb)")]
string storePath,
[Option('i', Description = "Target start block height. Tip as default. (Min: 1)")]
long startIndex = 1,
[Option('e', Description = "Target end block height. Tip as default. (Min: 1)" +
"If not set, same as START-INDEX.")]
long? endIndex = null,
[Option('r', Description = "Repeat count. (Min: 1)" +
"If not set, default is 1.")]
int repeatCount = 1,
[Option('v', Description = "Verbose mode.")]
bool verbose = false,
[Option('o', Description = "The path of output file.")]
string outputPath = "")
{
// …
```

Introduce command `replay blocks`

---

NineChronicles.Headless.Tests/GraphTypes/GraphQLTestBase.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneSubscriptionTest.cs
NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs
NineChronicles.Headless/StandaloneContext.cs

This PR adds `.Sample()` operator on `StandaloneContext.DifferentAppProtocolVersionEncounterSubject` to throttle events.

Throttle DAP subscription

---

NineChronicles.Headless/GraphTypes/NodeStatus.cs
NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs

This PR is a hotfix to address delayed block sync due to #1695 and #1694 .  it isn't a direct fix but it loosens a delay by GQL subscriptions via the two below approaches.
1. Specifies rendering thread for subscriptions in `StandaloneSubscription`, using `ObserveOn()`.
2. In `StandaloneSubscription.RenderBlock`, it introduces `AsParallel()` and `ForAll()` to enable parallelism.
Also, it adds a GQL query to debug this symptom and maintain versions.

Release v100321-3

---

NineChronicles.Headless/GraphQLService.cs
NineChronicles.Headless/GraphQLServiceExtensions.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs

This pull request enables `/graphql/explorer` endpoint and deprecates `query.chainQuery` (not obsolete).
This pull request closes #1690

Separate libplanet explorer into a new endpoint

---

NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.ActionTxQuery.cs
NineChronicles.Headless/GraphTypes/ActionTxQuery.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs

This PR adds `timestamp` argument to `actionTxQuery` GraphQL query to specify `Transaction<T>.Timestamp`.

Add timestamp to actionTxQuery

---

NineChronicles.Headless.Executable.Tests/Commands/ActionCommandTest.cs
NineChronicles.Headless.Executable.Tests/Commands/TxCommandTest.cs
NineChronicles.Headless.Executable/Commands/ActionCommand.cs
NineChronicles.Headless.Executable/Commands/TxCommand.cs

- Bump `lib9c`
- Expand `ActionCommand.ClaimStakeReward()` method
- Consider all versions of the `ClaimStakeReward` actions on `TxCommand.Sign()` method
- https://github.com/planetarium/lib9c/pull/1530
- https://github.com/planetarium/lib9c/pull/1533

Bump `lib9c` and Apply the changes related to `ClaimStakeReward`

---

NineChronicles.Headless.Executable/Commands/ReplayCommand.cs

- Fix minor bug of message.
- Fix messages more readable.
before
```
dotnet run -- replay blocks \
-s ~/Downloads/FileZilla/9c-snapshots/20221110031332_9c-main-snapshot-symlink/ \
-i 5371565 \
-e 5371570 \
-o ./ \
-v
Replay blocks start from #5371565 to #5371570.(range: 6, repeat: 1)
Local block protocol version(bpv): 3
- block #5371565 evaluating start: bpv(3), bloc-hash(e082cc5db1c56ec6dfa2371137bcf9b7f6e87ad3c6cae8ec492fa1ee0c4e42d0), state-root-hash(2196a6f816fc21c400cf239162739462154f5ee565e9475dc703049488604821), tx-count(0)
-- repeat #1 / 1(o)
--- action evaluation #1 tx-id(), action-type("RewardGold"), no-exception
- block #{block.Index} evaluating end successfully.
- block #5371566 evaluating start: bpv(3), bloc-hash(a4108314b9ac82c90f86018664586636d785369b0c2a9b8c36b18dcc8f4a5a1a …
```

Fix output messages of replay command

---

NineChronicles.Headless.Executable.sln

I think there is no reason to build *Lib9c.Tests* in *NineChronicles.Headless* project.

Remove Lib9c.Tests from solution

---

NineChronicles.Headless.Executable/Commands/GenesisCommand.cs
NineChronicles.Headless.Executable/Configuration.cs
NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj
NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless.Tests/GraphTypes/GraphQLTestBase.cs
NineChronicles.Headless/ActionEvaluationPublisher.cs
NineChronicles.Headless/BlockChainService.cs
NineChronicles.Headless/HostBuilderExtensions.cs
NineChronicles.Headless/NineChronicles.Headless.csproj

- Options added
- SentryDsn
- Prevent other local nodes from sending traces
- SentrySampleRate
- Inject `ConcurrentDictionary<string, ITransaction>` to pass trace from blockchain service to actionEvaluationPublisher
- Exclude too often errors, not to deplete sentry quota
ref) https://sentry.io/organizations/planetariumhq/performance/9c-headless:25f95a3f56044e16b2c1a90a7dc4be97/?project=6197051&query=transaction.duration%3A%3C15m&referrer=performance-transaction-summary&transaction=Nekoyume.Action.HackAndSlash&unselectedSeries=p100%28%29

Introduce Sentry Tracing on Action Execute

---

.github/workflows/build.yml
.github/workflows/deploy_gh_pages.yml
.github/workflows/deploy_ghpackages_docker.yml
.github/workflows/lint.yml
.github/workflows/push_docker_image.yml
.github/workflows/release.yaml

This pull request updates deprecated actions, used `node12` environment, `actions/checkout` and `actions/setup-dotnet`.
See also https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

ci(gh-actions): update actions used node12

---

NineChronicles.Headless.Executable/Commands/GenesisCommand.cs
README.md

Since #1602, `Lib9c.Tools` commands were moved from the `lib9c` repository to the `NineChronicles.Headless.Exectuable` command project. And `Lib9c.Tools` became deprecated. But the `NineChronicles.Headless` project still has references to `Lib9c.Tools`. This pull request removes them.

Unlink Lib9c.Tools to prepare deprecation

---

NineChronicles.Headless.Executable.Tests/Commands/ChainCommandTest.cs
NineChronicles.Headless.Executable/Commands/ChainCommand.cs
README.md

This PR adds the `snapshot` feature to the `headless chain command`, mostly taken from https://github.com/planetarium/NineChronicles.Snapshot. This should make maintenance much easier.

Add snapshot feature to chain command

---

NineChronicles.Headless.Executable.Tests/Commands/ActionCommandTest.cs

This pull request fixes `NineChronicles.Headless.Executable.Tests.Commands.ActionCommandTest.List` test.

Correct actions count

---

.github/workflows/lint.yml
NineChronicles.Headless.Executable/appsettings-schema.json
NineChronicles.Headless.Executable/appsettings.internal.json
NineChronicles.Headless.Executable/appsettings.json
NineChronicles.Headless.Executable/appsettings.mainnet.json
NineChronicles.Headless.Executable/appsettings.previewnet.json

This pull request resolves #1820. There is [JSON Schema][json-schema-spec] to make available defining JSON's schema. With the schema, you can see the hint or error messages:
Hint:
Error:
And it introduces the GitHub Actions workflow to make our configuration files follow the schema well.
Now, the schema supports only for `DynamicActionTypeLoader` feature.
[json-schema-spec]: https://json-schema.org

Introduce JSON schema for appsettings.json

---

Libplanet.Headless.Tests/Hosting/LibplanetNodeServiceTest.cs
Libplanet.Headless/Hosting/LibplanetNodeService.cs
Libplanet.Headless/Hosting/LibplanetNodeServiceProperties.cs
NineChronicles.Headless.Executable/ActionTypeLoaderConfiguration.cs
NineChronicles.Headless.Executable/Configuration.cs
NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless.Executable/StaticActionTypeLoaderConfiguration.cs
NineChronicles.Headless.Executable/appsettings-schema.json
NineChronicles.Headless.Tests/Common/ServiceBuilder.cs
NineChronicles.Headless.Tests/Common/StaticActionTypeLoaderSingleton.cs
NineChronicles.Headless.Tests/Controllers/GraphQLControllerTest.cs
NineChronicles.Headless.Tests/GraphTypes/GraphQLTestBase.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Headless/NineChroniclesNodeService.cs
NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs

This pull request introduces a new configuration for `StaticActionTypeLoader`. You can reference `appsettings-schema.json` and try these changes by editing `appsettings.mainnet.json` in the environment to support JSON schema (e.g., vscode).
For StaticActionTypeLoader
```json
{
"Headless": {
"ActionTypeLoader": {
"StaticActionTypeLoader": {
"Assemblies": ["/path/to/dllA", "/path/to/dllB"]
}
}
}
}
```

Intorduce configuration for `StaticActionTypeLoader`

---

NineChronicles.Headless/ActionEvaluationPublisher.cs
NineChronicles.Headless/GraphQLService.cs
NineChronicles.Headless/HostBuilderExtensions.cs
NineChronicles.Headless/NineChronicles.Headless.csproj
NineChronicles.Headless/NineChroniclesNodeService.cs

This pull request makes `NineChronicles.Headless` provide metrics, which `9c-headless-metric-gql-aggregator` has been providing.
You can fetch the metrics in the `http://localhost:5000/metrics` endpoint when you use `appsettings.development.json`.
This pull request will close https://github.com/planetarium/9c-headless-metric-gql-aggregator/issues/3 and archive the project when applied successfully.
You can add a job with nodes you want to gather metrics.
```yaml
- job_name: ninechronicles-headless-metrics-aggregator
metrics_path: /metrics
scrape_interval: 10s
scrape_timeout: 5s
static_configs:
- targets:
- <ENDPOINT>
tls_config:
insecure_skip_verify: true
```
------

Provide metrics for NineChronicles node 

---

NineChronicles.Headless.Tests/GraphTypes/ActionQueryFieldTypes/ActionQueryFieldTypeInheritor.cs
NineChronicles.Headless.Tests/GraphTypes/ActionQueryFieldTypes/ActionQueryFieldTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/ActionQueryFieldTypes/PetEnhancementFieldTypeTest.cs
NineChronicles.Headless/GraphTypes/ActionQuery.cs
NineChronicles.Headless/GraphTypes/ActionQueryFieldTypes/ActionQueryFieldType.cs
NineChronicles.Headless/GraphTypes/ActionQueryFieldTypes/PetEnhancementFieldType.cs
NineChronicles.Headless/NineChronicles.Headless.csproj

- Add `ActionQueryFieldType`
- Add `PetEnhancementFieldType`
- Apply `petEnhancement` action query
```graphql
query {
actionQuery {
petEnhancement(
avatarAddress: "0xe56d432da2032f6C851943b76C4a41815baaBB54",
petId: 1,
targetLevel: 1)
}
}
```
```json
{
"data": {
"actionQuery": {
"petEnhancement": "6475373a747970655f69647531353a7065745f656e68616e63656d656e7475363a76616c7565736475313a6132303ae56d432da2032f6c851943b76c4a41815baabb5475323a696431363acd57608e9f06b34f9f279651d9ba9aa675313a7075313a3175313a7475313a316565"
}
},
"extensions": {}
}
```
```python
>>> bytes.fromhex("6475373a747970655f69647531353a7065745f656e68616e63656d656e7475363a76616c7565736475313a6132303ae56d432da2032f6c851943b76c4a41815baabb5475323a696431363acd57608e9f06b34f9f279651d9ba9aa675313a7075313a3175313a7475313a316565") …
```

feat: `PetEnhancement` graphQL query

---

NineChronicles.Headless/Middleware/HttpCaptureMiddleware.cs

Updating gql logger level to `Information` to pull metrics in Cloudwatch.

update gql logger level

---

.versions.toml
Docs/PLUGGABLE_LIB9C.md
prepare-pluggable-lib9c.py

This pull request introduces a script to Lib9c DLLs of multiple versions easily with the configuration.
You can see the help message in `Docs/PLUGGABLE_LIB9C.md` file.
```
[versions]
$version_name = { ref = "$git_ref" }
// e.g. v100371 = { ref = "v100371" }
[config]
output_path = "$output_path"
repository_url = "$repository_url"  // URL to clone the Lib9c repository.
```

Introduce script to build multiple Lib9c versions for pluggable lib9c

---

NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless/HostBuilderExtensions.cs

Fix `OpenTelemetry` to be added not only on rpc, but also on non-rpc.

Track meter always

---

NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless.Executable/appsettings.internal.json
NineChronicles.Headless.Executable/appsettings.json
NineChronicles.Headless.Executable/appsettings.mainnet.json

Deprecate metrics log and add rendered json log for loki
- mount this path from k8s
- fluentbit will fetch json logs and export to loki
ref) https://github.com/planetarium/9c-k8s-config/pull/307/files#diff-7727ff4c04d5feffdcda5409ff8c421d4873185b7be7ede8c03371d11f1fbe92

add additional json log output for loki

---

NineChronicles.Headless/NineChroniclesNodeService.cs

Since injection of `Swarm<T>` to `standaloneContext` is missing, queries `nodeState.peers` and `nodeState.validators` was broken.
Fixed it with `Swarm<T>` injection.

Inject Swarm<T> to StandaloneContext

---

NineChronicles.Headless/GraphTypes/ActionQuery.DevEx.cs

DevEx function returns nullable but action must not be null.

Action should not be null

---

NineChronicles.Headless/NineChroniclesNodeService.cs

This pull request makes 9c-headless support more metrics that 9c-headless-metric-gql-aggregator supports:
- `ninechronicles_tx_count`
- `ninechronicles_block_interval`
See also #1872

Support additional metrics

---

.github/workflows/push_docker_image.yml
Dockerfile.lib9c-stateservice
Lib9c.StateService/Controllers/RemoteEvaluationController.cs
Lib9c.StateService/Lib9c.StateService.csproj
Lib9c.StateService/Program.cs
Lib9c.StateService/Properties/launchSettings.json
Lib9c.StateService/appsettings.Development.json
Lib9c.StateService/appsettings.json
Libplanet.Extensions.RemoteActionEvaluator.Tests/ActionEvaluationSerializerTest.cs
Libplanet.Extensions.RemoteActionEvaluator.Tests/Libplanet.Extensions.RemoteActionEvaluator.Tests.csproj
Libplanet.Extensions.RemoteActionEvaluator.Tests/Usings.cs
Libplanet.Extensions.RemoteActionEvaluator/AccountStateDelta.cs
Libplanet.Extensions.RemoteActionEvaluator/AccountStateDeltaMarshaller.cs
Libplanet.Extensions.RemoteActionEvaluator/ActionContext.cs
Libplanet.Extensions.RemoteActionEvaluator/ActionContextMarshaller.cs
Libplanet.Extensions.RemoteActionEvaluator/ActionEvaluation.cs
Libplanet.Extensions.RemoteActionEvaluator/ActionEvaluationMarshaller.cs
Libplanet.Extensions.RemoteActionEvaluator/AssemblyInfo.cs
Libplanet.Extensions.RemoteActionEvaluator/Libplanet.Extensions.RemoteActionEvaluator.csproj
Libplanet.Extensions.RemoteActionEvaluator/PreEvaluationBlockMarshaller.cs
Libplanet.Extensions.RemoteActionEvaluator/Random.cs
Libplanet.Extensions.RemoteActionEvaluator/RemoteActionEvaluator.cs
Libplanet.Extensions.RemoteActionEvaluator/RemoteBlockChainStates.cs
Libplanet.Extensions.RemoteActionEvaluator/RemoteEvaluationRequest.cs
Libplanet.Extensions.RemoteActionEvaluator/RemoteEvaluationResponse.cs
Libplanet.Extensions.RemoteActionEvaluator/TransactionMarshaller.cs
Libplanet.Headless/Hosting/LibplanetNodeService.cs
Libplanet.Headless/Libplanet.Headless.csproj
NineChronicles.Headless.Executable.sln

The `RemoteActionEvaluator` implements the `Libplanet.Action.IActionEvaluator` interface. It is to assume the situation that Libplanet cannot access Lib9c's DLL directly. extremely.

Implement `RemoteActionEvaluator`

---

Libplanet.Extensions.ActionEvaluatorCommonComponents.Tests/ActionEvaluationSerializerTest.cs
Libplanet.Extensions.ActionEvaluatorCommonComponents.Tests/Libplanet.Extensions.ActionEvaluatorCommonComponents.Tests.csproj
Libplanet.Extensions.ActionEvaluatorCommonComponents.Tests/Usings.cs
Libplanet.Extensions.ActionEvaluatorCommonComponents/AccountStateDelta.cs
Libplanet.Extensions.ActionEvaluatorCommonComponents/AccountStateDeltaMarshaller.cs
Libplanet.Extensions.ActionEvaluatorCommonComponents/ActionContext.cs
Libplanet.Extensions.ActionEvaluatorCommonComponents/ActionContextMarshaller.cs
Libplanet.Extensions.ActionEvaluatorCommonComponents/ActionEvaluation.cs
Libplanet.Extensions.ActionEvaluatorCommonComponents/ActionEvaluationMarshaller.cs
Libplanet.Extensions.ActionEvaluatorCommonComponents/Libplanet.Extensions.ActionEvaluatorCommonComponents.csproj
Libplanet.Extensions.ActionEvaluatorCommonComponents/PreEvaluationBlockMarshaller.cs
Libplanet.Extensions.ActionEvaluatorCommonComponents/Random.cs
Libplanet.Extensions.ActionEvaluatorCommonComponents/TransactionMarshaller.cs
Libplanet.Extensions.ForkableActionEvaluator.Tests/ForkableActionEvaluatorTest.cs
Libplanet.Extensions.ForkableActionEvaluator.Tests/Libplanet.Extensions.ForkableActionEvaluator.Tests.csproj
Libplanet.Extensions.ForkableActionEvaluator.Tests/Usings.cs
Libplanet.Extensions.ForkableActionEvaluator/ForkableActionEvaluator.cs
Libplanet.Extensions.ForkableActionEvaluator/HardForkRouter.cs
Libplanet.Extensions.ForkableActionEvaluator/Libplanet.Extensions.ForkableActionEvaluator.csproj
Libplanet.Extensions.RemoteActionEvaluator/Libplanet.Extensions.RemoteActionEvaluator.csproj
Libplanet.Extensions.RemoteActionEvaluator/RemoteActionEvaluator.cs
NineChronicles.Headless.Executable.sln

This pull request introduces `ForkableActionEvaluator`, a new `IActionEvaluator` implementation.
It receives `IActionEvaluator`s with the range of block index. The range is always presented as a closed interval[^1]. And the ranges must cover all long ranges (0 ~ 9223372036854775807).
[^1]: https://en.wikipedia.org/wiki/Interval_(mathematics)#Terminology

Introduce `ForkableActionEvaluator`

---

Lib9c.StateService/Controllers/RemoteEvaluationController.cs
Libplanet.Headless/Hosting/ActionEvaluatorType.cs
Libplanet.Headless/Hosting/DefaultActionEvaluatorConfiguration.cs
Libplanet.Headless/Hosting/ForkableActionEvaluatorConfiguration.cs
Libplanet.Headless/Hosting/IActionEvaluatorConfiguration.cs
Libplanet.Headless/Hosting/LibplanetNodeService.cs
Libplanet.Headless/Hosting/LibplanetNodeServiceProperties.cs
Libplanet.Headless/Hosting/RemoteActionEvaluatorConfiguration.cs
Libplanet.Headless/Libplanet.Headless.csproj
NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless.Executable/appsettings-schema.json
NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs

This pull request's purpose is to provide a way to configure `ActionEvaluator` with `appsettings.json` configuration file. If you want to run `ForkableActionEvaluator` with `ActionEvaluator` (0 ~ 7M blocks) and `RemoteActionEvaluator` (7000001 ~ `long.MaxValue`), you can write the configuration like below:
```json
"ActionEvaluator": {
"type": "ForkableActionEvaluator",
"pairs": [
{
"range": {
"start": 0,
"end": 7000000
},
"actionEvaluator": {
"type": "Default"
}
},
{
"range": {
"start": 0,
"end": 7000000
},
"actionEvaluator": {
"type": "RemoteActionEvaluator",
"stateServiceEndpoint": "http://localhost:5157/evaluation"
}
}
]
}
```
Or, if you want to organize Pluggable Lib9c with `ForkableActionEvaluator` and `RemoteActionEvaluator`, it will be like the below:
```json
"ActionEvaluator": { …
```

Support `ActionEvaluator` configuration

---

NineChronicles.Headless/GraphQLService.cs

as we parse every logs using JSON parser from fluentbit, we should make stderr logs follow global Logging config.

Fix gql error format to follow global Logger

---

.github/workflows/build.yml
NineChronicles.Headless.Executable/Program.cs

Now, it changes the jobs' names but they are required jobs. When the `v200020-1` released, the branch rule should be updated.

ci(gh-actions): build and test with DevEx configuration too

---

Lib9c.StateService/Controllers/RemoteEvaluationController.cs
Lib9c.StateService/Lib9c.StateService.csproj
Lib9c.StateService/Program.cs
Lib9c.StateService/RemoteEvaluationRequest.cs
Lib9c.StateService/RemoteEvaluationResponse.cs
Libplanet.Extensions.RemoteActionEvaluator/RemoteActionEvaluator.cs
Libplanet.Extensions.RemoteBlockChainStates/Libplanet.Extensions.RemoteBlockChainStates.csproj
Libplanet.Extensions.RemoteBlockChainStates/RemoteBlockChainStates.cs
NineChronicles.Headless.Executable.sln

- Separate `RemoteBlockChainStates` implementation.
- Move requests and response model to `Lib9c.StateService` project.

Reorganize projects related to `Lib9c.StateService`

---

Lib9c.StateService.Shared/Lib9c.StateService.Shared.csproj
Lib9c.StateService.Shared/RemoteEvaluationRequest.cs
Lib9c.StateService.Shared/RemoteEvaluationResponse.cs
Lib9c.StateService/Controllers/RemoteEvaluationController.cs
Lib9c.StateService/Lib9c.StateService.csproj
Libplanet.Extensions.RemoteActionEvaluator/Libplanet.Extensions.RemoteActionEvaluator.csproj
Libplanet.Extensions.RemoteActionEvaluator/RemoteActionEvaluator.cs
NineChronicles.Headless.Executable.sln

This pull request extracts request classes and response classes from `Lib9c.StateService`, as a new project `Lib9c.StateService.Shared`. I think it will resolve [the Docker image build failure](https://github.com/planetarium/NineChronicles.Headless/actions/runs/5041875226/jobs/9041960520)

Separate shared classes as a new project

---

Libplanet.Headless/Hosting/LibplanetNodeService.cs
Libplanet.Headless/Hosting/LibplanetNodeServiceProperties.cs
NineChronicles.Headless.Executable/Configuration.cs
NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless.Executable/appsettings-schema.json
NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs

After this pull request, it can configure `ConsensusReactorOption.TargetBlockInterval` with `appsettings.json` or with command line option `--consensus-target-block-interval`. If it was an intention to use the target block interval as constant, this pull request may be closed.
- Local testing with `--consensus-target-block-index=1000`.
- Update `TargetBlockIndex` without source updating. cc @planetarium/devops

feat(cli): make `ConsensusReactorOption.TargetBlockInterval` configurable

---

NineChronicles.Headless.Executable/appsettings.json
NineChronicles.Headless/Middleware/CustomRateLimitMiddleware.cs
NineChronicles.Headless/Middleware/CustomRateLimitProcessor.cs

This PR updates the rate-limiter to only use the IP value (not IP+port)  when managing gql/grpc requests.

Update rate limit

---

.github/workflows/build.yml
.github/workflows/deploy_gh_pages.yml
.github/workflows/lint.yml
Dockerfile
Dockerfile.amd64
Dockerfile.arm64v8
Dockerfile.lib9c-stateservice.amd64
Dockerfile.lib9c-stateservice.arm64v8
Lib9c.StateService.Shared/Lib9c.StateService.Shared.csproj
Lib9c.StateService/Lib9c.StateService.csproj
Libplanet.Extensions.ActionEvaluatorCommonComponents.Tests/Libplanet.Extensions.ActionEvaluatorCommonComponents.Tests.csproj
Libplanet.Extensions.ActionEvaluatorCommonComponents/Libplanet.Extensions.ActionEvaluatorCommonComponents.csproj
Libplanet.Extensions.ForkableActionEvaluator.Tests/Libplanet.Extensions.ForkableActionEvaluator.Tests.csproj
Libplanet.Extensions.ForkableActionEvaluator/Libplanet.Extensions.ForkableActionEvaluator.csproj
Libplanet.Extensions.RemoteActionEvaluator.Tests/Libplanet.Extensions.RemoteActionEvaluator.Tests.csproj
Libplanet.Extensions.RemoteActionEvaluator/Libplanet.Extensions.RemoteActionEvaluator.csproj
Libplanet.Extensions.RemoteBlockChainStates/Libplanet.Extensions.RemoteBlockChainStates.csproj
Libplanet.Headless.Tests/Libplanet.Headless.Tests.csproj
Libplanet.Headless/Libplanet.Headless.csproj
NineChronicles.Headless.Executable.Tests/Commands/ActionCommandTest.cs
NineChronicles.Headless.Executable.Tests/NineChronicles.Headless.Executable.Tests.csproj
NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj
NineChronicles.Headless.Tests/NineChronicles.Headless.Tests.csproj
NineChronicles.Headless/NineChronicles.Headless.csproj
global.json

This PR downgrades the headless target framework to `.NET6` because we've found that the `.NET7` version occasionally results in a segmentation fault(https://github.com/dotnet/runtime/issues/72365) which degrades our live RPC service quality. `.NET6` headless doesn't have this issue.
According to https://github.com/dotnet/runtime/issues/72365, this issue is fixed from `v7.0.7` so I will do another test when `v7.0.7` is officially released(not yet released).
@moreal Would it be ok to remove `Microsoft.AspNetCore.OpenApi` in `Lib9c.StateService` because this nuget package is only available starting from `.NET7`? It build successfully but I'm not sure if removing it would affect `Lib9c.StateService`'s feature. 🤔

downgrade headless to `.NET6`

---

NineChronicles.Headless/GraphTypes/TransactionHeadlessQuery.cs

This PR adds gas configs for `createUnsignedTx` query to accomplish backward compatibility.

Add gas config to createUnsignedTx query

---

NineChronicles.Headless.Tests/Common/Fixtures.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/AvatarStateTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/CombinationSlotStateTypeTest.cs
NineChronicles.Headless/GraphTypes/States/AvatarStateType.cs
NineChronicles.Headless/GraphTypes/States/CombinationSlotStateType.cs

Add CombinationSlot query in AvatarStateType query (resolves #2114)
```graphql
avatarState {
address
combinationSlotState {
address
unlockBlockIndex
unlockStage
startBlockIndex
petId
}
}
```

Add CombinationSlot query in AvatarStateType

---

NineChronicles.Headless.Executable.Tests/Commands/ActionCommandTest.cs
NineChronicles.Headless.Executable.Tests/Commands/TxCommandTest.cs
NineChronicles.Headless.Executable/Commands/TxCommand.cs
NineChronicles.Headless/GraphTypes/States/StakeStateType.cs

- Bump `lib9c`
- Use `lib9c` logic when calculate some in resolver method of graphql.
- Add more case to tx sign command.

release: version 4

---

Libplanet.Headless/ReducedStore.cs

This pull request suggests storing `TxSuccess.UpdatedStates`' addresses at least. When users want to know *REAL UPDATED ADDRESSES*, there is no way to know it because `Transaction.UpdatedAddresses` is deprecated and not trustable, and `TxSuccess.UpdatedStates` doesn't store anything. Then why we used `ReducedStore`? The `TxSuccess.UpdatedStates` was too big to store in gamers' storage. (like a copy of the `/states` directory). Sadly, no gamers have local storage. In addition, it is not big to store only updated addresses.
If this feature is applied, developers can get real updated addresses easily since the applied block index.

feat: store updated states' addresses at least

---

Libplanet.Headless/ReducedStore.cs

When working on *NineChronicles.Headless* project, I've often seen the `dotnet format` command put dots in awkward places. 😠 
While reverting it, I saw the below error. It was because of the `<see cref="IStore">` part. It should be closed like `<see ... />`.
After fixing the part, the `dotnet format` command doesn't put dots in awkward places 🤔 . It seems like the `dotnet format`'s bug... but this pull request is enough for this case.

fix: close xml tag

---

NineChronicles.Headless.Executable/Program.cs

This pull request continues from #2140 🙄

fix: correct `ForkableActionEvaluator`'s configuration parsing logic

---

.github/workflows/lint.yml
NineChronicles.Headless.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Headless/ActionEvaluationPublisher.cs
NineChronicles.Headless/GraphTypes/ActivationStatusMutation.cs
_typos.toml

This pull request resolves https://github.com/planetarium/NineChronicles.Headless/issues/1329.
This pull request suggests to check typos with GitHub Actions, [`typos` CLI tool](https://github.com/crate-ci/typos).
You can see the configuration file's spec at https://github.com/crate-ci/typos/blob/master/docs/reference.md#config-fields.
You can correct typos easily by running `typos . -w`.
p.s. I had tried to apply this tool in https://github.com/planetarium/NineChronicles.Headless/pull/1369, but there was no configurable option to ignore base64 or hexadecimal strings at that time 🙄

ci(gh-actions): check typos

---

NineChronicles.Headless/NCActionUtils.cs

This pull request resolves #2081.
The issue says `BlockChainService.PutTransaction` fails to load its action though he ran headless with `-c DevEx` option.
https://github.com/planetarium/NineChronicles.Headless/blob/b6728553842cab1f7edc0ade67e7f8c714e6a2ef/NineChronicles.Headless/BlockChainService.cs#L63-L70
It was because it uses `ActionUtils.ToAction()` and the method doesn't branch `_actionLoader` by `LIB9C_DEV_EXTENSIONS` constant flag.
https://github.com/planetarium/NineChronicles.Headless/blob/b6728553842cab1f7edc0ade67e7f8c714e6a2ef/NineChronicles.Headless/NCActionUtils.cs#L8-L11

fix: use `NCDevActionLoader` when DevEx configuration

---

.github/workflows/push_docker_image.yml

This pull request diables tagging lib9c-stateservice. I forgot removing the part in #2164

ci(gh-actions): disable tagging lib9c-stateservice

---

NineChronicles.Headless/GraphTypes/States/AvatarStateType.cs
NineChronicles.Headless/GraphTypes/States/RuneStateType.cs

To get runes in avatar, I created new `RuneStateType` and include it into `avatarState` query.
`runes` is not inside inventory because it's not in [Inventory](https://github.com/planetarium/lib9c/blob/development/Lib9c/Model/Item/Inventory.cs), but in [avatar](https://github.com/planetarium/lib9c/blob/07fad34fa36e03af8cf317938812eb2667592b85/Lib9c/Model/State/RuneState.cs#L9-L10).
Query looks like:
```graphql
query {
stateQuery {
avatar (avatarAddress:"0xDD21DCc1A9d393550A49999363e383c8409Ee1A2") {
runes {
runeId
level
}
}
}
}
```
and the result looks like:
```json
{
"data": {
"stateQuery": {
"avatar": {
"runes": [
{
"runeId": 10001,
"level": 9
},
{
"runeId": 10002,
"level": 79
},
{
"runeId": 10003,
"level": 42
},
...
]
}
}
},
"extensions": {}
}
```

Introduce runes query in avatarState GraphQL

---

NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless/ActionEvaluationPublisher.cs
NineChronicles.Headless/GraphTypes/RpcInformationQuery.cs
NineChronicles.Headless/HostBuilderExtensions.cs
NineChronicles.Headless/Middleware/GrpcCaptureMiddleware.cs

This PR utilizes `GrpcCaptureMiddleware` to track RPC clients by device (PC/mobile/other). 
In order to use the `GrpcCaptureMiddleware`, `ActionEvaluationPublisher` needs to be passed down to the middleware so I've made some adjustments in `Program.cs` when `UseNineChroniclesRPC()` method is called.

track client count by device

---

NineChronicles.Headless.Executable.Tests/Commands/ActionCommandTest.cs
NineChronicles.Headless.Executable/Commands/TxCommand.cs
NineChronicles.Headless.Executable/appsettings.mainnet.json
NineChronicles.Headless/GraphTypes/States/Models/Table/StakeRegularRewardInfoType.cs

Please refer to this issue. https://github.com/planetarium/9c-launcher/issues/2279
To put it simply, in order to print "Currency" Type of reward in Monster Collection,
Launcher needs extra field for FAV identifier. so I added a field.
This pull request based on https://github.com/planetarium/lib9c/pull/2071.

Add CurrencyTicker in RewardInfo to distinquish currency

---

NineChronicles.Headless/GraphTypes/States/Models/Item/InventoryType.cs

This pull request resolves https://github.com/planetarium/NineChronicles.Headless/issues/2189

Add `itemSubType` argument to `InventoryType.equipments` field

---

Dockerfile
Dockerfile.amd64
Dockerfile.arm64v8
NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj

This reverts commit a2f38717cae8dcec4bc2593c31f2d607c1219502.
We should analyze how to bypass the Native errors.

Revert "Add AssemblyName to Executable to make shortcut naming (#2173)"

---

NineChronicles.Headless/Middleware/CustomRateLimitMiddleware.cs
NineChronicles.Headless/Middleware/IpBanMiddleware.cs

This PR turns off redundant buffering that leads ASPNETCORE to store excessive temporary files(
https://stackoverflow.com/questions/62910894/asp-net-core-writes-request-body-to-windows-temp-folder), a situation that has been responsible for the frequent triggering of `OOMKilled` events in the Docker container (The fix is already applied in the mainnet).

disable buffering

---

NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless.Executable/appsettings.json
NineChronicles.Headless.Tests/GraphQLStartupTest.cs
NineChronicles.Headless/GraphQLService.cs
NineChronicles.Headless/HostBuilderExtensions.cs
NineChronicles.Headless/Middleware/GrpcCaptureMiddleware.cs
NineChronicles.Headless/Middleware/GrpcMultiAccountManagementMiddleware.cs
NineChronicles.Headless/Middleware/HttpCaptureMiddleware.cs
NineChronicles.Headless/Middleware/HttpMultiAccountManagementMiddleware.cs
NineChronicles.Headless/Properties/MultiAccountManagerProperties.cs

This feature manages multiple accounts that originate from the same source. The feature is turned off by default and you can turn it on by adjusting the [appsettings.json](https://github.com/planetarium/NineChronicles.Headless/compare/development...area363:account-management?expand=1#diff-e47fc585cf3ec48a24eabba8519cf4fcffbfc15f80cc907dec2379af8ebdf134R125-R130) or by adding the configuration as environment variables.
- `EnableManaging`: turn `on/off` account management mode
- `ThresholdCount`: number of accounts from a single source to start managing (eg. `50` means that if there are `50` accounts that are from a single origin, the feature will start managing the associated accounts).
- `TxIntervalMinutes`: tx interval for accounts that are under management. (e.g. `10` means that the …

add account management feature

---

NineChronicles.Headless/GraphQLService.cs
NineChronicles.Headless/HostBuilderExtensions.cs

Minor adjustment to use multiaccount management middlewares only when enabled.

don't use multiaccount middleware if not enabled

---

NineChronicles.Headless/GraphTypes/StandaloneQuery.cs

This pull request makes `query.state` field return `null` when the state corresponding to `address` doesn't exist. The original behavior is throwing `NullReferenceException` via `Bencodex.Codec.Encode` doesn't allow its parameter to be `null`.

fix(graphql): return null instead of errors

---

NineChronicles.Headless/GraphTypes/TransactionHeadlessQuery.cs

It resolves #2216 
Expected usage:
```graphql
query GetOnlyItemEnhancementTransactions {
transaction {
ncTransactions(actionType: "item_enhancement\d$", startingBlockIndex: 1000, limit: 100) {
id
}
}
}
```

Support regex for `transaction.ncTransactions`' actionType argument

---

NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless/HostBuilderExtensions.cs

This PR addresses the issue where `ActionEvaluationPublisher` was instantiated twice in RPC mode. Now, the publisher is initialized in `Program.cs` and subsequently passed to both `UseNineChroniclesNode` and `UseNineChroniclesNodeRPC` methods found in `HostBuilderExtensions.cs`.

fix duplicate publisher in RPC mode

---

Libplanet.Extensions.ForkableActionEvaluator.Tests/ForkableActionEvaluatorTest.cs
Libplanet.Extensions.ForkableActionEvaluator/ForkableActionEvaluator.cs
NineChronicles.Headless.Executable.Tests/Commands/ChainCommandTest.cs
NineChronicles.Headless.Executable/Commands/ReplayCommand.Privates.cs
NineChronicles.Headless.Executable/Commands/ReplayCommand.cs
NineChronicles.Headless.Executable/Commands/StateCommand.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneSubscriptionTest.cs
NineChronicles.Headless.Tests/GraphTypes/TransactionHeadlessQueryTest.cs

commit on aev

---

NineChronicles.Headless.Tests/GraphTypes/StandaloneSubscriptionTest.cs
NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs

This pull request updates the buffer size of `subscription.tipChanged` API's subject to 1. Without the limitation, the `ReplaySubject` uses `int.MaxValue` as its buffer size. It is very useless to provide `tipChanged` subscription feature. It just causes too many subscription responses and uses too much memory.
When I tested with launcher, it works well.

Set tipChanged subject's buffer size to 1

---

NineChronicles.Headless.Executable.Tests/Commands/AccountCommandTest.cs
NineChronicles.Headless.Executable.Tests/Commands/ChainCommandTest.cs
NineChronicles.Headless.Executable/Commands/ChainCommand.cs
NineChronicles.Headless.Executable/Commands/ReplayCommand.cs
NineChronicles.Headless/NineChroniclesNodeService.cs

🔧  Remove `IRenderer`s from `BlockPolicySource`

---

Libplanet.Extensions.ForkableActionEvaluator.Tests/ForkableActionEvaluatorTest.cs
Libplanet.Extensions.ForkableActionEvaluator/ForkableActionEvaluator.cs
Libplanet.Headless/Hosting/LibplanetNodeService.cs
NineChronicles.Headless.Executable.Tests/Commands/ChainCommandTest.cs
NineChronicles.Headless.Executable/Commands/ChainCommand.cs
NineChronicles.Headless/GraphQLServiceExtensions.cs
NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs
NineChronicles.Headless/GraphTypes/TransactionHeadlessQuery.cs

⬆️ Bump libplanet to 3.6.0

---

Dockerfile.ACC
Dockerfile.ACC.amd64
Dockerfile.ACC.arm64v8
NineChronicles.Headless.AccessControlCenter/AccessControlService/IMutableAccessControlService.cs
NineChronicles.Headless.AccessControlCenter/AccessControlService/MutableAccessControlServiceFactory.cs
NineChronicles.Headless.AccessControlCenter/AccessControlService/MutableRedisAccessControlService.cs
NineChronicles.Headless.AccessControlCenter/AccessControlService/MutableSqliteAccessControlService.cs
NineChronicles.Headless.AccessControlCenter/AcsService.cs
NineChronicles.Headless.AccessControlCenter/Configuration.cs
NineChronicles.Headless.AccessControlCenter/Controllers/AccessControlServiceController.cs
NineChronicles.Headless.AccessControlCenter/NineChronicles.Headless.AccessControlCenter.csproj
NineChronicles.Headless.AccessControlCenter/Program.cs
NineChronicles.Headless.AccessControlCenter/appsettings.json
NineChronicles.Headless.Executable.sln
NineChronicles.Headless.Executable/Configuration.cs
NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless.Tests/GraphQLStartupTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneSubscriptionTest.cs
NineChronicles.Headless/NineChronicles.Headless.csproj
NineChronicles.Headless/NineChroniclesNodeService.cs
NineChronicles.Headless/Properties/AccessControlServiceOptions.cs
NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs
NineChronicles.Headless/Services/AccessControlServiceFactory.cs
NineChronicles.Headless/Services/RedisAccessControlService.cs
NineChronicles.Headless/Services/SQLiteAccessControlService.cs

This PR should be merged after [lib9c PR](https://github.com/planetarium/lib9c/pull/2168) and then bumped.
This PR introduces the following changes related to the `AccessControlService`
- Added core logic for AccessControlService to manage access permissions.
- The AccessControlCenter can now control access permissions for using the REST API.
- Users can choose their desired storage type (SQLite, Redis). When an address is added as a key to the specified storage, it will be denied during staging in NCPolicy.

[Feature] Introduce Access control service and Access control center

---

NineChronicles.Headless.AccessControlCenter/AccessControlService/IMutableAccessControlService.cs
NineChronicles.Headless.AccessControlCenter/AccessControlService/MutableRedisAccessControlService.cs
NineChronicles.Headless.AccessControlCenter/AccessControlService/MutableSqliteAccessControlService.cs
NineChronicles.Headless.AccessControlCenter/Controllers/AccessControlServiceController.cs
NineChronicles.Headless/Services/RedisAccessControlService.cs
NineChronicles.Headless/Services/SQLiteAccessControlService.cs

- Add `AddTxQuota` and `RemoveTxQuota` to ACS to set or delete individual signer's `txQuotaPerSigner`.
Replaces https://github.com/planetarium/NineChronicles.Headless/pull/2276.

Add `AddTxQuota` and `RemoveTxQuota` to ACS

---

NineChronicles.Headless.Tests/GraphTypes/TransactionHeadlessQueryTest.cs
NineChronicles.Headless/GraphTypes/TransactionHeadlessQuery.cs

🔨 PDX-136: Fix ncTransactions bug when startingBlockIndex is the same as the tip index

---

NineChronicles.Headless/ActionEvaluationPublisher.cs

There are too many AEP logs like this:
```
[05:10:20 INF] [0x8CCEF8cf71B0317edC4B9B62153f731a0A646760], #35383, Nekoyume.Action.HackAndSlash, 0, 343, 343
[05:10:20 INF] [0xdb9bd6838C60f0D1b0Af9E5873D973c3Da869DEb], #35383, Nekoyume.Action.HackAndSlash, 0, 297, 297
[05:10:20 INF] [0x29f1f87D45e1c4DfcEd8Cd2D6229423f0F7d980B] #35383 Broadcasting render since the given action Nekoyume.Action.HackAndSlash. eval size: 355
[05:10:20 INF] [0x3981983daf2FDB8CD63d18A023eE886B54AB980e], #35383, Nekoyume.Action.HackAndSlash, 0, 607, 607
[05:10:20 INF] [0x5994D627934841624f420A2623471194610D704A] #35383 Broadcasting render since the given action Nekoyume.Action.HackAndSlash. eval size: 355
[05:10:20 INF] [0x8C429f7c210F5817ad7e490B39a7e17225128a10], #35383, Nekoyume.Action.HackAndSlash, 0, 315, 315 …
```

change some AEP logs to verbose level

---

NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
NineChronicles.Headless/GraphTypes/ActionQuery.cs

It resolves #2298.
As custom tickers(ex: Item_NT_111) was created, transferAsset action should be able to accept custom ticker instead of pre-defined enum currency.
changed schema looks like... :
```gql
actionQuery {
transferAsset{
sender: "0x00",
recipient: "0x01",
value: {
ticker: "token_str",
decimalPlaces: 18,
minters: [],
quantity: 100
}
}
}
```

PDX-126: update transferAsset to accept custom ticker

---

NineChronicles.Headless.Executable/Program.cs

```yang@yangcheon-ung-ui-MacBookPro data-provider % kubectl top pod test-headless-1-0 -n heimdall
NAME                CPU(cores)   MEMORY(bytes)
test-headless-1-0   1071m        10024Mi
yang@yangcheon-ung-ui-MacBookPro data-provider % kubectl top pod remote-headless-1-0 -n heimdall
NAME                  CPU(cores)   MEMORY(bytes)
remote-headless-1-0   1335m        11949Mi
yang@yangcheon-ung-ui-MacBookPro data-provider % kubectl top pod remote-headless-1-0 -n heimdall
NAME                  CPU(cores)   MEMORY(bytes)
remote-headless-1-0   1362m        13565Mi
yang@yangcheon-ung-ui-MacBookPro data-provider % kubectl top pod test-headless-1-0 -n heimdall
NAME                CPU(cores)   MEMORY(bytes)
test-headless-1-0   156m         393Mi
```
When a worker prepare list of arena players, …

configure arena list sync worker for avoid memory pressure

---

NineChronicles.Headless/GraphQLService.cs

Exposes inner exception message and stack trace for better debugging. However, there are some security concerns such as exposing sensitive information (such as passing private key around inside an exception message).
From what I gather, it'd be best if such exception decorating is only allowed under so called "development environment" (via `IWebHostEnvironment.IsDevelopment()`). I'm not sure whether such notion applies to our current deployment strategy (centrally run yet open distributed, if that makes any sense). 🙄
It would be nice to have the option to turn it on and off. 😗
```json
{
"errors": [
{
"message": "Error trying to resolve field 'getTx'.",
"locations": [
{
"line": 3,
"column": 5
}
],
"path": [
"transaction",
"getTx"
],
"extensions": {
"code": "ARGUMENT_OUT_OF_RANGE",
"codes": …
```

Add detail to graphQL exceptions

---

NineChronicles.Headless.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneSubscriptionTest.cs
NineChronicles.Headless.Tests/GraphTypes/TransactionHeadlessQueryTest.cs

⬆️ Bump after reverting deletion of actions from lib9c that use non-trivial context within 9c-headless.

⬆️ Bump lib9c to f1d89f59

---

NineChronicles.Headless.Executable/Configuration.cs
NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Headless/NineChroniclesNodeService.cs
NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs

The new `MaxTransactionPerBlock` parameter will customize the libplanet chain's `maxtransactionperblock` policy when operating validators.
Must be merged after https://github.com/planetarium/lib9c/pull/2475 and lib9c version must be rebumped.

Customize max transaction per block

---

NineChronicles.Headless.Tests/ArenaParticipantsWorkerTest.cs
NineChronicles.Headless.Tests/Common/Fixtures.cs
NineChronicles.Headless/ArenaParticipantsWorker.cs

Update submodules to apply rune level bonus.
This will propagate to DataProvider.

Apply latest lib9c for rune level bonus

---

NineChronicles.Headless/NineChronicles.Headless.csproj

Newly found vulnerability prevents this project being compiled in [DP](https://github.com/planetarium/NineChronicles.DataProvider).

🩹 Changed `csproj` to temporarily ignore warnings

---

NineChronicles.Headless/GraphQLService.cs
NineChronicles.Headless/Middleware/JwtAuthenticationMiddleware.cs
NineChronicles.Headless/NineChronicles.Headless.csproj

This pull request resolves https://github.com/planetarium/NineChronicles.Headless/issues/2453
This pull request does:
- Bump OpenTelemetry-related dependencies.
- Remove `WarningsNotAsErrors` option.
- FIx some compile errors related to nullable feature.

Bump OpenTelemetry-related dependencies

---

Libplanet.Headless/Hosting/LibplanetNodeService.cs

* Adding "PLUGIN_PATH=/data" env will store plugin files in pvc and avoid re-download each restart.
* Replace GetHashCode with CreateSha256Hash to get consistent path value (GetHashCode generates random value each time).

add PLUGIN_PATH env to avoid downloading the same plugin file each restart

---

NineChronicles.Headless.Executable/Program.cs

This will be `131` release not v200171.

hotfix(v200170): Disable .NET runtime instruments

---

Libplanet.Headless/Hosting/LibplanetNodeService.cs
Libplanet.Headless/Hosting/LibplanetNodeServiceProperties.cs
NineChronicles.Headless.Executable/Configuration.cs
NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs

resolves #2441 
This PR introduces `--consensus-propose-second-base` cli parameter to customize `ContextTimeoutOption`.`ProposeSecondBase` in `LibplanetNodeService`

add `--consensus-propose-second-base` cli parameter

---

NineChronicles.Headless/GraphTypes/StandaloneQuery.cs

When it's a PoW chain, it's very risky to access state by index. However, thanks to the work of the Libplanet team, the NineChronicles network has partially transitioned to PoS, so we're adding the ability to access it by index. We expect that this will solve the problem of replacing index with hash and then accessing it.
```graphql
{
state(address: "0x", index: 0)
stateQuery(index: 0)
{
avatar(address: "0x") { name }
}
}
```

Provide `index` parameter when to query state

---

NineChronicles.Headless.Executable/Program.cs

SSIA
example
```
http_server_request_duration_seconds_bucket{otel_scope_name="OpenTelemetry.Instrumentation.AspNetCore",otel_scope_version="1.0.0.0",http_request_method="GET",http_response_status_code="200",network_protocol_version="1.1",url_scheme="http",le="0.005"} 77 1721198393274
http_server_request_duration_seconds_bucket{otel_scope_name="OpenTelemetry.Instrumentation.AspNetCore",otel_scope_version="1.0.0.0",http_request_method="GET",http_response_status_code="200",network_protocol_version="1.1",url_scheme="http",le="0.01"} 78 1721198393274
http_server_request_duration_seconds_bucket{otel_scope_name="OpenTelemetry.Instrumentation.AspNetCore",otel_scope_version="1.0.0.0",http_request_method="GET",http_response_status_code="200",network_protocol_version="1.1",url_scheme="http",le="0.025 …
```

Add dotnet related metrics

---

NineChronicles.Headless/GraphTypes/TransactionHeadlessQuery.cs

Currently, checking the transaction status using the transaction result query consumes unnecessary network resources.
To address this, I propose adding a txStatus filter argument to the ncTransactions type.

Add txStatusFilter in ncTransactions type

---

NineChronicles.Headless.Executable/Commands/ReplayCommand.cs
README.md

replay remote tx 커맨드 실행시 유니티 등 다른 클라이언트에서 사용할 인자를 참조할 수 있도록 사용된 인자를 표시합니다.
```
/Users/yang/projects/headless/NineChronicles.Headless.Executable/bin/Release/net6/NineChronicles.Headless.Executable replay remote-tx --tx {txId} --endpoint {graphqlEndPoint} --grpc-endpoint {grpcEndPoint}
BlockIndex: 2657433, BlockProtocolVersion: 8, Miner: 0x088d96AF8e90b8B2040AeF7B3BF7d375C9E421f7, PreviousState: 5eee8394545c4eb2c91ef3051ecb3f18507f398fa6e623f826418e35886591a9, RandomSeed: 400765736, Signer: 0x3146FE0E47A1998e14cd8a33640e3648A5A90276, TxId: 23a69ad8ac380e0dfd9b3427f11b1fe505011a1d8ebd1d002c3c3ba073f4afac
```

logging remote replay tx execute arguments

---

NineChronicles.Headless/NineChronicles.Headless.csproj

Currently, Prometheus fails to fetch metrics from headless because its metrics export result isn't compatible for the standard or Prometheus' way. So I had disabled it in #2460 temporarily. And it is enabled again in this version and the error occurs again. But, fortunately, it seems fixed in OpenTelemetry 1.9.0 by https://github.com/open-telemetry/opentelemetry-dotnet/pull/5646. So this pull request bumps them to 1.9.0
```
unit not a suffix of metric "process_runtime_dotnet_gc_allocations_size_bytes_total"
```

Bump OpenTelemetry dependencies

---

NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
NineChronicles.Headless/GraphTypes/ActionQuery.cs
NineChronicles.Headless/GraphTypes/ActionQueryFields/IssueToken.cs
NineChronicles.Headless/GraphTypes/ItemIdAndCountInputType.cs

Introduce IssueToken action query

---

NineChronicles.Headless/Services/RedisAccessControlService.cs

When acc env value is added to the headless configuration, the headless operation completely stops when acc is down. Adding `AbortOnConnectFail = false` enables headless operation to continue even when acc is down. It also retries connection automatically so that it will reconnect to acc when it is back up.
Error message:
```
StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s). Error connecting right now. To allow this multiplexer to continue retrying until it's able to connect, use abortConnect=false in your connection string or AbortOnConnectFail=false; in your code.
at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(ConfigurationOptions configuration, TextWriter log, Nullable`1 serverType, EndPointCollection endpoints) in …
```

prevent headless from stopping when acc redis is down

---

NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
NineChronicles.Headless/GraphTypes/ActionQueryFields/RapidCombination.cs

apply changes to Lib9c
https://github.com/planetarium/lib9c/pull/2765

apply changes to Lib9c

---

NineChronicles.Headless.Tests/ArenaParticipantsWorkerTest.cs
NineChronicles.Headless.Tests/Common/Fixtures.cs

It bumps `Lib9c` submodule to the latest commit of its `development` branch. It only includes commits related with https://github.com/planetarium/lib9c/pull/2780

Bump lib9c to development

---

.github/workflows/deploy_gh_pages.yaml

`dotnet build` command doesn't accept `--project` option. Project path is just an argument.

ci(gh-actions): remove invalid option

---

NineChronicles.Headless/BlockChainService.cs

We observed that when the network quota ran out, the response speed of `GetTip` became significantly slower. 
The difference between `GetTip` and other `IBlockChainService` methods seems to be that it uses `private static Codec` instead of `private _codec`. First, I want to change it to use `_codec` instead of `Codec` and then check if there is a performance improvement.
Use `_codec` instead of `Codec` on the `GetTip`.

fix: use private codec instead of static Codec

---

.github/workflows/push_docker_image.yml
Dockerfile
Dockerfile.ACC

gh workflow has been updated as well - with proper build args

unified dockerfile that supports multi arch

---

.github/workflows/push_docker_image.yml

Pass `COMMIT` build-arg when building Docker images in GitHub Actions workflow.

ci(gh-actions): fix workflow to build docker image

---

.github/dependabot.yml

We usually missed to bump GitHub Actions and cannot realizing if there is a new release to bump. Since Dependabot supports GitHub Actions, I updated its configuration to check if there is something to bump automatically 🤖

chore: update dependabot conf to bump GitHub Actions automatically

---

.github/workflows/push_docker_image.yml
Dockerfile
Dockerfile.ACC

Since emulating x64 .NET to ARM64 is too hard to cause Segment-fault error, I fixed the `Dockerfile`s to run in `$BUILDPLATFORM` (i.e., `amd64`).

ci: use setup-qemu-action instead

---

NineChronicles.Headless.Executable.sln.DotSettings

- lib9c/headless등에 적용된 StyleCop 코드 규칙에 맞게 코드 변경을 진행 후 추가적으로 수정되는 스타일입니다.
- StyleCop 규칙에서 using문에 namespace를 작성할 때 무조건 namespace의 풀 네임을 적용해야 하는 규칙이 있습니다
- 이를 대비하기 위해 라이더에서 'PreferQualifiedReference' 옵션을 True로 설정해두었는데 이로 인해 필드의 클래스를 지정할때에도 자동적으로 full namespace가 들어가는 케이스가 있고 이게 신경쓰이는 상황이 반복되어 False로 옵션을 변경해두었습니다
```
SA1210: Using directives should be ordered alphabetically by the namespaces.
SA1135: Using directive for namespace 'Lib9c.Tests.Action' should be qualified
```
현재 development를 머지 타겟으로 설정해두었는데, 현재 작업중인 250(클라기준) 패치와 관련된 작업 브랜치에 머지해야겠다 싶으시면 코멘트 남겨주세요!

fix code style for namespace

---

NineChronicles.Headless.Executable/Program.cs

Apparently, on Mac, specifying the config path as a `url` or using a different name like `appsettings123.json` will cause the program to crash on launch.
This is presumably because the configuration generated by IHostBuilder does not read the settings from the specified path.
This PR contains changes to resolve the issue

Fixed exception thrown when executing with URL or other name config

---

.github/workflows/push_docker_image.yml

Previously, the `push_docker_image` workflow tagged image incorrectly, tag for only one platform (not both linux/amd64 and linux/arm64). It was because of misunderstanding for `docker pull` and `docker tag` command.
So I researched the way and I found `docker buildx imagetools create` command. It can create a new manifest list from manifest list with a tag. (`docker manifest` cannot handle manifest list 😢)
The following lines are my shell output when testing locally. Because their digests are same with the original manifest, I believe that its behavior is just retagging.
```
% docker buildx imagetools create --progress=plain --tag=moreal/9c-headless:333 planetariumhq/ninechronicles-headless:git-08308b1134eaaa7a593350ebe59f12021b33fae7
#1 [internal] pushing docker.io/moreal/9c-headless:333 …
```

ci(gh-actions): fix tagging docker image

---

NineChronicles.Headless.Tests/GraphTypes/ValidatorTypeTest.cs
NineChronicles.Headless/GraphTypes/StateQuery.cs
NineChronicles.Headless/GraphTypes/ValidatorType.cs

You can use the query below to see the delegation information for a Validator.
query
```GraphQL
query {
stateQuery {
validator(validatorAddress: <address>) {
power
isActive
totalShares
jailed
jailedUntil
tombstoned
commissionPercentage
totalDelegated {
currency
quantity
}
}
}
}
```
result
```json
{
"data": {
"stateQuery": {
"validator": {
"power": "1,000,000,000,000,000,000,000",
"isActive": false,
"totalShares": "1,000,000,000,000,000,000,000",
"jailed": false,
"jailedUntil": -1,
"tombstoned": false,
"commissionPercentage": "10",
"totalDelegated": {
"currency": "GUILD_GOLD",
"quantity": "1000.000000000000000000"
}
}
}
}
}
```

Add stateQuery for the validator's delegation

---

NineChronicles.Headless/GraphQLService.cs
NineChronicles.Headless/Middleware/CustomRateLimitMiddleware.cs
NineChronicles.Headless/Middleware/HttpCaptureMiddleware.cs
NineChronicles.Headless/Middleware/HttpMultiAccountManagementMiddleware.cs

When graphql query includes a header with jwt token, the headless rate-limiter & multi-account-manager whitelists the ip.

Override rate limit with jwt token

---

NineChronicles.Headless.Executable/appsettings.json
NineChronicles.Headless/Middleware/CustomRateLimitMiddleware.cs
NineChronicles.Headless/Middleware/HttpCaptureMiddleware.cs
NineChronicles.Headless/Middleware/IpBanMiddleware.cs

This PR addresses an issue where the transactionResults query currently does not limit the number of txids passed down. To mitigate potential abuse, this PR introduces a rate-limit specifically targeting abusive users before implementing a parameter-based limit in the query.

Add rate-limit to transactionresults query

---

.github/auto_assign.yml

I stepped down from maintainer by leaving the company so I remove myself from auto_assign reviewers list.

Remove moreal from auto_assign reviewers

---

NineChronicles.Headless.Tests/BlockChainServiceTest.cs
NineChronicles.Headless/BlockChainService.cs
NineChronicles.Headless/GraphQLService.cs
NineChronicles.Headless/Repositories/BlockChain/BlockChainRepository.cs
NineChronicles.Headless/Repositories/BlockChain/IBlockChainRepository.cs
NineChronicles.Headless/Repositories/Swarm/ISwarmRepository.cs
NineChronicles.Headless/Repositories/Swarm/SwarmRepository.cs

- https://github.com/planetarium/NineChronicles/issues/6580 관련 헤드리스에서 StageTransaction 처리 결과를 클라이언트에 반환
- 동작관련 테스트를 위해 BlockChain, Swarm 등의 클래스를 직접사용하는대신 Repository패턴 상용

IBlockChainService.PutTransaction의 결과값 반환

---

NineChronicles.Headless/ActionEvaluationPublisher.cs

- resolve #2682 
---
현재 헤드리스에 클라이언트가 grpc 구독시 다른 유저의 모든 액션까지 전부 렌더를 호출하고 있지만, 클라이언트는 TransferAsset과 같은 특정 액션을 제외하곤 해당 액션을 렌더하지않고 필터링해서 무시하고 있습니다.
불필요한 네트워크 전송을 방지하기위해 클라이언트에 적용되있던 필터를 참고해서 헤드리스에서 클라이언트에 보내주는 액션을 필터링하도록 처리합니다.

Filter for reduce broadcast action

---

NineChronicles.Headless.Tests/GraphTypes/DelegatorTypeTest.cs
NineChronicles.Headless/GraphTypes/ActionQuery.cs
NineChronicles.Headless/GraphTypes/DelegateeRepositoryType.cs
NineChronicles.Headless/GraphTypes/DelegateeType.cs
NineChronicles.Headless/GraphTypes/DelegatorRepositoryType.cs
NineChronicles.Headless/GraphTypes/DelegatorType.cs
NineChronicles.Headless/GraphTypes/StateQuery.cs

1. 길드 시스템에 대한 action query 를 추가하였습니다.
2. Delegatee 와 Delegator 상태를 확인할 수 있는 state query 를 추가하였습니다.
3. 밸리데이터는 아바타가 없기 때문에 stake 액션 쿼리를 실행할 수 없는 문제점을 수정하였습니다.
4. 밸리데이터 관련 action query 를 추가하였습니다.
makeGuild
removeGuild
joinGuild
quitGuild
moveGuild
banGuildMember
unbanGuildMember
claimReward
claimGuildReward
claimUnbonded
unjailValidator
delegateValidator
undelegateValidator
delegatee
delegator

Add state and action queries for guild system and delegation

---

Directory.Build.props

This bump contains below features :
- Block QuitGuild / RemoveGuild before unbonding has been ended
- Block MoveGuild to same guild
- Add soft migration logic for users who has been skipped delegation migration
- Fix issue where equality check returns false for same Delegator / Delegatee
- Bump Libplanet to 5.5.0

Bump Lib9c 1.22.0

---

NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
NineChronicles.Headless/GraphTypes/ActionQuery.cs

Hotfix
- Lib9c 1.22.0 -> 1.22.1
- 제거되었던 길드 / 위임 관련 마이그레이션 액션을 다시 되돌림
- 마이그레이션되지 않은 유저가 확인되었기 때문

Release 241

---

.github/workflows/push_docker_image.yml
NineChronicles.Headless.Tests/MemoryCacheExtensionsTest.cs
NineChronicles.Headless/BlockChainService.cs
NineChronicles.Headless/MemoryCacheExtensions.cs

Resolves https://github.com/planetarium/NineChronicles.RPC.Shared/issues/39, https://github.com/planetarium/NineChronicles/issues/6901
- RPC interace 업데이트
- 시트캐시에서 해싱값 비교를 위해 Normailze 처리를 추가하고 캐싱하는 값을 해당 데이터로 변경

Add BlockChainService.GetSheetHashes

---

NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Headless/GraphTypes/BlockStartingTxNoncesType.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs

특정 블록 실행 전의 논스값들을 가져올 수 있는 쿼리를 추가합니다.
- Arguments로서는 블록의 hash 혹은 index 둘 중의 하나를 받아,
- 해당 블록이 실행되기 이전의 해당 블록에 포함된 트랜잭션 서명자들에 대한 논스값을 리턴하며,
- 만약 hash와 index 양 쪽 모두 기입하지 않을 경우, tip에 대하여 위의 논스값들을 리턴합니다.

Introduce `blockStartingTxNoncesQuery`
