Libplanet.Standalone/Libplanet.Standalone.csproj

Bump libplanet to 0.10.0-dev.20200806084644

---

NineChronicles.Standalone/ActionEvaluationHub.cs
NineChronicles.Standalone/ActionEvaluationPublisher.cs

Closes #2 
This PR implements the feature that sends events via gRPC when reorg occurred.

Implement reorg features

---

.github/workflows/pull_request.yml
.github/workflows/push.yml

Automate build and push image

---

NineChronicles.Standalone/ActionEvaluationPublisher.cs

The title says it all. it closes #9 .

Prevent app crashing during gRPC broadcasting.

---

NineChronicles.Standalone/Controllers/GraphQLController.cs

- Return 409: Waiting node service
- Return 503: Unexpected Error
- Return 200: OK

More detail return status code

---

README.md

@longfin @limebell Can you guys check the English translation of the readme? Thanks!

translated readme to english

---

Libplanet.Standalone/Hosting/LibplanetNodeService.cs
Libplanet.Standalone/Libplanet.Standalone.csproj
NineChronicles.Standalone.Tests/GraphTypes/GraphQLTestBase.cs
NineChronicles.Standalone.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Standalone.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Standalone.Tests/GraphTypes/StandaloneSubscriptionTest.cs
NineChronicles.Standalone/BlockChainService.cs
NineChronicles.Standalone/Properties/NineChroniclesNodeServiceProperties.cs

This PR bumps its Lib9c to https://github.com/planetarium/lib9c/commit/f286c28e247290940060ab462659e1409b827122 and modify some codes for that commit.

Bump lib9c and libplanet

---

Libplanet.Standalone.Tests/Hosting/LibplanetNodeServiceTest.cs
Libplanet.Standalone/Hosting/LibplanetNodeService.cs
Libplanet.Standalone/Libplanet.Standalone.csproj
NineChronicles.Standalone.Tests/GraphTypes/GraphQLTestBase.cs
NineChronicles.Standalone/ActionEvaluationPublisher.cs
NineChronicles.Standalone/Controllers/GraphQLController.cs
NineChronicles.Standalone/GraphTypes/StandaloneSubscription.cs
NineChronicles.Standalone/NineChroniclesNodeService.cs

See also the patches merged into lib9c as well: <https://github.com/planetarium/lib9c/pull/23> & <https://github.com/planetarium/lib9c/pull/26>.

Follow up Lib9c & Libplanet's new rendering API

---

Libplanet.Standalone/Hosting/LibplanetNodeService.cs
Libplanet.Standalone/Libplanet.Standalone.csproj

This PR causes `LibplanetNodeService.Swarm` to restart if it does not receive a new message within the time specified(`BootstrapInterval`).

Restart Swarm<T> if it didn't receive messages

---

Libplanet.Standalone/Hosting/LibplanetNodeService.cs
Libplanet.Standalone/Hosting/LibplanetNodeServiceProperties.cs
Libplanet.Standalone/Libplanet.Standalone.csproj
NineChronicles.Standalone.Executable/Program.cs
NineChronicles.Standalone/Properties/NineChroniclesNodeServiceProperties.cs

It includes a feature addition and bumping dependencies:
Lib9c
- planetarium/lib9c#20
- planetarium/lib9c#27
- planetarium/lib9c#28
Libplanet
- planetarium/libplanet#968

Allow to use TrieStateStore

---

NineChronicles.Standalone.Tests/Common/Actions/RewardGold.cs

Bump lib9c

---

Libplanet.Standalone.Tests/Hosting/LibplanetNodeServiceTest.cs
Libplanet.Standalone/Hosting/LibplanetNodeService.cs
NineChronicles.Standalone.Tests/GraphTypes/DummyRenderer.cs
NineChronicles.Standalone.Tests/GraphTypes/GraphQLTestBase.cs
NineChronicles.Standalone/ActionEvaluationPublisher.cs
NineChronicles.Standalone/Controllers/GraphQLController.cs
NineChronicles.Standalone/GraphTypes/StandaloneSubscription.cs
NineChronicles.Standalone/NineChroniclesNodeService.cs

This applies https://github.com/planetarium/lib9c/pull/37.

Separate BlockRenderer and ActionRenderer

---

Libplanet.Standalone/Hosting/LibplanetNodeService.cs

Log error "No any peers in swarm's routing table." if no any peers in swarm's routing table.

Detect empty routing table

---

.github/workflows/push.yml

Build docker images for 9c-beta-* branch

---

NineChronicles.Standalone/NineChroniclesNodeService.cs

https://github.com/planetarium/lib9c/pull/51

Use LoggedRenderers

---

NineChronicles.Standalone/ActionEvaluationHub.cs
NineChronicles.Standalone/ActionEvaluationPublisher.cs

Please see also:
- https://github.com/planetarium/lib9c/pull/69
- https://github.com/planetarium/NineChronicles.RPC.Shared/pull/4

Broadcast `ReorgEnd` event

---

Libplanet.Standalone/Libplanet.Standalone.csproj

- planetarium/libplanet#1005
- planetarium/lib9c#68
- planetarium/lib9c#75

Bump Lib9c & Libplanet

---

Libplanet.Standalone/Libplanet.Standalone.csproj

- https://github.com/planetarium/lib9c/pull/78
- https://github.com/planetarium/lib9c/pull/77 ([Libplanet 0.10.0-dev.20200917072856][1])
- https://github.com/planetarium/libplanet/pull/1009
[1]: https://www.nuget.org/packages/Libplanet/0.10.0-dev.20200917072856

Upgrade Lib9c & Libplanet to 0.10.0-dev.20200917072856

---

NineChronicles.Standalone/BlockChainService.cs

Apply DelayedRenderer to BlockChainService.GetState()

---

NineChronicles.Standalone.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Standalone.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Standalone/GraphTypes/StandaloneMutation.cs
NineChronicles.Standalone/GraphTypes/StandaloneQuery.cs

It addresses #46 .
This PR adds two GraphQL interfaces for transfer and query gold(a.k.a. NCG).
```graphql
type StandaloneQuery
{
goldBalance(
address: Address!
hash: ByteString
): String!
}
```
```graphql
query
{
goldBalance(address: "0xba59F3b054EA42230b624e6c3D890e09287522A7")
}
```
```graphql
{
"data": {
"goldBalance": "105"
},
"extensions": {}
}
```
```graphql
type StandaloneMutation {
transferGold(recipient: Address!, amount: String!): Boolean!
}
```
```graphql
mutation
{
transferGold(amount: "100", recipient: "0xba59F3b054EA42230b624e6c3D890e09287522A7")
}
```
```graphql
{
"data": {
"transferGold": true
},
"extensions": {}
}
```

transferGold mutation

---

NineChronicles.Standalone/NineChroniclesNodeService.cs

I guess... we should refactor it within the near future. 😓

Fix a bug that activatedAccount hadn't updated

---

Libplanet.Standalone/Hosting/DevLibplanetNodeService.cs
Libplanet.Standalone/Hosting/LibplanetNodeService.cs
NineChronicles.Standalone.Executable/Program.cs
NineChronicles.Standalone/NineChroniclesNodeService.cs
NineChronicles.Standalone/ReorgPolicy.cs
NineChronicles.Standalone/StandaloneServices.cs
README.md

This adds three program arguments for developing: `--dev`, `--dev.block-interval`, `--dev.reorg-interval`
Please see also: https://github.com/planetarium/lib9c/pull/113

Add artificial periodic reorg mode

---

Libplanet.Standalone/Hosting/LibplanetNodeService.cs

Fix a bug that peer checker disturb Swarm<T>

---

NineChronicles.Standalone.Executable.sln

Continued from <https://github.com/planetarium/NineChronicles.Standalone/pull/89>.
See also <https://github.com/planetarium/lib9c/pull/132>.

Add Libplanet & Libplanet.Stun projects to the NineChronicles.Standalone.Executable.sln

---

NineChronicles.Standalone.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Standalone.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Standalone/Controllers/GraphQLController.cs

Bumped to https://github.com/planetarium/lib9c/commit/d303116fd0e2d32ad42a3af02a54e6c9a883431d
TODO : `NotifyRefillActionPoint(long dailyRewardReceivedIndex)` should be covered in test.

Bump lib9c to d303116.

---

NineChronicles.Standalone/GraphTypes/ActivationStatusMutation.cs

This PR adds exception messages about activation error for frontend.

Separate activation exception message for frontend

---

Libplanet.Standalone/Hosting/DevLibplanetNodeService.cs
NineChronicles.Standalone.Executable/Program.cs
NineChronicles.Standalone/NineChroniclesNodeService.cs
NineChronicles.Standalone/StandaloneServices.cs
README.md

Adds an option to turn on `ValidatingActionRenderer` implemented in Lib9c.

Options for ValidatingActionRenderer

---

Libplanet.Standalone/Hosting/LibplanetNodeServiceProperties.cs
NineChronicles.Standalone.Executable/Program.cs
NineChronicles.Standalone.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Standalone/GraphTypes/ActionMutation.cs
NineChronicles.Standalone/NineChroniclesNodeService.cs
NineChronicles.Standalone/Properties/NineChroniclesNodeServiceProperties.cs
README.md

Adds unsigned-integer-typed `--max-transactions` option of default value 0.
See also: https://github.com/planetarium/lib9c/pull/158

Adds option to limit maximum transactions in single block

---

NineChronicles.Standalone.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Standalone/GraphTypes/StandaloneMutation.cs

This PR adds a GraphQL mutation named `stageTx()` to add to staging arbitrary transactions.

Add stageTx mutation

---

NineChronicles.Standalone/NineChroniclesNodeService.cs

The line was accidently removed, so restore it.

Add interval between mining in dev mode

---

NineChronicles.Standalone.Executable/Program.cs

Fix a bug occurred when set --graphql-host rather than localhost

---

NineChronicles.Standalone.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Standalone/GraphTypes/StandaloneQuery.cs

This PR adds `nextTxNonce()` to query next tx nonce for the given address.

Add nextTxNonce query

---

Libplanet.Standalone/Hosting/LibplanetNodeService.cs

Shuffle ice servers

---

NineChronicles.Standalone/BlockChainService.cs

Since exception thrown here is hidden, log them manually.

Logging for exceptions in PutTransaction

---

NineChronicles.Standalone/GraphTypes/BlockHeaderType.cs
NineChronicles.Standalone/GraphTypes/NodeStatus.cs
NineChronicles.Standalone/GraphTypes/StandaloneQuery.cs

Expose topmost blocks and genesis via GraphQL

---

.github/workflows/push.yml
.github/workflows/push_docker_image.yml

Upload docker image when 9c-main is changed

---

NineChronicles.Standalone/ActionEvaluationHub.cs
NineChronicles.Standalone/ActionEvaluationPublisher.cs

SSIA. See also: https://github.com/planetarium/NineChronicles.RPC.Shared/pull/7

Enrich RenderBlock event

---

Libplanet.Standalone/Hosting/LibplanetNodeService.cs

Will report `RPCException.ChainTooLowException` (0x02) via graphql.

Report NodeException when the chain's tip is far beyond network's tip

---

Libplanet.Standalone/Hosting/LibplanetNodeService.cs
NineChronicles.Standalone.Executable/Program.cs
NineChronicles.Standalone.Tests/Common/ServiceBuilder.cs
NineChronicles.Standalone.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Standalone.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Standalone/ActionEvaluationHub.cs
NineChronicles.Standalone/ActionEvaluationPublisher.cs
NineChronicles.Standalone/BlockChainService.cs
NineChronicles.Standalone/GraphTypes/BlockHeaderType.cs
NineChronicles.Standalone/GraphTypes/NodeStatus.cs
NineChronicles.Standalone/GraphTypes/StandaloneMutation.cs
NineChronicles.Standalone/GraphTypes/StandaloneQuery.cs
NineChronicles.Standalone/GraphTypes/TxIdType.cs
NineChronicles.Standalone/GraphTypes/ValidationQuery.cs
NineChronicles.Standalone/NineChroniclesNodeService.cs
NineChronicles.Standalone/StandaloneContext.cs
NineChronicles.Standalone/StandaloneServices.cs

Please check if any commits are missing.

Pull from 9c-main to main

---

NineChronicles.Standalone/GraphTypes/ValidationQuery.cs

ValidationQuery returns true when unexpected exception occur

---

NineChronicles.Standalone/ActionEvaluationPublisher.cs
NineChronicles.Standalone/Controllers/GraphQLController.cs
NineChronicles.Standalone/ExceptionRenderer.cs

- Filtering subscribes in `ActionEvaluationPublisher`

Filtering subscribes in `ActionEvaluationPublisher`

---

NineChronicles.Standalone/ActionEvaluationPublisher.cs
NineChronicles.Standalone/BlockChainService.cs
NineChronicles.Standalone/Controllers/GraphQLController.cs
NineChronicles.Standalone/ExceptionRenderer.cs
NineChronicles.Standalone/NineChroniclesNodeService.cs
NineChronicles.Standalone/RPCContext.cs

Filters actions using addresses subscribe from the rpc client.

Filter action by addresses subscribed from client

---

NineChronicles.Standalone/BlockChainService.cs

Can be used in client by `_service.IsTransactionStaged(byte[] txidBytes)`.

Add RPC method to check is transaction staged

---

Libplanet.Standalone/Hosting/LibplanetNodeService.cs

Adjusted checkers' timeout and now exits check loop.

Refactor Swarm status checkers

---

Libplanet.Standalone/Hosting/LibplanetNodeService.cs
Libplanet.Standalone/NodeException.cs
NineChronicles.Standalone/BlockChainService.cs
NineChronicles.Standalone/NineChroniclesNodeService.cs

Send Unity error code on NodeException subscribe

---

NineChronicles.Standalone/BlockChainService.cs

Changed error code to 30 & 31. See also https://github.com/planetarium/nekoyume-unity/pull/3057

Change action timeout related error code

---

NineChronicles.Standalone/BlockChainService.cs

Add logs for expected nonce, tx and staged txs.

Add logging for tx related rpc requests

---

NineChronicles.Standalone/BlockChainService.cs

feat: logging when reported exception from Unity

---

.github/workflows/deploy_ghpackages_docker.yml

Account secrets have been added to settings.

Add GitHub packages workflow

---

NineChronicles.Standalone.Executable/AWSSink.cs
NineChronicles.Standalone.Executable/Program.cs

The log stream name will be determined through:
1. Use `standaloneContext.NineChroniclesNodeService.PrivateKey` if it is.
1. Use `standaloneContext.Swarm.Address` if it is.
1. If it doesn't satisfy any above conditions, it will not do anything and sleep 100ms while waiting to be ready to satisfy the conditions.
After, the mechanism will be better to be implemented with `future` having a queue to include log events.

fix(logging): deal with also GraphQL mode

---

NineChronicles.Standalone/Controllers/GraphQLController.cs
NineChronicles.Standalone/GraphTypes/NodeStatus.cs
NineChronicles.Standalone/GraphTypes/StandaloneQuery.cs
NineChronicles.Standalone/StandaloneContext.cs

The field is added under `nodeStatus` query.

Add query to know whether headless is mining

---

NineChronicles.Standalone/NineChroniclesNodeService.cs

*The PR <https://github.com/planetarium/lib9c/pull/239> & PR <https://github.com/planetarium/NineChronicles.RPC.Shared/pull/13> should be merged first, and the submodules should refer to their merge commits instead.*
Make it to publish `InvalidRenderException` through RPC on `--strict-rendering` mode.  The published RPC error should be handled by the client side.

Publish InvalidRenderException through RPC on --strict-rendering mode

---

NineChronicles.Headless/BlockChainInitializeException.cs
NineChronicles.Headless/GraphTypes/ValidationQuery.cs

Instead of just return true, it became to throw exception instead.

Throw when exception occurred during validating metadata

---

NineChronicles.Headless.Executable/Program.cs

This PR modifies the description in the executable Program.cs in response to @moreal's suggestion (https://github.com/planetarium/NineChronicles.Headless/pull/219#discussion_r547020461)

change standalone to headless

---

NineChronicles.Headless/Controllers/GraphQLController.cs
NineChronicles.Headless/GraphTypes/Notification.cs
NineChronicles.Headless/GraphTypes/NotificationEnum.cs
NineChronicles.Headless/GraphTypes/NotificationType.cs

- see also https://github.com/planetarium/9c-launcher/pull/492

Add new notification type

---

NineChronicles.Headless/Controllers/GraphQLController.cs

- logging agent address for player log matching

Logging agent address information

---

NineChronicles.Headless.Tests/Controllers/GraphQLControllerTest.cs
NineChronicles.Headless.Tests/Middleware/LocalAuthenticationMiddlewareTest.cs
NineChronicles.Headless/Controllers/GraphQLController.cs
NineChronicles.Headless/GraphQLService.cs
NineChronicles.Headless/Middleware/LocalAuthenticationMiddleware.cs

fix: correct validate local policy

---

NineChronicles.Headless.Executable/AWSSink.cs

Instead of looking previous logstream, use sequence token received from error response.

Use sequence token from InvalidSequenceTokenException

---

Libplanet.Headless/Hosting/LibplanetNodeService.cs

Don't restart Swarm when recent message is stale

---

NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless/NineChroniclesNodeService.cs
NineChronicles.Headless/StandaloneServices.cs
README.md

- make configurable lifetime on `VolatileStagePolicy<T>`

fix: make configurable Tx lifetime

---

NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Headless.Tests/SetAvatarState.cs
NineChronicles.Headless/GraphTypes/StateQuery.cs
NineChronicles.Headless/GraphTypes/States/Models/Item/ItemUsableType.cs
NineChronicles.Headless/GraphTypes/States/Models/Item/ShopItemType.cs
NineChronicles.Headless/GraphTypes/States/ShopStateType.cs

resolve #251 
```graphql
query {
stateQuery {
shop {
address
products {
sellerAgentAddress
sellerAvatarAddress
productId
price
itemUsable {
itemId
itemType
itemSubType
}
costume {
itemId
itemType
itemSubType
}
}
}
}
}
```

Introduce shop state query

---

NineChronicles.Headless/GraphQLService.cs

SSIA. And it is related to the #225 issue.

fix: remove 'AllowAllOrigins' CORS policy

---

Libplanet.Headless/Hosting/DevLibplanetNodeService.cs
Libplanet.Headless/Hosting/LibplanetNodeService.cs
Libplanet.Headless/Hosting/LibplanetNodeServiceProperties.cs
NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless.Tests/Common/ServiceBuilder.cs
NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs
README.md

This PR adds three application arguments:
- `--message-timeout`
- `--tip-timeout`
- `--demand-buffer`
which are the exit condition of libplanet node service.

Configurable exit condition constants

---

.github/stale.yaml

This introduces [Stale](https://probot.github.io/apps/stale/) to moderate issues

Introduce stale

---

.github/workflows/push_docker_image.yml

ci: update push_docker_image.yml

---

NineChronicles.Headless.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Headless/GraphTypes/ActionMutation.cs

Improve Buy mutation

---

NineChronicles.Headless.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Headless/GraphTypes/ActionMutation.cs

Update action mutations

---

NineChronicles.Headless.Tests/GraphQLTestUtils.cs
NineChronicles.Headless.Tests/GraphTypes/GraphQLTestBase.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/AgentStateTypeTest.cs
NineChronicles.Headless/GraphQLService.cs
NineChronicles.Headless/GraphQLServiceExtensions.cs
NineChronicles.Headless/GraphTypes/StateQuery.cs
NineChronicles.Headless/GraphTypes/States/AgentStateType.cs
NineChronicles.Headless/GraphTypes/States/Models/Item/EquipmentType.cs

Introduce AgentState query

---

NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
NineChronicles.Headless/GraphTypes/StateQuery.cs

This PR takes a `block hash` as an offset for [GetState()](https://github.com/planetarium/libplanet/blob/95a8409bf11017d742be14ff19e49b913ceaeb42/Libplanet/Blockchain/BlockChain.cs#L490).
The code seems a little verbose(especially the `if else` logic) so I'm open to suggestions 😄

add height to statequery

---

NineChronicles.Headless.Tests/GraphTypes/GraphQLTestBase.cs
NineChronicles.Headless/GraphTypes/StateQuery.cs

Resolve conflict in development branch

---

NineChronicles.Headless/NineChroniclesNodeService.cs

Avoid NRE in minerLoopAction

---

NineChronicles.Headless/Controllers/GraphQLController.cs

Fix NotifyAction subscribe

---

.github/workflows/push_docker_image.yml

This PR builds `development branch` Docker images and pushes it to Docker Hub.

update docker workflow

---

.github/workflows/deploy_gh_pages.yml
schema.graphql

- close #311
- you can see example this [page](https://ipdae.github.io/NineChronicles.Headless/)

Intoduce gh pages

---

NineChronicles.Headless.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Headless/Controllers/GraphQLController.cs
NineChronicles.Headless/GraphTypes/ActionMutation.cs
NineChronicles.Headless/GraphTypes/States/Models/Item/CostumeType.cs
NineChronicles.Headless/GraphTypes/States/Models/Item/ShopItemType.cs
schema.graphql

Update action version

---

NineChronicles.Headless.Executable.Tests/Commands/ChainCommandTest.cs
NineChronicles.Headless.Executable.Tests/Store/IStoreExtensionsTest.cs
NineChronicles.Headless.Executable.Tests/Store/StoreTypeExtensionsTest.cs
NineChronicles.Headless.Executable/Commands/ChainCommand.cs
NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj
NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless.Executable/Store/IStoreExtensions.cs
NineChronicles.Headless.Executable/Store/NoOpStateStore.cs
NineChronicles.Headless.Executable/Store/StoreType.cs
NineChronicles.Headless.Executable/Store/StoreTypeExtensions.cs
README.md

feat: introduce `chain tip` subcommand 

---

NineChronicles.Headless.Executable.Tests/Commands/ChainCommandTest.cs
NineChronicles.Headless.Executable.Tests/Store/IStoreExtensionsTest.cs
NineChronicles.Headless.Executable.Tests/Store/StoreTypeExtensionsTest.cs
NineChronicles.Headless.Executable/Commands/ChainCommand.cs
NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj
NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless.Executable/Store/IStoreExtensions.cs
NineChronicles.Headless.Executable/Store/NoOpStateStore.cs
NineChronicles.Headless.Executable/Store/StoreType.cs
NineChronicles.Headless.Executable/Store/StoreTypeExtensions.cs
README.md

Port #348 to rc-v100035

---

Libplanet.Headless/Hosting/LibplanetNodeService.cs

bump lib9c rc-v100036

---

NineChronicles.Headless.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Headless/Controllers/GraphQLController.cs
NineChronicles.Headless/GraphTypes/ActionMutation.cs
NineChronicles.Headless/GraphTypes/States/Models/Item/CostumeType.cs
NineChronicles.Headless/GraphTypes/States/Models/Item/ShopItemType.cs
schema.graphql

Revert "Merge pull request #344 from ipdae/improve/update-action"

---

NineChronicles.Headless.Executable.sln

The solution file hadn't been built as it had lacked  *Libplanet.Analyzers* project that it depends on.

Fix broken build

---

NineChronicles.Headless/BlockChainService.cs

Implement members added to the interface

---

NineChronicles.Headless/BlockChainService.cs

Fix GetTip method

---

NineChronicles.Headless/GraphTypes/NodeStatus.cs
NineChronicles.Headless/GraphTypes/PeerChainStateQuery.cs
NineChronicles.Headless/GraphTypes/TransactionType.cs

This PR adds descriptions for tx, nodeStatus and peerChainState queries.
it resolves #312 and #313

Descriptions for tx, nodeStatus and peerChainState

---

NineChronicles.Headless/ActionEvaluationPublisher.cs

This PR fixes RPC errors in-game UI by discarding shop state from rendering result. (it's a workaround and we should reduce shop state in near future.)

Fix RPC error (caused by ObjectDisposedException)

---

NineChronicles.Headless.Tests/GraphTypes/States/Models/AgentStateTypeTest.cs
NineChronicles.Headless/BlockChainExtensions.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
NineChronicles.Headless/GraphTypes/StateQuery.cs
NineChronicles.Headless/GraphTypes/States/AgentStateType.cs

fix(graphql): pass state & balance getter into subfields

---

NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless.Tests/Controllers/GraphQLControllerTest.cs
NineChronicles.Headless/Controllers/GraphQLController.cs

This pull request does
- Remove `/run-standalone` HTTP endpoint.
- Remove `--libplanet-node` option.
- Run libplanet headless in default.

feat(cli): run libplanet node as default

---

NineChronicles.Headless.Tests/GraphTypes/States/Models/CombinationSlotStateTypeTest.cs
NineChronicles.Headless/GraphTypes/StateQuery.cs
NineChronicles.Headless/GraphTypes/States/CombinationSlotStateType.cs

Introduce CombinationSlotState query

---

Libplanet.Headless/Hosting/LibplanetNodeService.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneSubscriptionTest.cs

This PR addresses some features as below that related node start-up
- Delayed obsoleted chain checking and pruning after preloading. (closes #417 )
- Added support for local file as the genesis block 
- Added event notification before bootstrapping. it can help the user to distingiush the actual preloading phase.

Enhance start-up experience

---

NineChronicles.Headless/GraphTypes/KeyStoreMutation.cs
NineChronicles.Headless/GraphTypes/KeyStoreType.cs
NineChronicles.Headless/GraphTypes/PrivateKeyType.cs
NineChronicles.Headless/GraphTypes/ProtectedPrivateKeyType.cs
NineChronicles.Headless/GraphTypes/PublicKeyType.cs
NineChronicles.Headless/GraphTypes/TransactionType.cs
NineChronicles.Headless/GraphTypes/ValidationQuery.cs

Release v100040

---

NineChronicles.Headless.Executable.sln
NineChronicles.Headless/NineChronicles.Headless.csproj

See also: <https://github.com/planetarium/libplanet/pull/1244>.

Bump Libplanet & use Libplanet.Explorer in submodule instead of NuGet

---

Libplanet.Headless/Hosting/LibplanetNodeService.cs

Merge rc-v100043 into main

---

NineChronicles.Headless.Tests/GraphTypes/StandaloneSubscriptionTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/AgentStateTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/FungibleAssetValueTypeTest.cs
NineChronicles.Headless/GraphTypes/FungibleAssetValueType.cs
NineChronicles.Headless/GraphTypes/States/AgentStateType.cs

Enable minor unit option

---

NineChronicles.Headless.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Headless/GraphTypes/ActionMutation.cs

Disable cancel monster collect

---

NineChronicles.Headless/GraphTypes/ActionMutation.cs

Prevent MonsterCollect mutation when state already exist

---

NineChronicles.Headless.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Headless/GraphTypes/StandaloneMutation.cs

This pull request resolves #493

feat(graphql): add memo field to transfer mutation

---

NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/TransferNCGHistoryTypeTest.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
NineChronicles.Headless/GraphTypes/TransferNCGHistoryType.cs
NineChronicles.Headless/TransferNCGHistory.cs

feat(graphql): add `memo` field on `TransferNCGHistory` type

---

NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Headless/GraphTypes/StateQuery.cs

Fix wrong argument name

---

NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless/NineChroniclesNodeService.cs
NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs
README.md

Here is the code snippet you requested.
1. I made this edit.
2. Applied this patch: https://github.com/planetarium/libplanet/commit/425320bc5d8140a9817a56988b144510416bef72
3. Compiled with docker

Added multithread snippet to mining function

---

.editorconfig
Libplanet.Headless/Hosting/LibplanetNodeService.cs
Libplanet.Headless/Hosting/LibplanetNodeServiceProperties.cs
NineChronicles.Headless.Executable.sln
NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs
README.md

This PR adds `--skip-preload` flag to skipping preloading when startup.

Add --skip-preload and LibplanetNodeServiceProperties.Preload

---

Libplanet.Headless/Hosting/DevLibplanetNodeService.cs

This PR fixes blocking issues by returning `Task` created by `Task.Run()` to enables other services than `DevLibplanetNodeService`.

Fix blocking issues between services

---

NineChronicles.Headless.Executable/Program.cs

This PR addresses #523 and #527

Force delete temporary log files while starting

---

NineChronicles.Headless.Tests/GraphTypes/States/Models/EquipmentTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/SkillTypeTest.cs
NineChronicles.Headless/GraphTypes/States/Models/Item/EquipmentType.cs
NineChronicles.Headless/GraphTypes/States/Models/SkillType.cs
NineChronicles.Headless/GraphTypes/States/Models/StatsMapType.cs

- Add some equipment information (level, grade, skills, etc)

Add more equipment information

---

LICENSE

This PR adds `LICENSE` for [AGPLv3](https://www.gnu.org/licenses/agpl-3.0.en.html) as we decided.

Licensing (AGPLv3)

---

NineChronicles.Headless.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneSubscriptionTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/MonsterCollectionStateTypeTest.cs
NineChronicles.Headless/GraphTypes/ActionMutation.cs
NineChronicles.Headless/GraphTypes/MonsterCollectionStatus.cs
NineChronicles.Headless/GraphTypes/MonsterCollectionStatusType.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs
NineChronicles.Headless/GraphTypes/StateQuery.cs
NineChronicles.Headless/GraphTypes/States/AgentStateType.cs
NineChronicles.Headless/GraphTypes/States/MonsterCollectionStateType.cs

This PR adjusts GraphQL APIs related to monster collection. (see aslo https://github.com/planetarium/lib9c/pull/455 and https://github.com/planetarium/lib9c/pull/481)

Revise monster collection

---

NineChronicles.Headless.Tests/GraphTypes/StandaloneSubscriptionTest.cs
NineChronicles.Headless/GraphTypes/ActionMutation.cs
NineChronicles.Headless/GraphTypes/MonsterCollectionStatus.cs
NineChronicles.Headless/GraphTypes/MonsterCollectionStatusType.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs
NineChronicles.Headless/GraphTypes/StateQuery.cs

This PR fixes GraphQL APIs to apply new monster collection spec.

GraphQL fixes for MonsterCollection

---

.github/workflows/deploy_gh_pages.yml

Fix deploy gh pages

---

NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs

This PR is the continued work of #556 .

Apply offset for delayed renderer

---

NineChronicles.Headless/GraphTypes/States/Models/World/WorldInformationType.cs

Fix wrong resolve in worldInformation query

---

NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Headless/GraphTypes/NodeStatus.cs

This PR adds an `offset` parameter to the `topmostblock` query so that the launcher can utilize it to show confirmed blocks mined by players instead of showing the blocks mined from the chain tip which are prone to `reorg`.

add offset parameter to topmostblock query

---

NineChronicles.Headless/GraphTypes/StandaloneQuery.cs

- resolve https://github.com/planetarium/9c-onboarding/issues/74

Introduce invitation key activated query

---

NineChronicles.Headless/GraphTypes/StandaloneQuery.cs

Validate code in activated query

---

.github/workflows/build.yml
Libplanet.Headless.Tests/Hosting/LibplanetNodeServiceTest.cs
Libplanet.Headless/ReducedStore.cs
NineChronicles.Headless.Executable.Tests/Commands/ChainCommandTest.cs
NineChronicles.Headless.Executable.Tests/Store/IStoreExtensionsTest.cs
NineChronicles.Headless.Tests/Controllers/GraphQLControllerTest.cs
NineChronicles.Headless.Tests/GraphTypes/GraphQLTestBase.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneSubscriptionTest.cs
NineChronicles.Headless.Tests/GraphTypes/TransactionHeadlessQueryTest.cs
NineChronicles.Headless/ReorgPolicy.cs

<del timestamp="2021-07-30T13:35:00+09:00">This pull request has to be adjusted and merged after <https://github.com/planetarium/lib9c/pull/521> is merged.</del> <ins timestamp="2021-07-30T13:35:00+09:00">Now this pull request is ready for review.</ins>

Upgrade Lib9c & Libplanet to 0.13.1

---

.github/workflows/build.yml
Libplanet.Headless.Tests/Hosting/LibplanetNodeServiceTest.cs
Libplanet.Headless/ReducedStore.cs
NineChronicles.Headless.Executable.Tests/Commands/ChainCommandTest.cs
NineChronicles.Headless.Executable.Tests/Store/IStoreExtensionsTest.cs
NineChronicles.Headless.Tests/Controllers/GraphQLControllerTest.cs
NineChronicles.Headless.Tests/GraphTypes/GraphQLTestBase.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneSubscriptionTest.cs
NineChronicles.Headless.Tests/GraphTypes/TransactionHeadlessQueryTest.cs
NineChronicles.Headless/GraphTypes/NodeStatus.cs
NineChronicles.Headless/GraphTypes/StandaloneMutation.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
NineChronicles.Headless/GraphTypes/TransactionHeadlessQuery.cs
NineChronicles.Headless/ReorgPolicy.cs

Merge rc-v100065 into main

---

NineChronicles.Headless/ActionEvaluationHub.cs
NineChronicles.Headless/ActionEvaluationPublisher.cs
NineChronicles.Headless/BlockChainService.cs
NineChronicles.Headless/GraphTypes/ActivationStatusQuery.cs
NineChronicles.Headless/HostBuilderExtensions.cs

- Update RPC interface for multiple clients https://github.com/planetarium/NineChronicles.RPC.Shared/pull/15
- Add new activated query for launcher https://github.com/planetarium/9c-launcher/pull/891

Introduce multiple client

---

NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless/ActionEvaluationPublisher.cs
NineChronicles.Headless/BlockChainService.cs
NineChronicles.Headless/HostBuilderExtensions.cs
NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs
NineChronicles.Headless/Properties/RpcNodeServiceProperties.cs
NineChronicles.Headless/RPCContext.cs

- Introduce `rpc-remote-server` flag for avoid duplicate action render called.

Avoid duplicate action render called

---

NineChronicles.Headless.Executable.Tests/Commands/ActionCommandTest.cs
NineChronicles.Headless.Executable.Tests/Commands/TxCommandTest.cs
NineChronicles.Headless.Executable/Commands/ActionCommand.cs
NineChronicles.Headless.Executable/Commands/TxCommand.cs
NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Headless.Tests/NineChronicles.Headless.Tests.csproj
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs

- Add api for rpc mode activation.
- get nonce query
- action command for tx
- tx command for remote mutation

Introduce tx command

---

NineChronicles.Headless/ActionEvaluationPublisher.cs

Fix duplicate action render called

---

NineChronicles.Headless.Executable.Tests/Commands/ChainCommandTest.cs
NineChronicles.Headless.Executable/Commands/ChainCommand.cs

Merge `rc-v100079` into `development`

---

Libplanet.Headless/Hosting/DevLibplanetNodeService.cs
Libplanet.Headless/Hosting/LibplanetNodeService.cs
Libplanet.Headless/ReducedStore.cs
NineChronicles.Headless.Executable.Tests/Commands/ChainCommandTest.cs
NineChronicles.Headless.Executable.Tests/Store/IStoreExtensionsTest.cs
NineChronicles.Headless.Executable/Commands/ChainCommand.cs
NineChronicles.Headless.Executable/Store/IStoreExtensions.cs
NineChronicles.Headless.Executable/Store/NoOpStateStore.cs
NineChronicles.Headless.Tests/Controllers/GraphQLControllerTest.cs
NineChronicles.Headless.Tests/GraphTypes/TransactionHeadlessQueryTest.cs
NineChronicles.Headless/ActionEvaluationPublisher.cs
NineChronicles.Headless/BlockChainService.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
NineChronicles.Headless/NineChroniclesNodeService.cs

Reverts planetarium/NineChronicles.Headless#760 that I merged (along with #759) by mistake.

Revert "Catch up Libplanet upstream's API changes"

---

NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs

- resolve https://github.com/planetarium/9c-launcher/issues/1003

Handle error msg when invitation code format is wrong

---

Libplanet.Headless/Hosting/LibplanetNodeService.cs

Put some log on the `LibplanetNodeServices`

---

NineChronicles.Headless/ActionEvaluationPublisher.cs
NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs

- Bump lib9c
- Wait https://github.com/planetarium/lib9c/pull/713

Bump submodules

---

NineChronicles.Headless.Executable.sln.DotSettings
NineChronicles.Headless.Executable/Commands/ChainCommand.cs
NineChronicles.Headless/ActionEvaluationPublisher.cs
NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs

Merge `v100085` from `main`

---

.github/workflows/deploy_gh_pages.yml

This PR is follow-up PR of #859

Bump .NET SDK version in GH Action

---

NineChronicles.Headless.Tests/Controllers/GraphQLControllerTest.cs
NineChronicles.Headless/ActionEvaluationPublisher.cs
NineChronicles.Headless/Controllers/GraphQLController.cs

- disable .net6.0 compile warning
- return 400 error when set private key failed

Return BadRequest when SetPrivateKey failed

---

README.md

docs: correct readme

---

NineChronicles.Headless/ActionEvaluationPublisher.cs
NineChronicles.Headless/HostBuilderExtensions.cs

- relate from https://github.com/planetarium/lib9c/pull/742

Use MessagePackSerializer instead of BinaryFormatter

---

.github/workflows/build.yml
Dockerfile
Libplanet.Headless.Tests/Libplanet.Headless.Tests.csproj
Libplanet.Headless/Hosting/LibplanetNodeService.cs
Libplanet.Headless/Libplanet.Headless.csproj
NineChronicles.Headless.Executable.Tests/NineChronicles.Headless.Executable.Tests.csproj
NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj
NineChronicles.Headless.Tests/Controllers/GraphQLControllerTest.cs
NineChronicles.Headless.Tests/GraphQLStartupTest.cs
NineChronicles.Headless.Tests/GraphQLTestUtils.cs
NineChronicles.Headless.Tests/NineChronicles.Headless.Tests.csproj
NineChronicles.Headless/ActionEvaluationPublisher.cs
NineChronicles.Headless/Controllers/GraphQLController.cs
NineChronicles.Headless/HostBuilderExtensions.cs
NineChronicles.Headless/NineChronicles.Headless.csproj

[Bot] Merge rc-v100088 to development

---

NineChronicles.Headless/ActionEvaluationPublisher.cs

- logging broadcast action for check rpc render bug

Logging broadcast action render

---

NineChronicles.Headless.Tests/GraphTypes/StandaloneSubscriptionTest.cs
NineChronicles.Headless/GraphTypes/MonsterCollectionStatus.cs
NineChronicles.Headless/GraphTypes/MonsterCollectionStatusType.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs

- add tip index info for launcher subscribe

Add block index info

---

NineChronicles.Headless.Tests/GraphTypes/StandaloneSubscriptionTest.cs
NineChronicles.Headless/GraphTypes/MonsterCollectionStatus.cs
NineChronicles.Headless/GraphTypes/MonsterCollectionStatusType.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs

[Bot] Merge rc-v100089 to development

---

NineChronicles.Headless/ActionEvaluationPublisher.cs

Avoid KeyNotFoundException when renderer filter client

---

NineChronicles.Headless.Executable/appsettings.json

Output log file extension changed

---

NineChronicles.Headless/BlockChainService.cs

- bulk interface for reduce pvp page loading time.
in 9c client test result
```
GetAvatarStates service: 00:00:10.4562596
GetAvatarStates deserialize: 00:00:07.9844180
GetAvatarStates: 00:00:18.4410319
TryGetAvatarStateAsync: 00:01:41.1094759
```

Introduce GetAvatarStates

---

NineChronicles.Headless/BlockChainService.cs

- see with https://github.com/planetarium/NineChronicles/pull/1054

Introduce GetStateBulk

---

NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless.Executable/appsettings.json
NineChronicles.Headless/ActionEvaluationPublisher.cs
NineChronicles.Headless/BlockChainService.cs
NineChronicles.Headless/GraphQLService.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
NineChronicles.Headless/GraphTypes/States/AgentStateType.cs
NineChronicles.Headless/HostBuilderExtensions.cs
NineChronicles.Headless/NineChronicles.Headless.csproj

This reverts commit 98b7b42c858158e95ea5921fb34bcead84788095, reversing
changes made to c2f8ae808e6a4c5566bdfc1974cfcf3f1a192c43.

Revert "Merge pull request #938 from planetarium/rc-v100090"

---

NineChronicles.Headless.Executable/appsettings.json

Metric log formatter changed

---

NineChronicles.Headless/ActionEvaluationPublisher.cs
NineChronicles.Headless/BlockChainService.cs

Fix default address set in client list

---

.github/workflows/deploy_gh_pages.yml

Revert .net sdk version In gh action

---

NineChronicles.Headless.Tests/Controllers/GraphQLControllerTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneSubscriptionTest.cs
NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs
NineChronicles.Headless/StandaloneContext.cs

- introduce balance subscription for https://github.com/planetarium/9c-launcher/issues/1117

Introduce current balance subscription

---

NineChronicles.Headless.Tests/GraphTypes/GraphQLTestBase.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs

[Bot] Merge rc-v100097 to main

---

NineChronicles.Headless.Tests/GraphTypes/GraphQLTestBase.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs

[Bot] Merge rc-v100096 to main

---

NineChronicles.Headless/BlockChainService.cs

Update interface for reduce grpc request time

---

Libplanet.Headless.Tests/Libplanet.Headless.Tests.csproj
NineChronicles.Headless.Executable.Tests/NineChronicles.Headless.Executable.Tests.csproj
NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj
NineChronicles.Headless.Tests/AccountStateGetterExtensionTest.cs
NineChronicles.Headless.Tests/Controllers/GraphQLControllerTest.cs
NineChronicles.Headless.Tests/GraphQLStartupTest.cs
NineChronicles.Headless.Tests/GraphQLTestUtils.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/AgentStateTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/ShopStateTypeTest.cs
NineChronicles.Headless.Tests/NineChronicles.Headless.Tests.csproj
NineChronicles.Headless/AccountStateGetterExtension.cs
NineChronicles.Headless/BlockChainExtensions.cs
NineChronicles.Headless/BlockChainService.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
NineChronicles.Headless/GraphTypes/StateQuery.cs
NineChronicles.Headless/GraphTypes/States/AgentStateType.cs
NineChronicles.Headless/GraphTypes/States/StateContext.cs

See also:
- <https://github.com/planetarium/lib9c/pull/814>
- <https://github.com/planetarium/libplanet/pull/1703>

Bump Lib9c & apply `BlockChain<T>.GetStates()` API

---

NineChronicles.Headless.Executable.Tests/Commands/GenesisCommandTest.cs
NineChronicles.Headless.Executable.sln
NineChronicles.Headless.Executable/Commands/GenesisCommand.cs
NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Headless/GraphTypes/ActionMutation.cs
NineChronicles.Headless/GraphTypes/States/AvatarStateType.cs
NineChronicles.Headless/NineChronicles.Headless.csproj

- resolve #996 
- see also https://github.com/planetarium/lib9c/pull/813

Introduce genesis command

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

This pull request resolves #1005

Setup devcontainer for GitHub Codespace

---

Libplanet.Headless/Libplanet.Headless.csproj
NineChronicles.Headless.Executable.sln

- https://github.com/planetarium/libplanet/releases/tag/0.27.0
- https://github.com/planetarium/lib9c/pull/831

Bump Lib9c & upgrade Libplanet to 0.27.0

---

.github/workflows/push_docker_image.yml

It's a fix of a mistake I made in the previous PR <https://github.com/planetarium/NineChronicles.Headless/pull/1071>.

Fix GitHub Actions context expansions

---

NineChronicles.Headless/ActionEvaluationPublisher.cs

compress action evaluation size

Compress action evaluation

---

Libplanet.Headless/Libplanet.Headless.csproj
NineChronicles.Headless.Executable.sln
NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj

[Bot] Merge rc-v100120 to development

---

NineChronicles.Headless/AccountStateGetterExtension.cs
NineChronicles.Headless/BlockChainService.cs

Introduce GetRawAvatarStates

---

NineChronicles.Headless.Tests/GraphTypes/States/Models/MonsterCollectionRowTypeTest.cs
NineChronicles.Headless/BlockChainService.cs

Fix invalid address serialization

Fix invalid serialize address

---

.github/workflows/push_docker_image.yml

chore: ci build branch name changed

---

NineChronicles.Headless.Executable.Tests/ProgramTest.cs
NineChronicles.Headless/Controllers/GraphQLController.cs
NineChronicles.Headless/GraphQLService.cs
NineChronicles.Headless/HostBuilderExtensions.cs

This pull request doesn't bump to .NET 6 but it updates code acceptable also in .NET 6 version.

Prepare .NET 6 bump

---

.gitmodules

It will let people outside @planetarium easily contribute to the project.

Use HTTPS for submodule URLs

---

NineChronicles.Headless/GraphTypes/NodeStatus.cs

See https://github.com/planetarium/NineChronicles.Headless/issues/1127

feat(graphql): introduce `nodeStatus.appProtocolVersion`

---

.github/workflows/release.yaml
.gitmodules
Libplanet.Headless/Hosting/LibplanetNodeService.cs
Libplanet.Headless/Libplanet.Headless.csproj
NineChronicles.Headless.Executable.Tests/ProgramTest.cs
NineChronicles.Headless.Executable/Store/StoreTypeExtensions.cs
NineChronicles.Headless/ActionEvaluationPublisher.cs
NineChronicles.Headless/Controllers/GraphQLController.cs
NineChronicles.Headless/GraphQLService.cs
NineChronicles.Headless/GraphTypes/NodeStatus.cs
NineChronicles.Headless/GraphTypes/StandaloneMutation.cs
NineChronicles.Headless/HostBuilderExtensions.cs

- Merge the `main` branch into the `previewnet` branch.
- Bump `lib9c:previewnet` into `NineChronicles.Headless:previewnet`.

Update the `previewnet` branch

---

.github/workflows/release.yaml

merge rc-v100160 into development

---

.github/workflows/push_docker_image.yml
NineChronicles.Headless/NineChroniclesNodeService.cs
NineChronicles.Headless/Properties/NetworkType.cs

- Merge the `previewnet` branch into the `development` branch.
- Bump `lib9c:development` into `development`.

Update the `development` branch

---

NineChronicles.Headless/ActionEvaluationPublisher.cs

- Fix timeout when RankingBattle execution failed.

Fix timeout when RankingBattle failed

---

NineChronicles.Headless.Executable/appsettings.json

change logging option for multiline logging. https://www.datadoghq.com/blog/multiline-logging-guide/

Use JsonFormatter for multiline logging

---

.github/workflows/build.yml
Dockerfile
Dockerfile.amd64
Dockerfile.arm64v8
Libplanet.Headless.Tests/Libplanet.Headless.Tests.csproj
Libplanet.Headless/Hosting/LibplanetNodeService.cs
Libplanet.Headless/Libplanet.Headless.csproj
NineChronicles.Headless.Executable.Tests/NineChronicles.Headless.Executable.Tests.csproj
NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj
NineChronicles.Headless.Tests/NineChronicles.Headless.Tests.csproj
NineChronicles.Headless/NineChronicles.Headless.csproj

This pull request resolves #1067

Update target to net6

---

NineChronicles.Headless/ActionEvaluationPublisher.cs

Bump `lib9c:rv-v100180`

---

.github/workflows/build.yml
Dockerfile
Dockerfile.amd64
Dockerfile.arm64v8
Libplanet.Headless.Tests/Libplanet.Headless.Tests.csproj
Libplanet.Headless/Hosting/LibplanetNodeService.cs
Libplanet.Headless/Libplanet.Headless.csproj
Libplanet.Headless/ReducedStore.cs
NineChronicles.Headless.Executable.Tests/NineChronicles.Headless.Executable.Tests.csproj
NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj
NineChronicles.Headless.Executable/appsettings.json
NineChronicles.Headless.Tests/NineChronicles.Headless.Tests.csproj
NineChronicles.Headless/ActionEvaluationPublisher.cs
NineChronicles.Headless/NineChronicles.Headless.csproj
NineChronicles.Headless/NineChroniclesNodeService.cs

Rc v100180 to main

---

NineChronicles.Headless/ActionEvaluationPublisher.cs

Merge `v100180` into `development`

---

NineChronicles.Headless.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Headless/GraphTypes/ActionMutation.cs
NineChronicles.Headless/GraphTypes/StandaloneMutation.cs

- Remove playCount. 
- Related link : https://github.com/planetarium/lib9c/pull/921

Remove playCount & bump lib9c

---

NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
NineChronicles.Headless/GraphTypes/ActionQuery.cs

- Add queries for CRYSTAL related actions

Introduce CRYSTAL action query

---

NineChronicles.Headless.Tests/Common/Fixtures.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/StakeAchievementsTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/StakeRegularRewardRowTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/StakeRegularRewardSheetTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/StakeStateTypeTest.cs
NineChronicles.Headless/GraphTypes/StateQuery.cs
NineChronicles.Headless/GraphTypes/States/Models/Table/StakeRegularRewardInfoType.cs
NineChronicles.Headless/GraphTypes/States/Models/Table/StakeRegularRewardRowType.cs
NineChronicles.Headless/GraphTypes/States/Models/Table/StakeRegularRewardSheetType.cs
NineChronicles.Headless/GraphTypes/States/StakeAchievementsType.cs
NineChronicles.Headless/GraphTypes/States/StakeStateType.cs

Introduce model queries related to `Stake`

---

NineChronicles.Headless.Tests/GraphTypes/States/Models/AgentStateTypeTest.cs
NineChronicles.Headless/GraphTypes/StateQuery.cs
NineChronicles.Headless/GraphTypes/States/AgentStateType.cs

- Add CRYSTAL balance query
- Add unlocked ids list query

Introduce CRYSTAL related model queries

---

NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
NineChronicles.Headless/GraphTypes/ActionQuery.cs
NineChronicles.Headless/GraphTypes/CurrencyType.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs

- reslove #1268 
- Introduce `TrasnferAsset` action query.
- Add missing `actionQuery` execute path.

Introduce TransferAsset query

---

Docs/BUILD_GENESIS.md
NineChronicles.Headless.Executable/Commands/GenesisCommand.cs

This pull request does:
- Check the required fields in the genesis config
- Introduce `How to build genesis block`
This pull request should be reviewed by @ipdae.

docs: introduce how to build genesis

---

NineChronicles.Headless/GraphTypes/States/Models/Table/StakeRegularRewardSheetType.cs

This pull request includes:
- https://github.com/planetarium/NineChronicles.Headless/pull/1292

Merge `2022q2` to `previewnet`

---

NineChronicles.Headless.Executable.Tests/Commands/ActionCommandTest.cs
NineChronicles.Headless.Executable.Tests/Commands/TxCommandTest.cs
NineChronicles.Headless.Executable/Commands/ActionCommand.cs
NineChronicles.Headless.Executable/Commands/TxCommand.cs
NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
NineChronicles.Headless/GraphTypes/ActionQuery.cs

This pull request provides APIs related to `MigrateMonsterCollection`.

Provide APIs for `MigrateMonsterCollection`

---

Libplanet.Headless/Hosting/LibplanetNodeService.cs

`Reactor` has `VoteSet` for previous block, which is `LastCommit` for newly mined block.

Hand over `LastCommit` when mining

---

Libplanet.Headless/Hosting/LibplanetNodeService.cs
Libplanet.Headless/Hosting/LibplanetNodeServiceProperties.cs
NineChronicles.Headless.Executable.Tests/ProgramTest.cs
NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs

chore: consensus argument

---

Libplanet.Headless.Tests/Hosting/LibplanetNodeServiceTest.cs
Libplanet.Headless/Hosting/LibplanetNodeService.cs
NineChronicles.Headless.Tests/Common/ServiceBuilder.cs
NineChronicles.Headless.Tests/Controllers/GraphQLControllerTest.cs
NineChronicles.Headless.Tests/GraphTypes/GraphQLTestBase.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs

`Swarm` contains `ConsensusReactor`.

Merge `ConsensusReactor` and `Swarm`

---

NineChronicles.Headless/ActionEvaluationPublisher.cs

related link : https://github.com/planetarium/lib9c/pull/1086

Add extra fields to battle arena

---

Libplanet.Headless/Hosting/DevLibplanetNodeService.cs
Libplanet.Headless/Hosting/LibplanetNodeService.cs
Libplanet.Headless/PropertyParser.cs

⬆️ Bump lib9c

---

NineChronicles.Headless.Executable/Commands/TxCommand.cs

hotfix: Remove useless output

---

NineChronicles.Headless.Executable/Commands/TxCommand.cs
NineChronicles.Headless/GraphTypes/States/Models/Table/StakeRegularRewardSheetType.cs

This pull request includes hotfix #1335.

Merge feature/stake to 2022q2

---

NineChronicles.Headless.Executable.Tests/Commands/ActionCommandTest.cs
NineChronicles.Headless.Executable.Tests/Commands/TxCommandTest.cs
NineChronicles.Headless.Executable/Commands/ActionCommand.cs
NineChronicles.Headless.Executable/Commands/TxCommand.cs
NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
NineChronicles.Headless/GraphTypes/ActionQuery.cs

SSIA. See also #1301.
Because this pull request is a simple cherry-pick, I'll merge it if the build passed.

Cherry-pick 2122c917c73ae971236ab12e6e8ff033e1ab7700

---

NineChronicles.Headless.Executable.Tests/ProgramTest.cs

Fix flaky test

---

Libplanet.Headless/Hosting/LibplanetNodeService.cs

- Bump `Lib9C`
- Simplify constructor argument of `Swarm<T>`
- Add proper modification on `LibplanetNodeService<T>`

feat: simplify constructor argument of `Swarm<T>`

---

NineChronicles.Headless/ActionEvaluationPublisher.cs

Merge v100230 into development

---

NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
NineChronicles.Headless/GraphTypes/ActionQuery.cs

Introduce PatchTableSheet action query.

Introduce PatchTableSheet query

---

.github/workflows/deploy_gh_pages.yml

https://github.com/planetarium/NineChronicles.Headless/actions/runs/2594765749

Fix deploy gh pages workflow

---

NineChronicles.Headless/GraphTypes/States/Models/Order/OrderBaseType.cs

Add resolving fields about OrderId and TradableId in OrderBaseType

---

NineChronicles.Headless.Executable/Commands/ChainCommand.cs

Originally, the `chain command` used `GetGenesisBlock<NCAction>()` method to retrieve the genesis block. Unfortunately, this method takes very long to complete so I've bypassed the `GetGenesisBlock<NCAction>()` method by retrieving the hash first and then getting the block using `GetBlock<NCAction>()`. Here's an example time comparison of the two methods:
```
<Original>
Block<NCAction> genesisBlock = store.GetGenesisBlock<NCAction>(blockPolicy.GetHashAlgorithm);
// Time taken: 38746.4047ms
<New>
var chainId = store.GetCanonicalChainId();
var genesisHash = store.IndexBlockHash(chainId, 0);
var genesisBlock = store.GetBlock<NCAction>(blockPolicy.GetHashAlgorithm, genesisHash);
// Time taken: 452.8261ms
```

improve speed with GetBlock

---

NineChronicles.Headless.Executable.Tests/Commands/ChainCommandTest.cs
NineChronicles.Headless.Executable/Commands/ChainCommand.cs

This PR adds a `Truncate` command in `NineChronicles.Headless.Executable` chain command which truncates the tip of the chain based on the input value (similar to `NineChronicles.Snapshot`).
Usage: `dotnet run -- chain truncate [Store-Type] [Store-Path] [Number-of-Blocks-to-Truncate]`

add truncate command

---

NineChronicles.Headless.Executable/Program.cs
README.md

resolves #1445 
---
`README.md` is outdated of `NineChronicles.Headless.Executable`'s execution option.
I've updated options and rearranged by semantic.
- Docker command line option is not updated

Update headless options

---

NineChronicles.Headless.Tests/GraphTypes/States/Models/CurrencyTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/FungibleAssetValueWithCurrencyTypeTest.cs
NineChronicles.Headless/GraphTypes/ActionQuery.cs
NineChronicles.Headless/GraphTypes/CurrencyEnumType.cs
NineChronicles.Headless/GraphTypes/CurrencyType.cs
NineChronicles.Headless/GraphTypes/FungibleAssetValueWithCurrencyType.cs

detailed Currency info for FungibleAssetValue query

detailed FungibleAssetValue info

---

NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/ScenarioTest.cs
NineChronicles.Headless/GraphTypes/ActionQuery.cs

- Introduce `Raid` action query.

Introduce Raid action query

---

NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/ScenarioTest.cs
NineChronicles.Headless.Tests/GraphTypes/SignScenarioTest.cs
NineChronicles.Headless.Tests/GraphTypes/WorldBossScenarioTest.cs
NineChronicles.Headless/GraphTypes/ActionQuery.cs
NineChronicles.Headless/GraphTypes/AddressQuery.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
NineChronicles.Headless/GraphTypes/StateQuery.cs
NineChronicles.Headless/GraphTypes/States/RaiderStateType.cs
NineChronicles.Headless/GraphTypes/States/WorldBossKillRewardRecordType.cs
NineChronicles.Headless/GraphTypes/States/WorldBossStateType.cs

- AddressQuery for find derive addresses
- RaiderState
- WorldBossState
- WorldBossKillRecord

Introduce world boss models

---

Libplanet.Headless.Tests/Hosting/LibplanetNodeServiceTest.cs
Libplanet.Headless/Hosting/DevLibplanetNodeService.cs
Libplanet.Headless/Hosting/LibplanetNodeService.cs
Libplanet.Headless/ReducedStore.cs
NineChronicles.Headless.Executable.Tests/Commands/ChainCommandTest.cs
NineChronicles.Headless.Executable.Tests/Store/IStoreExtensionsTest.cs
NineChronicles.Headless.Executable/Commands/ChainCommand.cs
NineChronicles.Headless.Executable/Commands/TxCommand.cs
NineChronicles.Headless.Executable/Store/IStoreExtensions.cs
NineChronicles.Headless.Tests/Controllers/GraphQLControllerTest.cs
NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/GraphQLTestBase.cs
NineChronicles.Headless.Tests/GraphTypes/ScenarioTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneSubscriptionTest.cs
NineChronicles.Headless.Tests/GraphTypes/TransactionHeadlessQueryTest.cs
NineChronicles.Headless/GraphQLServiceExtensions.cs
NineChronicles.Headless/GraphTypes/ActionQuery.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
NineChronicles.Headless/GraphTypes/TransactionHeadlessQuery.cs
NineChronicles.Headless/GraphTypes/TransactionType.cs
NineChronicles.Headless/GraphTypes/TxResult.cs
NineChronicles.Headless/GraphTypes/TxResultType.cs
NineChronicles.Headless/GraphTypes/TxStatusType.cs
NineChronicles.Headless/NineChroniclesNodeService.cs
NineChronicles.Headless/ReorgPolicy.cs

Bump lib9c for `libplanet 0.40`

---

README.md

This pull request attaches Discord invitation buttons on the README.

Add Discord invitation button

---

NineChronicles.Headless.Executable.Tests/Commands/ChainCommandTest.cs
NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/SignScenarioTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/CurrencyTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/FungibleAssetValueWithCurrencyTypeTest.cs
NineChronicles.Headless/GraphTypes/ActionMutation.cs
NineChronicles.Headless/GraphTypes/ActionQuery.cs
NineChronicles.Headless/GraphTypes/CurrencyEnumType.cs
NineChronicles.Headless/GraphTypes/CurrencyType.cs
NineChronicles.Headless/GraphTypes/FungibleAssetValueInputType.cs
NineChronicles.Headless/GraphTypes/FungibleAssetValueWithCurrencyType.cs

- Bump lib9c
- Cherrypick from #1459 
- Add query API `PrepareRewardAssets` action

Introduce PrepareRewardAssets action query

---

.github/workflows/push_docker_image.yml
NineChronicles.Headless.Executable.Tests/Commands/GenesisCommandTest.cs
NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/SignScenarioTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/CurrencyTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/FungibleAssetValueWithCurrencyTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/WorldBossScenarioTest.cs
NineChronicles.Headless/GraphTypes/ActionQuery.cs
NineChronicles.Headless/GraphTypes/AddressQuery.cs
NineChronicles.Headless/GraphTypes/CurrencyEnumType.cs
NineChronicles.Headless/GraphTypes/CurrencyType.cs
NineChronicles.Headless/GraphTypes/FungibleAssetValueInputType.cs
NineChronicles.Headless/GraphTypes/FungibleAssetValueWithCurrencyType.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
NineChronicles.Headless/GraphTypes/StateQuery.cs
NineChronicles.Headless/GraphTypes/States/RaiderStateType.cs
NineChronicles.Headless/GraphTypes/States/WorldBossKillRewardRecordType.cs
NineChronicles.Headless/GraphTypes/States/WorldBossStateType.cs

Merge world boss into development

---

NineChronicles.Headless.Executable.Tests/Commands/GenesisCommandTest.cs
NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/SignScenarioTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/CurrencyTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/FungibleAssetValueWithCurrencyTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/WorldBossScenarioTest.cs
NineChronicles.Headless/GraphTypes/CurrencyEnumType.cs
NineChronicles.Headless/GraphTypes/CurrencyInputType.cs
NineChronicles.Headless/GraphTypes/FungibleAssetValueInputType.cs
NineChronicles.Headless/GraphTypes/StateQuery.cs

Introduce balance query

---

NineChronicles.Headless.Tests/GraphTypes/WorldBossScenarioTest.cs
NineChronicles.Headless/GraphTypes/StateQuery.cs

- Added option to raidId query for look up previous season rewards.

Find previous raid id

---

Libplanet.Headless.Tests/Hosting/LibplanetNodeServiceTest.cs
Libplanet.Headless/Hosting/LibplanetNodeService.cs
NineChronicles.Headless.Executable.Tests/Commands/ChainCommandTest.cs
NineChronicles.Headless.Executable.Tests/Store/IStoreExtensionsTest.cs
NineChronicles.Headless.Executable/Commands/GenesisCommand.cs
NineChronicles.Headless.Tests/Controllers/GraphQLControllerTest.cs
NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/GraphQLTestBase.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneSubscriptionTest.cs
NineChronicles.Headless.Tests/GraphTypes/TransactionHeadlessQueryTest.cs
NineChronicles.Headless/GraphTypes/PeerChainStateQuery.cs

[PBFT] Bump lib9c

---

NineChronicles.Headless.Tests/GraphTypes/WorldBossScenarioTest.cs
NineChronicles.Headless/GraphTypes/StateQuery.cs

Cherry raid id query

---

Libplanet.Headless/PropertyParser.cs

Support argument input for BLS public key

chore: support bls public key in parser

---

Libplanet.Headless/Hosting/LibplanetNodeServiceProperties.cs
Libplanet.Headless/ReducedStore.cs
NineChronicles.Headless.Executable/Commands/ActionCommand.cs
NineChronicles.Headless.Tests/Common/Fixtures.cs
NineChronicles.Headless.Tests/Common/ServiceBuilder.cs
NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/GraphQLTestBase.cs
NineChronicles.Headless.Tests/GraphTypes/SignScenarioTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneSubscriptionTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/AgentStateTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/CurrencyTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/FungibleAssetValueTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/FungibleAssetValueWithCurrencyTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/StakeStateTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/TransferNCGHistoryTypeTest.cs
NineChronicles.Headless/DifferentAppProtocolVersionEncounter.cs
NineChronicles.Headless/GraphQLServiceExtensions.cs
NineChronicles.Headless/GraphTypes/CurrencyInputType.cs
NineChronicles.Headless/GraphTypes/FungibleAssetValueInputType.cs
NineChronicles.Headless/HostBuilderExtensions.cs
NineChronicles.Headless/NineChroniclesNodeService.cs

Second attempt at bumping libplanet. Should be fine this time...
Prerequisite: https://github.com/planetarium/lib9c/pull/1373

Bump lib9c for libplanet 0.41.2

---

Libplanet.Headless/Hosting/LibplanetNodeService.cs
Libplanet.Headless/Hosting/LibplanetNodeServiceProperties.cs
Libplanet.Headless/PropertyParser.cs
Libplanet.Headless/ReducedStore.cs
NineChronicles.Headless.Executable.Tests/Commands/GenesisCommandTest.cs
NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless.Tests/Common/ServiceBuilder.cs
NineChronicles.Headless.Tests/Controllers/GraphQLControllerTest.cs
NineChronicles.Headless.Tests/GraphTypes/GraphQLTestBase.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs

Added new program argument `--consensus-seed` which is used for seed peers for the PBFT consensus.

[PBFT] Bump libplanet for consensus seed

---

NineChronicles.Headless.Tests/GraphTypes/WorldBossScenarioTest.cs
NineChronicles.Headless/GraphTypes/StateQuery.cs

Merge 100300 into development

---

NineChronicles.Headless.Tests/GraphTypes/States/Models/AgentStateTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/AvatarStateTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/StakeStateTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/WorldBossScenarioTest.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
NineChronicles.Headless/GraphTypes/StateQuery.cs
NineChronicles.Headless/GraphTypes/States/AgentStateType.cs
NineChronicles.Headless/GraphTypes/States/AvatarStateType.cs
NineChronicles.Headless/GraphTypes/States/StakeStateType.cs
NineChronicles.Headless/GraphTypes/States/StateContext.cs

This pull request merges v100301 to `development` branch. There are so many commits but it's because the hotfix commits weren't applied yet. We should avoid merge `rc-v*` branch instead of `v*` tag.
I'll merge when the build passed.

Apply v100301 to development branch

---

README.md

Refurnish and remove outdated content.

update `README.md` to latest

---

NineChronicles.Headless/GraphTypes/StateQuery.cs

This PR adds a new `StakeStates` field to look up multiple `StakeState` by a bunch of addresses. it closes #1650.

Add `StakeStates` field to `stateQuery`

---

NineChronicles.Headless.Executable/Configuration.cs
NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj
NineChronicles.Headless.Executable/Program.cs

Drop features related to AWS

---

NineChronicles.Headless.Tests/GraphTypes/WorldBossScenarioTest.cs
NineChronicles.Headless/GraphTypes/AddressQuery.cs

Fix raider address query always deriven from default address result

Fix invalid raider address query

---

NineChronicles.Headless.Tests/GraphTypes/WorldBossScenarioTest.cs
NineChronicles.Headless/GraphTypes/AddressQuery.cs
NineChronicles.Headless/GraphTypes/StateQuery.cs

- Introduce raiderList address query by world boss season.
- Introduce raiderList state query.

Introduce raider list query

---

NineChronicles.Headless/ActionEvaluationPublisher.cs

Fixed renderers to work in parallel if they were intended to run in parallel but didn't.

Add ObserveOn on ActionEvaluationPublisher

---

NineChronicles.Headless.Executable.Tests/Commands/ActionCommandTest.cs
NineChronicles.Headless.Executable.sln
NineChronicles.Headless.Tests/NineChronicles.Headless.Tests.csproj
NineChronicles.Headless/GraphTypes/States/Models/Table/MonsterCollectionSheetType.cs
NineChronicles.Headless/NineChronicles.Headless.csproj

- Bump submodule `lib9c:development`
- Fix solution and projects settings
- (WIP)Fix possible null references

Bump submodule `lib9c:development` and fix others

---

NineChronicles.Headless.Tests/GraphTypes/GraphQLTestBase.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneSubscriptionTest.cs
NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs
NineChronicles.Headless/StandaloneContext.cs

This PR resolves https://github.com/planetarium/NineChronicles.Headless/issues/1684.

update gql subscription

---

NineChronicles.Headless.Tests/GraphTypes/GraphQLTestBase.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneSubscriptionTest.cs
NineChronicles.Headless/ActionEvaluationPublisher.cs
NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs
NineChronicles.Headless/StandaloneContext.cs

This PR cherry-picks fixes already merged onto development as below.
- https://github.com/planetarium/NineChronicles.Headless/pull/1682
- https://github.com/planetarium/NineChronicles.Headless/pull/1683
- https://github.com/planetarium/NineChronicles.Headless/pull/1688

Port fixes & Release v100321-2

---

NineChronicles.Headless.Executable.Tests/Commands/ActionCommandTest.cs
NineChronicles.Headless.Executable.Tests/Commands/ChainCommandTest.cs
NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/SignScenarioTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Headless/GraphTypes/ActionMutation.cs
NineChronicles.Headless/GraphTypes/ActionQuery.cs
NineChronicles.Headless/GraphTypes/RuneSlotInfoInputType.cs
NineChronicles.Headless/GraphTypes/RuneSlotInfoType.cs

- bump lib9c for rune
- introduce RuneSlotInfo graphql types

Introduce RuneSlotInfoType

---

NineChronicles.Headless/GraphTypes/NodeStatus.cs
NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs

Release v100321-3

---

NineChronicles.Headless/GraphTypes/NodeStatus.cs

This release added:
- `stagedTxIdsCount` field in `nodeStatus`
- `subscriberAddressesCount` field in `nodeStatus`

Release v100321-4

---

NineChronicles.Headless.Executable.Tests/Commands/ActionCommandTest.cs
NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/SignScenarioTest.cs
NineChronicles.Headless/GraphTypes/ActionQuery.cs
NineChronicles.Headless/GraphTypes/RecipientsInputType.cs

- TransferAssets query API for bulk transfer asset

Introduce TransferAssets action query

---

NineChronicles.Headless.Executable/Commands/ActionCommand.cs
NineChronicles.Headless.Executable/Commands/TxCommand.cs
NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
NineChronicles.Headless/GraphTypes/ActionQuery.cs

NIneChronicles.Headless now implements factory and interface of ClaimStakeReward.
Also, few updates to cli commands.

Implement ClaimStakeReward interface and factory

---

NineChronicles.Headless/GraphTypes/ActionQuery.cs

Fix `createAvatar` action query

---

NineChronicles.Headless/ActionEvaluationPublisher.cs

Add extra field to evaluation of `BattleGrandFinale`

---

NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
NineChronicles.Headless/GraphTypes/ActionQuery.cs

- bump lib9c
- validate recipients capacity in action query.

set TransferAssets capacity

---

NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
NineChronicles.Headless/GraphTypes/ActionQuery.cs

Introduce runeEnhancement GQL endpoint

---

NineChronicles.Headless.Executable/Configuration.cs
NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless/NineChroniclesNodeService.cs
NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs

This pull requests added an option to give miner break time after mining a block.

feat: Give miner break time

---

NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj
NineChronicles.Headless.Executable/appsettings.development.json

Run `dotnet run -- --config appsettings.development.json`

Provide `appsettings.development.json`

---

Libplanet.Headless/Libplanet.Headless.csproj
NineChronicles.Headless/NineChronicles.Headless.csproj

See https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version#defaults
----------
I'll merge this pull request if the build was successful.

Follow .NET default C# language version

---

Libplanet.Headless.Tests/Libplanet.Headless.Tests.csproj
Libplanet.Headless/Libplanet.Headless.csproj
NineChronicles.Headless.Executable/Commands/ReplayCommand.Privates.cs
NineChronicles.Headless.Executable/Commands/StateCommand.cs
NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj
NineChronicles.Headless.Tests/Common/Fixtures.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/MonsterCollectionResultTypeTest.cs
NineChronicles.Headless.Tests/NineChronicles.Headless.Tests.csproj
NineChronicles.Headless/ActionEvaluationPublisher.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs
NineChronicles.Headless/GraphTypes/States/WorldBossKillRewardRecordType.cs
NineChronicles.Headless/NineChronicles.Headless.csproj

Bump `SonarAnalyzer.CSharp` to `8.49.0.57237`

---

NineChronicles.Headless.Executable.Tests/Commands/ActionCommandTest.cs
NineChronicles.Headless.Executable.Tests/Commands/ChainCommandTest.cs
NineChronicles.Headless.Executable.sln
NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/SignScenarioTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Headless/GraphTypes/ActionMutation.cs
NineChronicles.Headless/GraphTypes/ActionQuery.cs
NineChronicles.Headless/GraphTypes/RuneSlotInfoInputType.cs
NineChronicles.Headless/GraphTypes/RuneSlotInfoType.cs

Bump `lib9c:development` and merge `2022q4-rune` into `development`

---

NineChronicles.Headless.Tests/GraphTypes/AddressQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/WorldBossScenarioTest.cs
NineChronicles.Headless/GraphTypes/AddressQuery.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs

- Inject `StandaloneContext` into `AddressQuery`
- Add `currencyMintersAddress` query

feat: Add `currencyMintersAddress` query

---

NineChronicles.Headless.Executable.Tests/Commands/ActionCommandTest.cs
NineChronicles.Headless.Executable.Tests/Commands/TxCommandTest.cs
NineChronicles.Headless.Executable.sln
NineChronicles.Headless.Executable/Commands/ActionCommand.cs
NineChronicles.Headless.Executable/Commands/ReplayCommand.cs
NineChronicles.Headless.Executable/Commands/TxCommand.cs
NineChronicles.Headless.Tests/GraphTypes/Abstractions/StakeRegularRewardsTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/SignScenarioTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.ActionTxQuery.cs
NineChronicles.Headless.Tests/NineChronicles.Headless.Tests.csproj
NineChronicles.Headless/ActionEvaluationPublisher.cs
NineChronicles.Headless/GraphQLService.cs
NineChronicles.Headless/GraphQLServiceExtensions.cs
NineChronicles.Headless/GraphTypes/ActionQuery.cs
NineChronicles.Headless/GraphTypes/ActionTxQuery.cs
NineChronicles.Headless/GraphTypes/RecipientsInputType.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
NineChronicles.Headless/GraphTypes/States/Models/Table/MonsterCollectionSheetType.cs
NineChronicles.Headless/GraphTypes/States/Models/Table/StakeRegularRewardInfoType.cs
NineChronicles.Headless/GraphTypes/States/Models/Table/StakeRewardEnumType.cs
NineChronicles.Headless/NineChronicles.Headless.csproj

🔀 [PBFT] Merge v100330-1 to pbft-pow

---

NineChronicles.Headless.Executable.Tests/Commands/ActionCommandTest.cs
NineChronicles.Headless.Executable.Tests/Commands/TxCommandTest.cs
NineChronicles.Headless.Executable.sln
NineChronicles.Headless.Executable/Commands/ActionCommand.cs
NineChronicles.Headless.Executable/Commands/ReplayCommand.Privates.cs
NineChronicles.Headless.Executable/Commands/ReplayCommand.cs
NineChronicles.Headless.Executable/Commands/TxCommand.cs
NineChronicles.Headless.Tests/GraphTypes/Abstractions/StakeRegularRewardsTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/SignScenarioTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.ActionTxQuery.cs
NineChronicles.Headless.Tests/NineChronicles.Headless.Tests.csproj
NineChronicles.Headless/ActionEvaluationPublisher.cs
NineChronicles.Headless/GraphQLService.cs
NineChronicles.Headless/GraphQLServiceExtensions.cs
NineChronicles.Headless/GraphTypes/ActionQuery.cs
NineChronicles.Headless/GraphTypes/ActionTxQuery.cs
NineChronicles.Headless/GraphTypes/RecipientsInputType.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
NineChronicles.Headless/GraphTypes/States/Models/Table/MonsterCollectionSheetType.cs
NineChronicles.Headless/GraphTypes/States/Models/Table/StakeRegularRewardInfoType.cs
NineChronicles.Headless/GraphTypes/States/Models/Table/StakeRewardEnumType.cs
NineChronicles.Headless/NineChronicles.Headless.csproj

🔀 [PBFT] Merge v100330-1 to pbft

---

.github/workflows/push_docker_image.yml

🧹 [PBFT] Added pbft branch to docker image workflow

---

NineChronicles.Headless.Executable/Configuration.cs

Nooooooooo Whyyyyyyyy

---

NineChronicles.Headless/BlockChainContext.cs
NineChronicles.Headless/GraphQLServiceExtensions.cs
NineChronicles.Headless/NineChroniclesNodeService.cs
NineChronicles.Headless/StandaloneContext.cs

**NOTE! Query result may contains seed node**

[PBFT] Support graphql query for online validators

---

.github/workflows/push_docker_image.yml

Temporary branch to test optimization. Sorry about the lousy naming scheme. 🙄

⬆️ [PBFT] Bump lib9c pbft for testing

---

.github/workflows/build.yml
NineChronicles.Headless.Executable.Tests/ProgramTest.cs

Bump lib9c - pbft-dynamic_validator

---

NineChronicles.Headless.Executable.Tests/ProgramTest.cs

⬆️ [PBFT] Bump lib9c

---

NineChronicles.Headless.Executable/Configuration.cs
NineChronicles.Headless.Executable/CredentialConfig.cs
NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj
NineChronicles.Headless.Executable/Program.cs

introduce: s3 logger

---

NineChronicles.Headless.Executable/Commands/GenesisCommand.cs

Fix injection of genesis validator set

---

Libplanet.Headless/ReducedStore.cs
NineChronicles.Headless.Executable/Commands/ReplayCommand.Privates.cs
NineChronicles.Headless.Executable/Commands/ReplayCommand.cs
NineChronicles.Headless/GraphTypes/TransactionHeadlessQuery.cs

Bump `Lib9c:development` and fix compile errors

---

NineChronicles.Headless.Tests/Common/Fixtures.cs
NineChronicles.Headless.Tests/GraphTypes/GraphQLTestBase.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Headless.Tests/TableSheetsImporter.cs

Bump `lib9c` and fix `TableSheetsImporter`

---

.github/workflows/deploy_gh_pages.yml

Correct setup-dotnet action version

---

.github/workflows/push_docker_image.yml

Add github action trigger to simply build and push docker image

add workflow dispatch trigger to build and push step

---

Libplanet.Headless/Hosting/LibplanetNodeService.cs

Bump lib9c-pow-dynamic-validator

---

NineChronicles.Headless.Executable.Tests/Commands/ActionCommandTest.cs
NineChronicles.Headless.Executable.Tests/ProgramTest.cs

Bump `lib9c:rc-v100351` into `rc-v100351`

---

Libplanet.Headless/DynamicActionTypeLoader.cs
Libplanet.Headless/Hosting/DynamicActionTypeLoaderConfiguration.cs
Libplanet.Headless/Hosting/LibplanetNodeService.cs
Libplanet.Headless/Hosting/LibplanetNodeServiceProperties.cs
Libplanet.Headless/PluginLoadContext.cs
NineChronicles.Headless.Executable.Tests/Commands/ActionCommandTest.cs
NineChronicles.Headless.Executable/Configuration.cs
NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless.Tests/Controllers/GraphQLControllerTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Headless/NineChroniclesNodeService.cs
NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs

This pull request introduces `DynamicActionTypeLoader`.
You can configure it in `appsettings.json` with `DynamicActionTypeLoader` property. The example setting is below:
```json
{
"DynamicActionTypeLoader": {
"BasePath": "/tmp/testdlls",
"AssemblyFileName": "Lib9c.dll",
"HardForks": [
{
"SinceBlockIndex": 0,
"VersionName": "v100340"
},
{
"SinceBlockIndex":  5673859,
"VersionName": "v100350"
}
]
}
}
```

Introduce `DynamicActionTypeLoader`

---

NineChronicles.Headless.Executable.Tests/Commands/ActionCommandTest.cs
NineChronicles.Headless.Executable.Tests/ProgramTest.cs

Merge `rc-v100351` into `main`

---

NineChronicles.Headless.Tests/GraphTypes/StandaloneSubscriptionTest.cs
NineChronicles.Headless/StandaloneContext.cs

Close https://github.com/orgs/planetarium/projects/75
ReplaySubject -> Subject, and adjust preload test

[Feature] ReplaySubject to Subject

---

NineChronicles.Headless.Executable/appsettings-schema.json

This pull request is a follow-up job of #1826. It introduces some more fields of `appsettings.{network}.json`.

Improve `appsettings-schema.json`

---

Libplanet.Headless.Tests/Hosting/LibplanetNodeServiceTest.cs
Libplanet.Headless/Hosting/LibplanetNodeService.cs
Libplanet.Headless/Hosting/LibplanetNodeServiceProperties.cs
NineChronicles.Headless.Executable/Commands/ReplayCommand.Privates.cs
NineChronicles.Headless.Executable/Commands/ReplayCommand.cs
NineChronicles.Headless.Executable/Configuration.cs
NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless.Executable/appsettings-schema.json
NineChronicles.Headless.Executable/appsettings.internal.json
NineChronicles.Headless.Executable/appsettings.json
NineChronicles.Headless.Executable/appsettings.mainnet.json
NineChronicles.Headless.Executable/appsettings.previewnet.json
NineChronicles.Headless.Tests/Common/ServiceBuilder.cs
NineChronicles.Headless.Tests/Controllers/GraphQLControllerTest.cs
NineChronicles.Headless.Tests/GraphTypes/GraphQLTestBase.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Headless/GraphQLServiceExtensions.cs
NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs
README.md

⬆️ Bump lib9c to 0e75a6ae

---

.github/bin/constants.sh
.github/bin/dist-github-release.sh
.github/bin/dist-pack.sh
.github/bin/github-release.sh
.github/workflows/release.yaml
.gitignore

Related to https://github.com/orgs/planetarium/projects/75/views/2?pane=issue&itemId=9195552
Introduce GitHub release CI
When tagged `v*` create new gitHub release and upload linux, osx, win files

[Feature] Introduce github release CI

---

NineChronicles.Headless/GraphTypes/ActionQuery.DevEx.cs
NineChronicles.Headless/GraphTypes/ActionQuery.cs
NineChronicles.Headless/GraphTypes/Input/ItemIdAndEnhancementType.cs

- Related with https://github.com/planetarium/NineChronicles.Headless/pull/1835
- Add `ActionQuery.DevEx.cs` file which contains a partial class of `ActionQuery`.

[DevEx]Add `createOrReplaceAvatar` action query

---

.github/workflows/release.yaml

This pull request includes a commit cherry-picked from #1868 PR

Fix release workflow bug

---

.github/workflows/push_docker_image.yml

Add quotes around `${{ github.event.inputs.imageTag }}` due to this error: https://github.com/planetarium/NineChronicles.Headless/actions/runs/4063155194/jobs/7010608950#step:3:72

fix syntax error

---

NineChronicles.Headless.Executable/Program.cs

Update pbft logger

---

NineChronicles.Headless.Executable.sln

- Bump `Lib9c`.
- Add `Lib9c.Utils` project to solution.

fix: build errors

---

.github/workflows/push_docker_image.yml

- bump lib9c
- push docker image

 Prepare previewnet test

---

NineChronicles.Headless/NineChronicles.Headless.csproj

This pull request closes #1904 .

Bump OpenTelemetry

---

Dockerfile

~~This pull request requires merging #1921 first.~~

Include Pluggable Lib9c DLLs in container image

---

NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless/HostBuilderExtensions.cs

This pull request resolves #1937.

Track meter always

---

Libplanet.Headless/Hosting/LibplanetNodeService.cs

`Swarm<T>` have to receive `ITransport consensusTransport`, but it was omitted.

Fix: submit consensusTransport param to Swarm

---

NineChronicles.Headless.Executable/Commands/ReplayCommand.cs

Fix startIndex as nullable and use tip index as default

---

NineChronicles.Headless.Executable/appsettings.json
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
NineChronicles.Headless/NineChroniclesNodeService.cs

- change log level verbose for check execution time
- execute target block actions

Introduce replay blocks query

---

NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless.Executable/appsettings.internal.json
NineChronicles.Headless.Executable/appsettings.json
NineChronicles.Headless.Executable/appsettings.mainnet.json

Add json log config

---

NineChronicles.Headless.Executable/Configuration.cs
NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs

feat: arguments for consensus

---

NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless.Executable/appsettings.internal.json
NineChronicles.Headless.Executable/appsettings.json
NineChronicles.Headless.Executable/appsettings.mainnet.json

Add Json logging config

---

NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless.Executable/appsettings.internal.json
NineChronicles.Headless.Executable/appsettings.json
NineChronicles.Headless.Executable/appsettings.mainnet.json

Add json logging configuration

---

NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless.Executable/appsettings.internal.json
NineChronicles.Headless.Executable/appsettings.json
NineChronicles.Headless.Executable/appsettings.mainnet.json

rc-v100382-1 to main

---

Libplanet.Headless/Hosting/LibplanetNodeService.cs

Fix block interval to 7

---

Libplanet.Headless/Hosting/LibplanetNodeService.cs

Release for changing block interval : v200000-2

Merge rc-v200000-2 to main

---

NineChronicles.Headless.Executable/Program.cs

Fix default JSON log path

---

Dockerfile
Dockerfile.amd64
Dockerfile.arm64v8
Libplanet.Headless.Tests/Libplanet.Headless.Tests.csproj
Libplanet.Headless/Libplanet.Headless.csproj
NineChronicles.Headless.Executable.Tests/Commands/ActionCommandTest.cs
NineChronicles.Headless.Executable.Tests/NineChronicles.Headless.Executable.Tests.csproj
NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj
NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless.Tests/NineChronicles.Headless.Tests.csproj
NineChronicles.Headless/GraphQLService.cs
NineChronicles.Headless/NineChronicles.Headless.csproj

Resolves https://github.com/planetarium/NineChronicles.Headless/issues/1986.

Upgrade headless to .NET 7

---

NineChronicles.Headless.Tests/GraphTypes/States/Models/OrderDigestListStateTypeTest.cs
NineChronicles.Headless/GraphTypes/StateQuery.cs
NineChronicles.Headless/GraphTypes/States/Models/Item/InventoryItemType.cs
NineChronicles.Headless/GraphTypes/States/Models/Item/InventoryType.cs
NineChronicles.Headless/GraphTypes/States/Models/Order/OrderDigestListStateType.cs

this pr based from #1972 
- Add queries for check avatar selling list
- Check avatar inventory locked

Introduce OrderDigestListStateType

---

NineChronicles.Headless.Executable/appsettings.json
NineChronicles.Headless/GraphQLService.cs
NineChronicles.Headless/HostBuilderExtensions.cs
NineChronicles.Headless/Middleware/CustomRateLimitMiddleware.cs
NineChronicles.Headless/Middleware/CustomRateLimitProcessor.cs
NineChronicles.Headless/Middleware/GrpcCaptureMiddleware.cs
NineChronicles.Headless/Middleware/HttpCaptureMiddleware.cs

A much simpler update of the original rate limiter(https://github.com/planetarium/NineChronicles.Headless/pull/1995) that can be controlled by modifying "appsettings.json".

Combine grpc/gql rate limiter

---

Libplanet.Extensions.RemoteActionEvaluator/Libplanet.Extensions.RemoteActionEvaluator.csproj
Libplanet.Extensions.RemoteActionEvaluator/RemoteBlockChainStates.cs
NineChronicles.Headless.Executable.sln

This pull request introduces `RemoteBlockChainStates`, `IBlockChainStates` implementation to access `Libplanet.Explrer` in `IBlockChainStates` interface.

Introduce `RemoteBlockChainStates`

---

NineChronicles.Headless.Tests/GraphTypes/States/Models/MeadContractTypeTest.cs
NineChronicles.Headless/GraphTypes/ActionQuery.cs
NineChronicles.Headless/GraphTypes/ActionQueryFields/RegisterMead.cs
NineChronicles.Headless/GraphTypes/StateQuery.cs
NineChronicles.Headless/GraphTypes/States/Models/MeadContractType.cs

- Add action query for contract
- check contract state query

Introduce mead contract api

---

Libplanet.Headless.Tests/Hosting/LibplanetNodeServiceTest.cs
Libplanet.Headless/DynamicActionLoader.cs
Libplanet.Headless/Hosting/LibplanetNodeService.cs
NineChronicles.Headless.Executable/Commands/ReplayCommand.cs
NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless.Tests/Common/ServiceBuilder.cs
NineChronicles.Headless.Tests/Common/StaticActionLoaderSingleton.cs
NineChronicles.Headless.Tests/Controllers/GraphQLControllerTest.cs
NineChronicles.Headless.Tests/GraphTypes/GraphQLTestBase.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Headless/NineChroniclesNodeService.cs
NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs

This PR should be revised after https://github.com/planetarium/lib9c/pull/1889

Bump Libplanet

---

Libplanet.Extensions.RemoteActionEvaluator.Tests/ActionEvaluationSerializerTest.cs

Correct `Libplanet.Extensions.RemoetActionEvaluator` build

---

NineChronicles.Headless.Executable/Program.cs

Fix json log rotation limit from 500M to 100M

---

Lib9c.StateService/Controllers/RemoteEvaluationController.cs
Libplanet.Extensions.ActionEvaluatorCommonComponents/ActionContextMarshaller.cs
Libplanet.Headless/Hosting/LibplanetNodeService.cs
NineChronicles.Headless.Executable.Tests/Commands/AccountCommandTest.cs
NineChronicles.Headless.Executable.Tests/Commands/ChainCommandTest.cs
NineChronicles.Headless.Executable/Commands/ReplayCommand.cs
NineChronicles.Headless.Tests/GraphQLTestUtils.cs
NineChronicles.Headless.Tests/GraphTypes/DummyRenderer.cs
NineChronicles.Headless.Tests/GraphTypes/GraphQLTestBase.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/EquipmentTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/SkillTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/TransactionHeadlessQueryTest.cs
NineChronicles.Headless/GraphTypes/States/Models/SkillType.cs
NineChronicles.Headless/NineChroniclesNodeService.cs

⬆️ Bump lib9c to f33b69c0

---

NineChronicles.Headless/ActionEvaluationPublisher.cs

ssia, need to bump lib9c https://github.com/planetarium/lib9c/pull/1918

remove extra field setting from `ActionEvaluationPublisher`

---

NineChronicles.Headless.Executable/Commands/ReplayCommand.cs

fix(cli): correct replay command

---

NineChronicles.Headless.Executable.Tests/Commands/TxCommandTest.cs
NineChronicles.Headless.Executable/Commands/TxCommand.cs
NineChronicles.Headless.Tests/GraphTypes/SignScenarioTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.ActionTxQuery.cs
NineChronicles.Headless/GraphTypes/ActionQueryFields/RegisterMead.cs
NineChronicles.Headless/GraphTypes/ActionTxQuery.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
NineChronicles.Headless/GraphTypes/StateQuery.cs
NineChronicles.Headless/GraphTypes/TransactionHeadlessQuery.cs

- rename mead API
- add gas config for txs.

Update headless API

---

.github/workflows/push_docker_image.yml

This pull request makes GitHub Actions workflow to publish tagged `planetarium/lib9c-stateservice` too. And it refactors the workflow file with matrix.

ci(gh-actions): refactor docker image build workflow

---

NineChronicles.Headless.Tests/GraphTypes/States/Models/EquipmentTypeTest.cs
NineChronicles.Headless/GraphTypes/States/Models/Item/ItemBaseType.cs

add requiredBlockIndex field.
it can be use like this.
```
query {
stateQuery {
avatar(avatarAddress: "") {
inventory {
equipments {
requiredBlockIndex
}
}
}
}
}
```

Add requiredBlockIndex field

---

.github/workflows/push_docker_image.yml

Update `push docker image` action trigger

---

.github/workflows/lint.yml
.github/workflows/push_docker_image.yml
.github/workflows/validate-github-actions-workflows.yaml

Though I approved #2079 and it was merged, the workflow was broken. This pull request automates validating GitHub Actions with actionlint. It checks GitHub Actions workflow YAML schema and runs shellcheck for `steps.run` scripts.

Automate validating GitHub Actions workflow

---

Libplanet.Extensions.RemoteBlockChainStates/RemoteBlockChainStates.cs
NineChronicles.Headless.Executable/Commands/ReplayCommand.cs
NineChronicles.Headless/BlockChainService.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs

⬆️ Bump lib9c to b3f88b0a

---

NineChronicles.Headless.Executable.Tests/Commands/ActionCommandTest.cs
NineChronicles.Headless.Executable.Tests/Commands/TxCommandTest.cs
NineChronicles.Headless.Executable/Commands/TxCommand.cs

Bump lib9c:development(`8d177752`)

---

.github/workflows/update-submodule.yaml

add submodule-updater to bump headless submodule in `DataProvider`

---

NineChronicles.Headless.Executable.Tests/Commands/TxCommandTest.cs
NineChronicles.Headless.Executable/Commands/TxCommand.cs
NineChronicles.Headless.Tests/GraphTypes/SignScenarioTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.ActionTxQuery.cs
NineChronicles.Headless/GraphTypes/ActionTxQuery.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
NineChronicles.Headless/GraphTypes/TransactionHeadlessQuery.cs

- Delete gasLimit arguments and set gasLimit by action type

Set gasLimit by each action

---

NineChronicles.Headless/ActionEvaluationPublisher.cs

add enemy states(avatar, item slot, rune slot, runes)

Add PreviousStates for rendering of BattleArena

---

NineChronicles.Headless/BlockChainService.cs

Validate tx in grpc PutTransaction

---

NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
NineChronicles.Headless/GraphTypes/TransactionHeadlessQuery.cs

Merge `main` into `development`

---

NineChronicles.Headless/GraphTypes/ActionQuery.cs
NineChronicles.Headless/GraphTypes/ActivationStatusMutation.cs
NineChronicles.Headless/GraphTypes/ActivationStatusQuery.cs
NineChronicles.Headless/GraphTypes/StandaloneMutation.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs

This pull request may resolve parts of #2108

Deprecate activation-related queries

---

Libplanet.Extensions.ActionEvaluatorCommonComponents/AccountDelta.cs
Libplanet.Extensions.ActionEvaluatorCommonComponents/AccountStateDelta.cs
Libplanet.Extensions.ActionEvaluatorCommonComponents/AccountStateDeltaMarshaller.cs
Libplanet.Extensions.RemoteBlockChainStates/RemoteBlockChainStates.cs
NineChronicles.Headless.Executable/Commands/ReplayCommand.Privates.cs
NineChronicles.Headless.Executable/Commands/ReplayCommand.cs
NineChronicles.Headless.Executable/Commands/StateCommand.cs
NineChronicles.Headless/ActionEvaluationPublisher.cs
NineChronicles.Headless/GraphTypes/TransactionHeadlessQuery.cs

Passes all tests, but I cannot ensure things didn't break (especially with `RemoteActionEvaluator` and `ReplayCommand`). 😣
There will be other releases for libplanet shortly to mitigate the issues somewhat.

⬆️ Bump lib9c to 014bff43

---

Libplanet.Extensions.ActionEvaluatorCommonComponents.Tests/ActionEvaluationSerializerTest.cs
Libplanet.Extensions.ActionEvaluatorCommonComponents/ActionContext.cs
Libplanet.Extensions.ActionEvaluatorCommonComponents/ActionContextMarshaller.cs
Libplanet.Extensions.ActionEvaluatorCommonComponents/ActionEvaluation.cs
Libplanet.Extensions.ActionEvaluatorCommonComponents/ActionEvaluationMarshaller.cs
Libplanet.Extensions.RemoteActionEvaluator/RemoteActionEvaluator.cs
Libplanet.Extensions.RemoteBlockChainStates/RemoteBlockChainStates.cs
Libplanet.Headless.Tests/Hosting/LibplanetNodeServiceTest.cs
NineChronicles.Headless.Executable/Commands/ReplayCommand.Privates.cs
NineChronicles.Headless.Executable/Commands/ReplayCommand.cs
NineChronicles.Headless.Executable/Commands/StateCommand.cs
NineChronicles.Headless.Tests/Common/Actions/EmptyAction.cs
NineChronicles.Headless/ActionEvaluationPublisher.cs
NineChronicles.Headless/Controllers/GraphQLController.cs
NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs
NineChronicles.Headless/GraphTypes/TransactionHeadlessQuery.cs

⬆️ Bump lib9c to 9e0282e9

---

NineChronicles.Headless.Tests/GraphTypes/StateQueryTest.cs
NineChronicles.Headless/GraphTypes/StateQueryFields/Garages.cs
NineChronicles.Headless/GraphTypes/States/GaragesType.cs
NineChronicles.Headless/GraphTypes/States/Models/Garage/FungibleItemGarageType.cs

- query
```graphql
query {
stateQuery {
garages(
agentAddr: "0x6132331720A774274d6E51CaeAd375068cC00505",
currencyTickers: [ "NCG", "CRYSTAL", "GARAGE" ],
fungibleItemIds: "0000000000000000000000000000000000000000000000000000000000000000") {
agentAddr
garageBalancesAddr
garageBalances {
currency {
ticker
}
quantity
string
}
fungibleItemGarages {
fungibleItemId # <- added
addr
item {
fungibleItemId
}
count
}
}
}
}
```
- result
```json
{
"data": {
"stateQuery": {
"garages": {
"agentAddr": "0x6132331720A774274d6E51CaeAd375068cC00505",
"garageBalancesAddr": "0x403705B701FC881775112eb68d792d85bfa867d2",
"garageBalances": [
{
"currency": {
"ticker": "NCG"
},
"quantity": "0",
"string": "0 NCG"
},
{
"currency": {
"ticker": "CRYSTAL"
},
"quantity": "0",
"string": "0 CRYSTAL"
},
{
"currency": { …
```

feat: improve state query `garages` result schema

---

NineChronicles.Headless.Executable.Tests/Commands/ActionCommandTest.cs
NineChronicles.Headless.Executable.Tests/Commands/TxCommandTest.cs
NineChronicles.Headless.Executable/Commands/TxCommand.cs
NineChronicles.Headless/GraphTypes/States/StakeStateType.cs

- Bump `lib9c:development`
- Merge `release/4` into `development`

release: merge `release/4` into `development`

---

NineChronicles.Headless.Executable.Tests/Commands/ValidationCommandTest.cs
NineChronicles.Headless.Executable/Commands/ValidationCommand.cs

This pull request resolves #1664.
- Anyone in @planetarium/9c-backend.
- @boscohyun

fix(cli): remove private key from log

---

.github/auto_assign.yml

chore: remove longfin from auto_assign list

---

NineChronicles.Headless.Executable.Tests/Commands/ChainCommandTest.cs

⬆️ Bump lib9c to ec8dc528

---

NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs

This reverts commit e4db3e782ad1a4594b17a491512e110af57730cc.

Revert "feat: Cleanup agent addresses in SubscribeBalance (#2162)"

---

NineChronicles.Headless/GraphTypes/States/Models/Quest/QuestRewardType.cs

Update inteface with https://github.com/planetarium/lib9c/pull/2041

Update interface by bump lib9c

---

NineChronicles.Headless.Tests/GraphTypes/StandaloneSubscriptionTest.cs
NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs
NineChronicles.Headless/GraphTypes/States/Models/Item/InventoryType.cs
NineChronicles.Headless/GraphTypes/TransactionHeadlessQuery.cs

This pull request cherry-picks:
- https://github.com/planetarium/NineChronicles.Headless/pull/2190
- https://github.com/planetarium/NineChronicles.Headless/pull/2184

Some GraphQL features

---

.github/workflows/deploy_gh_pages.yaml

ci(gh-actions): increase delay time between startup and fetching

---

NineChronicles.Headless/GraphTypes/States/Models/Item/InventoryType.cs

```graphql
query {
stateQuery {
avatar(address: "<AVATAR_ADDRESS>") {
inventory {
equipment(ids: [10100000, 10110000]) {
itemSubType
}
}
}
}
```

feat(graphql): provide `ids` filter on `equipments` query

---

NineChronicles.Headless/GraphTypes/ActionQuery.cs

Force `claim_stake_reward6`

---

Dockerfile
Dockerfile.amd64
Dockerfile.arm64v8
NineChronicles.Headless.Executable.Tests/Commands/ActionCommandTest.cs
NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj
NineChronicles.Headless.Tests/GraphTypes/StandaloneSubscriptionTest.cs
NineChronicles.Headless/GraphTypes/ActionQuery.cs
NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs
NineChronicles.Headless/GraphTypes/States/Models/Item/InventoryType.cs
NineChronicles.Headless/GraphTypes/TransactionHeadlessQuery.cs
NineChronicles.Headless/Middleware/CustomRateLimitMiddleware.cs
NineChronicles.Headless/Middleware/IpBanMiddleware.cs

- "release/30"
- "release/31"
- "release/32"

merge release branches into "development"

---

NineChronicles.Headless.Executable.Tests/Commands/ActionCommandTest.cs
NineChronicles.Headless.Executable/Commands/TxCommand.cs

bump lib9c:release/0.5.3

---

NineChronicles.Headless.Executable.Tests/Commands/ActionCommandTest.cs
NineChronicles.Headless.Executable/Commands/TxCommand.cs

bump release/34 into main

---

NineChronicles.Headless.Executable.Tests/Commands/ActionCommandTest.cs
NineChronicles.Headless.Executable/Commands/TxCommand.cs

- bump lib9c:release/1.0.0
- merge release/34 into release/40

merge release/34 into release/40

---

NineChronicles.Headless.Executable.Tests/Commands/ActionCommandTest.cs
NineChronicles.Headless.Executable/Commands/TxCommand.cs

- bump lib9c:development
- merge release/34 into development

merge release/34 into development

---

NineChronicles.Headless/GraphTypes/States/Models/Item/EquipmentType.cs

Exp field needs resolve function

---

Libplanet.Headless.Tests/Hosting/LibplanetNodeServiceTest.cs
Libplanet.Headless/ReducedStore.cs
NineChronicles.Headless.Executable/Commands/ReplayCommand.Privates.cs
NineChronicles.Headless.Executable/Commands/ReplayCommand.cs
NineChronicles.Headless.Executable/Commands/StateCommand.cs
NineChronicles.Headless.Tests/Common/Actions/EmptyAction.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs
NineChronicles.Headless/GraphTypes/TransactionHeadlessQuery.cs

- Change API name `IAccountStateDelta` to `IAccount`.
- Removed `TxSuccess.FungibleAssetDelta`.
For more detailed changes you can get [https://github.com/planetarium/libplanet/releases/tag/3.2.0](https://github.com/planetarium/libplanet/releases/tag/3.2.0).

🚀  bump: libplanet 3.2.0

---

.gitallowed

Add .gitallowed for git secrets

---

NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
NineChronicles.Headless/GraphTypes/ActionQuery.cs
NineChronicles.Headless/GraphTypes/ActionQueryFields/Summon.cs

Introduce auraSummon ActionQuery

---

NineChronicles.Headless.Executable.Tests/Commands/ChainCommandTest.cs
NineChronicles.Headless.Executable/Commands/ReplayCommand.Privates.cs
NineChronicles.Headless.Executable/Commands/ReplayCommand.cs
NineChronicles.Headless.Tests/Common/MockState.cs
NineChronicles.Headless.Tests/GraphQLTestUtils.cs
NineChronicles.Headless.Tests/GraphTypes/TransactionHeadlessQueryTest.cs
NineChronicles.Headless/BlockChainService.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
NineChronicles.Headless/NineChroniclesNodeService.cs

⬆️ Bump libplanet to 3.3.1

---

NineChronicles.Headless/BlockChainService.cs

Implement `IBlockChainService.GetBlockHash` to get `BlockHash` from `BlockIndex` with gRPC.

✨ implement: `IBlockChainService.GetBlockHash`

---

Libplanet.Extensions.ForkableActionEvaluator.Tests/ForkableActionEvaluatorTest.cs
Libplanet.Extensions.ForkableActionEvaluator/ForkableActionEvaluator.cs
NineChronicles.Headless.Executable.Tests/Commands/ChainCommandTest.cs
NineChronicles.Headless.Executable/Commands/ReplayCommand.Privates.cs
NineChronicles.Headless.Executable/Commands/ReplayCommand.cs
NineChronicles.Headless.Executable/Commands/StateCommand.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneSubscriptionTest.cs
NineChronicles.Headless.Tests/GraphTypes/TransactionHeadlessQueryTest.cs

Commit on AEV

---

NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless.Executable/appsettings.json
NineChronicles.Headless.Tests/GraphQLStartupTest.cs
NineChronicles.Headless/ActionEvaluationPublisher.cs
NineChronicles.Headless/GraphQLService.cs
NineChronicles.Headless/GraphTypes/MultiAccountType.cs
NineChronicles.Headless/GraphTypes/RpcInformationQuery.cs
NineChronicles.Headless/Middleware/GrpcMultiAccountManagementMiddleware.cs
NineChronicles.Headless/Middleware/HttpMultiAccountManagementMiddleware.cs

1. Add RPC account tracking in `RPCInformationQuery`.
2. Add RPC account metrics gauage (used in grafana).
3. Update `Http` and `gRPC` account managment middlewares.

Update account management

---

.github/workflows/push_docker_image.yml

ci: push docker image for testing

---

NineChronicles.Headless/BlockChainService.cs

🚀  bump: `NineChronicles.RPC.Shared`

---

NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs
NineChronicles.Headless/GraphTypes/TransactionType.cs

- Support regular expression to filter by action type when subscribing transactions with `subscription.tx` subscription.
- Introduce `subscription.tx.transaction.serializedPayload` field.

Provide some features related to transactions

---

NineChronicles.Headless/ActionEvaluationPublisher.cs

🔧 Fix updated addresses for every render

---

.github/workflows/push_docker_image.yml
NineChronicles.Headless.AccessControlCenter/AccService.cs
NineChronicles.Headless.AccessControlCenter/AccessControlService/MutableRedisAccessControlService.cs
NineChronicles.Headless.AccessControlCenter/AccessControlService/MutableSqliteAccessControlService.cs
NineChronicles.Headless.AccessControlCenter/Controllers/AccessControlServiceController.cs
NineChronicles.Headless.AccessControlCenter/NineChronicles.Headless.AccessControlCenter.csproj
NineChronicles.Headless.AccessControlCenter/Program.cs

Implement swagger page

---

NineChronicles.Headless/Services/RedisAccessControlService.cs
NineChronicles.Headless/Services/SQLiteAccessControlService.cs

Add acs access denied debug log

---

NineChronicles.Headless/Services/RedisAccessControlService.cs
NineChronicles.Headless/Services/SQLiteAccessControlService.cs

Change acs log format for loki

---

.github/workflows/deploy_gh_pages.yaml
NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj
NineChronicles.Headless.Executable/Program.cs
README.md

- This pull request introduces a new CLI document with [***Cocona.Docs***](https://github.com/planetarium/Cocona.Docs) 
- This pull request moves the GraphQL document's path to `/graphql` from `/`  (base: `https://planetarium.github.io/NineChronincles.Headless`).
- This pull request removes *Table of contents* because it was staled and it can be replaced by the GitHub's feature. And it replaces the CLI help message with a link https://planetarium.github.io/NineChronicles.Headless/cli (Preview: https://moreal.github.io/NineChronicles.Headless/cli)
After it is merged, I'll overwrite the index.html in gh-pages.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1205841408648935
- https://app.asana.com/0/0/1205841408648941
- …

Use Cocona.Docs

---

.github/workflows/deploy_gh_pages.yaml
Docs/resources/landing.html

Deploy `index.html` also to gh-pages

---

NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
NineChronicles.Headless/GraphTypes/ActionQuery.cs
NineChronicles.Headless/GraphTypes/ActionQueryFields/ClaimItems.cs
NineChronicles.Headless/GraphTypes/Input/ClaimDataInputType.cs

Introduce ClaimItems GQL endpoint

---

NineChronicles.Headless/GraphTypes/States/CombinationSlotStateType.cs

fix: warning disable CS0618 about CombinationSlotState.UnlockStage

---

NineChronicles.Headless/ActionEvaluationPublisher.cs

🔧  fix: remove diff

---

NineChronicles.Headless/ActionEvaluationPublisher.cs

🔀 merge: release/71 into main

---

NineChronicles.Headless.AccessControlCenter/AccessControlService/IMutableAccessControlService.cs
NineChronicles.Headless.Tests/Policies/StagePolicyTest.cs
NineChronicles.Headless/AccessControlService/IAccessControlService.cs
NineChronicles.Headless/NineChroniclesNodeService.cs
NineChronicles.Headless/Policies/NCStagePolicy.cs
NineChronicles.Headless/Services/AccessControlServiceFactory.cs
NineChronicles.Headless/Services/RedisAccessControlService.cs
NineChronicles.Headless/Services/SQLiteAccessControlService.cs

Resolves https://github.com/planetarium/lib9c/issues/2192.
- lib9c needs to be bumped after https://github.com/planetarium/lib9c/pull/2210 is merged.

Move `NCStagePolicy` to `NineChronicles.Headless`

---

NineChronicles.Headless/Services/RedisAccessControlService.cs

update acs log level to verbose

---

NineChronicles.Headless/Services/RedisAccessControlService.cs

Replaces https://github.com/planetarium/NineChronicles.Headless/pull/2297.

set timeout to 0.5s

---

NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
NineChronicles.Headless/GraphTypes/ActionQueryFields/ClaimItems.cs

Add memo to claimItems GQL

---

NineChronicles.Headless/ActionEvaluationPublisher.cs
NineChronicles.Headless/BlockChainService.cs
NineChronicles.Headless/Middleware/GrpcCaptureMiddleware.cs

- cherrypick from https://github.com/planetarium/NineChronicles.Headless/tree/release/72-caching-sheet

compress csv data in IBlockChainService.GetSheets

---

NineChronicles.Headless.Executable/Configuration.cs
NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless.Tests/GraphQLStartupTest.cs
NineChronicles.Headless.Tests/GraphQLTestUtils.cs
NineChronicles.Headless.Tests/GraphTypes/GraphQLTestBase.cs
NineChronicles.Headless.Tests/GraphTypes/StateQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/AgentStateTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/AvatarStateTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/StakeStateTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/WorldBossScenarioTest.cs
NineChronicles.Headless/ActionEvaluationPublisher.cs
NineChronicles.Headless/ArenaParticipantsWorker.cs
NineChronicles.Headless/BlockChainService.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
NineChronicles.Headless/GraphTypes/StateQuery.cs
NineChronicles.Headless/GraphTypes/States/AgentStateType.cs
NineChronicles.Headless/GraphTypes/States/AvatarStateType.cs
NineChronicles.Headless/GraphTypes/States/StakeStateType.cs
NineChronicles.Headless/GraphTypes/States/StateContext.cs
NineChronicles.Headless/StateMemoryCache.cs

- rename cache class
- add arguments for worker interval
- set compressed sheet value instead of compress every request

Refactor caching

---

NineChronicles.Headless/ArenaParticipantsWorker.cs

more detailed worker log for arena list caching

detailed log arena list worker

---

NineChronicles.Headless.Tests/GraphTypes/TransactionHeadlessQueryTest.cs

⬆️ Bump lib9c to d7c3bfdc

---

NineChronicles.Headless.Tests/GraphTypes/TransactionHeadlessQueryTest.cs
NineChronicles.Headless/GraphTypes/TransactionHeadlessQuery.cs

introduce bulk api for transaction result check from #2323

Introduce TransactionResults query

---

NineChronicles.Headless.AccessControlCenter/Controllers/AccessControlServiceController.cs

- Add new endpoint "entries/bulk-add-tx-quota"

[Feature] Implement Acc bulk insert

---

NineChronicles.Headless.AccessControlCenter/Controllers/AccessControlServiceController.cs
NineChronicles.Headless/Services/AccessControlServiceFactory.cs
NineChronicles.Headless/Services/RedisAccessControlService.cs
NineChronicles.Headless/Services/RestAPIAccessControlService.cs
NineChronicles.Headless/Services/SQLiteAccessControlService.cs

- Add new RestAPIAccessControlService class
You can use acs with rest api get query

[Feature] Add Restapi acs

---

Libplanet.Headless/Hosting/LibplanetNodeService.cs

feat: resolve plugin path

---

Libplanet.Extensions.PluggedActionEvaluator/Libplanet.Extensions.PluggedActionEvaluator.csproj
Libplanet.Extensions.PluggedActionEvaluator/PluggedActionEvaluator.cs
Libplanet.Extensions.PluggedActionEvaluator/PluginKeyValueStore.cs
Libplanet.Extensions.PluggedActionEvaluator/PluginLoadContext.cs
Libplanet.Headless/Hosting/ActionEvaluatorType.cs
Libplanet.Headless/Hosting/LibplanetNodeService.cs
Libplanet.Headless/Hosting/PluggedActionEvaluatorConfiguration.cs
Libplanet.Headless/Libplanet.Headless.csproj
NineChronicles.Headless.Executable.sln
NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless.Executable/appsettings-schema.json

🔀 merge release/73 into main

---

Libplanet.Headless/Hosting/ActionEvaluatorType.cs
Libplanet.Headless/Hosting/LibplanetNodeService.cs
Libplanet.Headless/Hosting/RemoteActionEvaluatorConfiguration.cs
NineChronicles.Headless.Executable.Tests/Commands/TxCommandTest.cs
NineChronicles.Headless.Executable.sln
NineChronicles.Headless.Executable/Commands/ReplayCommand.Privates.cs
NineChronicles.Headless.Executable/Commands/ReplayCommand.cs
NineChronicles.Headless.Executable/Commands/StateCommand.cs
NineChronicles.Headless.Executable/Commands/TxCommand.cs
NineChronicles.Headless.Executable/Program.cs

⬆️ Bump lib9c to c8247aaa (libplanet 3.9.0)

---

Libplanet.Headless/Hosting/LibplanetNodeService.cs
Libplanet.Headless/Libplanet.Headless.csproj

🧹 Just taking care of some stuff missed in #2344. Kind of odd missing project reference didn't throw an error. 🙄

🧹 Remove unnecessary code

---

NineChronicles.Headless.Executable/appsettings.json
NineChronicles.Headless/GraphQLService.cs
NineChronicles.Headless/GraphTypes/StandaloneMutation.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs
NineChronicles.Headless/Middleware/JwtAuthenticationMiddleware.cs
NineChronicles.Headless/NineChronicles.Headless.csproj
NineChronicles.Headless/Properties/JwtOptions.cs

Introduce JWT Authentication for GraphQL(Optional)

---

config.json.example
config.schema.json

Add schema file for config.json (used by genesis block generator cli tool)

PDX-203: add config.schema.json

---

Dockerfile.amd64

add rocksdb-related dependencies

---

NineChronicles.Headless/GraphTypes/TransactionHeadlessQuery.cs

✨ Added `TxStatus.INCLUDED`

---

NineChronicles.Headless/GraphTypes/States/Models/Item/InventoryItemType.cs

- add fungibleItemId for check garage quantity

Add fungibleItemId on inventory item

---

NineChronicles.Headless.Executable.Tests/Commands/ChainCommandTest.cs
NineChronicles.Headless.Executable/Commands/ChainCommand.cs

update snapshot command to latest

---

NineChronicles.Headless/Services/RedisAccessControlService.cs
NineChronicles.Headless/Services/RestAPIAccessControlService.cs

ACS Handle redis, resapi timeout

---

NineChronicles.Headless/GraphQLService.cs
NineChronicles.Headless/HostBuilderExtensions.cs
NineChronicles.Headless/Middleware/GrpcMultiAccountManagementMiddleware.cs
NineChronicles.Headless/Middleware/HttpMultiAccountManagementMiddleware.cs
NineChronicles.Headless/Middleware/IpBanMiddleware.cs

update multiaccount management middleware

---

README.md

Add devforum badge to README

---

NineChronicles.Headless.Tests/Common/KeyConverters.cs
NineChronicles.Headless.Tests/Common/MockAccount.cs
NineChronicles.Headless.Tests/Common/MockAccountState.cs
NineChronicles.Headless.Tests/Common/MockWorld.cs
NineChronicles.Headless.Tests/Common/MockWorldDelta.cs
NineChronicles.Headless.Tests/Common/MockWorldState.cs
NineChronicles.Headless/GraphQLServiceExtensions.cs
NineChronicles.Headless/GraphTypes/ActionMutation.cs

⬆️ [Libplanet 4.0] Bump lib9c to a56d8ea52

---

NineChronicles.Headless.Tests/Common/MockAccountState.cs
NineChronicles.Headless/GraphTypes/StateQueryFields/Garages.cs

🔧 [Libplanet 4.0] Fix query tests

---

NineChronicles.Headless/ActionEvaluationPublisher.cs
NineChronicles.Headless/GraphQLServiceExtensions.cs

⬆️ Bump lib9c to e1742b5c (libplanet 3.9.3)

---

NineChronicles.Headless.Tests/Common/MockWorld.cs
NineChronicles.Headless.Tests/Common/MockWorldState.cs
NineChronicles.Headless/BlockChainService.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs

⬆️ [Libplanet 4.0] Bump lib9c to b4c1fda61

---

Libplanet.Extensions.ForkableActionEvaluator.Tests/ForkableActionEvaluatorTest.cs
Libplanet.Extensions.ForkableActionEvaluator/ForkableActionEvaluator.cs
Libplanet.Extensions.PluggedActionEvaluator/PluggedActionEvaluator.cs

Match API of AEVs not to reveal stateRootHashBytes

---

.github/workflows/push_docker_image.yml

Add upgrade/libplanet-4.0 branch on workflow to push docker image

---

NineChronicles.Headless/BlockChainService.cs

Fix NRE on byte encodings on BlockChainService

---

NineChronicles.Headless.AccessControlCenter/Controllers/AccessControlServiceController.cs
NineChronicles.Headless.Executable.Tests/Commands/ActionCommandTest.cs
NineChronicles.Headless.Executable.Tests/Commands/TxCommandTest.cs
NineChronicles.Headless.Executable/Commands/ActionCommand.cs
NineChronicles.Headless.Executable/Commands/TxCommand.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Headless/ActionEvaluationPublisher.cs
NineChronicles.Headless/GraphQLService.cs
NineChronicles.Headless/GraphTypes/ActionMutation.cs
NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs
NineChronicles.Headless/HostBuilderExtensions.cs
NineChronicles.Headless/Middleware/GrpcMultiAccountManagementMiddleware.cs
NineChronicles.Headless/Middleware/HttpMultiAccountManagementMiddleware.cs
NineChronicles.Headless/Middleware/IpBanMiddleware.cs
README.md

🔀 [Libplanet 4.0] Merge 285d5e95 into libplanet 4.0

---

NineChronicles.Headless.Executable.Tests/Commands/ChainCommandTest.cs
NineChronicles.Headless.Executable/Configuration.cs
NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless.Executable/appsettings.internal.json
NineChronicles.Headless.Tests/Common/ServiceBuilder.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/TransactionHeadlessQueryTest.cs
NineChronicles.Headless/NineChroniclesNodeService.cs
NineChronicles.Headless/Properties/NetworkType.cs
NineChronicles.Headless/Properties/NineChroniclesNodeServiceProperties.cs

As title says, this PR replace `--network-type` argument with `--planet` to specify planet which node will be belongs to.

Replace `--network-type` with `--planet`

---

NineChronicles.Headless.Tests/ArenaParticipantsWorkerTest.cs
NineChronicles.Headless/ArenaParticipantsWorker.cs

merge collection system development

development merge feature/collection branch

---

NineChronicles.Headless.Tests/ArenaParticipantsWorkerTest.cs
NineChronicles.Headless/ArenaParticipantsWorker.cs

- Bump lib9c
- Fix calculate cp

Fix arena worker

---

NineChronicles.Headless.Tests/ArenaParticipantsWorkerTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Headless/ArenaParticipantsWorker.cs

merge release/100 into development

merge release/100 into development

---

NineChronicles.Headless.Tests/GraphTypes/StandaloneSubscriptionTest.cs
NineChronicles.Headless/GraphTypes/StandaloneSubscription.cs
NineChronicles.Headless/StandaloneContext.cs

Monstercollection is no longer used so this PR removes it from standalone subscription.

remove monster collection

---

NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
NineChronicles.Headless/GraphTypes/ActionQuery.cs
NineChronicles.Headless/GraphTypes/ActionQueryFields/RetrieveAvatarAssets.cs

- implement action query API for NCIP-18

Register RetrieveAvatarAssets query

---

NineChronicles.Headless.Tests/ArenaParticipantsWorkerTest.cs
NineChronicles.Headless/ArenaParticipantsWorker.cs
NineChronicles.Headless/GraphTypes/States/AvatarStateType.cs

- Revert Libplanet version to 4.2.0
- Use `AllRuneState` to use new rune state module

Reset lib9c

---

NineChronicles.Headless.Executable/Commands/ReplayCommand.Privates.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Headless/GraphTypes/StateQuery.cs
NineChronicles.Headless/GraphTypes/StateQueryFields/Garages.cs

⬆️ Bump libplanet to 4.4.1

---

Libplanet.Headless/Hosting/LibplanetNodeService.cs

Backmerge 130 to development

---

NineChronicles.Headless.Tests/GraphTypes/States/Models/AvatarStateTypeTest.cs
NineChronicles.Headless/GraphTypes/States/AvatarStateType.cs

Fix AvatarStateType actionPoint, dailyRewardReceivedBlockIndex

---

NineChronicles.Headless.AccessControlCenter/Controllers/AccessControlServiceController.cs
NineChronicles.Headless/Services/RedisAccessControlService.cs
NineChronicles.Headless/Services/RestAPIAccessControlService.cs
NineChronicles.Headless/Services/SQLiteAccessControlService.cs

Bump lib9c after https://github.com/planetarium/lib9c/pull/2554 is merged.

update acs GetTxQuota Method to async

---

NineChronicles.Headless.Executable.sln

Add Libplanet.Mocks project to solution

---

NineChronicles.Headless.Executable/Commands/TxCommand.cs
NineChronicles.Headless/BlockChainService.cs

bump lib9c & follow update https://github.com/planetarium/lib9c/pull/2569

Delete agent, avatar legacy account backward compatible code

---

NineChronicles.Headless/GraphQLServiceExtensions.cs

⬆️ Bump libplanet to 4.4.2

---

NineChronicles.Headless.Tests/GraphTypes/States/Models/CrystalMonsterCollectionMultiplierSheetTypeTest.cs

⬆️ Bump lib9c to 90f1b34f

---

NineChronicles.Headless.Executable.Tests/ProgramTest.cs

⬆️ Bump libplanet to 4.6.0

---

Libplanet.Headless.Tests/Hosting/LibplanetNodeServiceTest.cs
NineChronicles.Headless.Executable.Tests/Commands/AccountCommandTest.cs
NineChronicles.Headless.Executable.Tests/Commands/ChainCommandTest.cs
NineChronicles.Headless.Executable.Tests/Commands/GenesisHelper.cs
NineChronicles.Headless.Executable.Tests/ProgramTest.cs
NineChronicles.Headless.Executable.Tests/Store/StoreExtensionsTest.cs
NineChronicles.Headless.Executable/Commands/ChainCommand.cs
NineChronicles.Headless.Executable/Commands/ReplayCommand.Queries.cs
NineChronicles.Headless.Executable/Commands/ReplayCommand.cs
NineChronicles.Headless.Executable/Commands/StateCommand.cs
NineChronicles.Headless.Executable/Store/AnonymousStore.cs
NineChronicles.Headless.Tests/GraphQLTestUtils.cs
NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/AddressQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/GraphQLTestBase.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneSubscriptionTest.cs
NineChronicles.Headless.Tests/GraphTypes/TransactionHeadlessQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/WorldBossScenarioTest.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs

Bump prerelease of Sloth, and apply changes for it.

Bump Lib9c:sloth

---

NineChronicles.Headless.Tests/GraphTypes/StandaloneMutationTest.cs

Backmerge 160 into development

Backmerge 160

---

NineChronicles.Headless.Executable.Tests/NineChronicles.Headless.Executable.Tests.csproj
NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless/NineChronicles.Headless.csproj

https://github.com/Cysharp/MagicOnion?tab=readme-ov-file#metrics
in order to utilize metrics from magiconion, we need to upgrade it to at least `6.0.0`

Upgrade MaginOnion version to 6.1.3

---

NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj
NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless/NineChronicles.Headless.csproj

add pyroscope tracing

---

Libplanet.Extensions.ForkableActionEvaluator.Tests/ForkableActionEvaluatorTest.cs
Libplanet.Extensions.ForkableActionEvaluator/Libplanet.Extensions.ForkableActionEvaluator.csproj
Libplanet.Extensions.PluggedActionEvaluator/Libplanet.Extensions.PluggedActionEvaluator.csproj
Libplanet.Headless/Libplanet.Headless.csproj
NineChronicles.Headless.Executable.Tests/Commands/ChainCommandTest.cs
NineChronicles.Headless.Executable.Tests/Commands/GenesisHelper.cs
NineChronicles.Headless.Executable.Tests/NineChronicles.Headless.Executable.Tests.csproj
NineChronicles.Headless.Executable.sln
NineChronicles.Headless.Executable/Commands/ReplayCommand.Privates.cs
NineChronicles.Headless.Executable/Commands/ReplayCommand.cs
NineChronicles.Headless.Executable/Commands/StateCommand.cs
NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj
NineChronicles.Headless.Executable/Store/AnonymousStore.cs
NineChronicles.Headless.Tests/GraphQLTestUtils.cs
NineChronicles.Headless.Tests/GraphTypes/GraphQLTestBase.cs
NineChronicles.Headless.Tests/GraphTypes/TransactionHeadlessQueryTest.cs
NineChronicles.Headless/GraphQLServiceExtensions.cs
NineChronicles.Headless/NineChronicles.Headless.csproj

libplanet 5.1.2 이 범프된 lib9c 범프 입니다. 자세한 내용은 https://github.com/planetarium/lib9c/pull/2696 에 있습니다.

Bump libplanet to 5.1.2

---

NineChronicles.Headless/GraphTypes/StandaloneQuery.cs

Implement account diffs type

---

Libplanet.Headless/Hosting/LibplanetNodeService.cs
NineChronicles.Headless.Executable.Tests/Commands/AccountCommandTest.cs
NineChronicles.Headless.Executable.Tests/Commands/ChainCommandTest.cs
NineChronicles.Headless.Executable/Commands/ChainCommand.cs
NineChronicles.Headless.Executable/Commands/ReplayCommand.Privates.cs
NineChronicles.Headless.Executable/Commands/ReplayCommand.cs
NineChronicles.Headless.Executable/Commands/StateCommand.cs
NineChronicles.Headless.Tests/GraphQLTestUtils.cs
NineChronicles.Headless.Tests/GraphTypes/TransactionHeadlessQueryTest.cs

⬆️
https://github.com/planetarium/lib9c/pull/2703

⬆️ Bump libplanet to 5.2.0

---

NineChronicles.Headless/NineChronicles.Headless.csproj

v200211 hotfix

---

NineChronicles.Headless/NineChronicles.Headless.csproj

This pull request just cherry-picks #2516's merge commit.

Port #2516

---

NineChronicles.Headless.Executable/Configuration.cs
NineChronicles.Headless.Executable/NineChronicles.Headless.Executable.csproj
NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless.Tests/GraphQLStartupTest.cs
NineChronicles.Headless.Tests/GraphTypes/GraphQLTestBase.cs
NineChronicles.Headless/ActionEvaluationPublisher.cs
NineChronicles.Headless/BlockChainService.cs
NineChronicles.Headless/NineChronicles.Headless.csproj

chore: remove sentry

---

NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
NineChronicles.Headless/GraphTypes/TransactionHeadlessQuery.cs

From https://github.com/planetarium/NineChronicles.Headless/commit/f0d3519d514552ece82daec1b165b9c5a7f7aa16

Cherry pick from f0d35

---

NineChronicles.Headless/Services/AccessControlServiceFactory.cs
NineChronicles.Headless/Services/LocalAccessControlService.cs

Add whitelist from S3

---

NineChronicles.Headless.Executable/Program.cs
NineChronicles.Headless/GraphTypes/StandaloneMutation.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
NineChronicles.Headless/GraphTypes/TransactionHeadlessQuery.cs
NineChronicles.Headless/Services/AccessControlServiceFactory.cs
NineChronicles.Headless/Services/LocalAccessControlService.cs
NineChronicles.Headless/Services/RedisAccessControlService.cs

Backmerge 190 into development

Backmerge 190

---

.github/workflows/build.yml
.github/workflows/deploy_gh_pages.yaml
.github/workflows/deploy_ghpackages_docker.yml
.github/workflows/lint.yml
.github/workflows/push_docker_image.yml
.github/workflows/release.yaml
.github/workflows/validate-github-actions-workflows.yaml

Bump `actions/*` GitHub Actions

---

scripts/create-config-for-single.sh

Add create config script for create genesis block

---

NineChronicles.Headless.Executor/NineChronicles.Headless.Executor.csproj
NineChronicles.Headless.Executor/Program.cs

Add `Replace("\\", "\\\\")` for window config files

Handling window path

---

NineChronicles.Headless.Executable.Tests/Commands/ActionCommandTest.cs

Fix `ActionCommandTest`

---

Libplanet.Headless/Hosting/LibplanetNodeService.cs

⬆️ Bump libplanet to 5.3.0 alpha.3

---

NineChronicles.Headless.Tests/ArenaParticipantsWorkerTest.cs
NineChronicles.Headless.Tests/Common/Fixtures.cs

AvatarState does not receive AvatarSheets anymore.

Fix broken tests

---

NineChronicles.Headless.Executable/Configuration.cs
NineChronicles.Headless.Executable/Program.cs

chore: clean arenaParticipantsSync option

---

NineChronicles.Headless/GraphTypes/CurrencyEnumType.cs

Support more minterless currencies

---

NineChronicles.Headless/GraphTypes/ActionMutation.cs

Deprecate outdated ActionMutation

---

.github/workflows/push_docker_image.yml

refactor: use buildx on  push_doker_image

---

.github/workflows/deploy_gh_pages.yaml

ci: bump peaceiris/actions-gh-pages action to v4

---

NineChronicles.Headless.Executable.Tests/Commands/ChainCommandTest.cs
NineChronicles.Headless.Executable.Tests/Commands/GenesisHelper.cs
NineChronicles.Headless.Executable.Tests/NineChronicles.Headless.Executable.Tests.csproj
NineChronicles.Headless.Executable.Tests/TableSheetsImporter.cs
NineChronicles.Headless.Executable/Commands/GenesisCommand.cs
NineChronicles.Headless.Executable/Commands/ReplayCommand.Privates.cs
NineChronicles.Headless.Tests/Action/ActionContext.cs
NineChronicles.Headless.Tests/Common/Fixtures.cs
NineChronicles.Headless.Tests/GraphQLTestUtils.cs
NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/AddressQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/GraphQLTestBase.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneMutationTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/StakeAchievementsTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/StakeStateTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/TransactionHeadlessQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/WorldBossScenarioTest.cs
NineChronicles.Headless/GraphTypes/ActionMutation.cs
NineChronicles.Headless/GraphTypes/ActionQuery.cs
NineChronicles.Headless/GraphTypes/StateQuery.cs
NineChronicles.Headless/GraphTypes/States/StakeAchievementsType.cs
NineChronicles.Headless/GraphTypes/States/StakeStateType.cs
NineChronicles.Headless/Utils/HallowActionContext.cs

Release 211

---

NineChronicles.Headless/GraphTypes/ActionQuery.cs

Release 213

---

NineChronicles.Headless.Executable/Commands/GenesisCommand.cs

- Update validator power config for PoS

Update Validator power config

---

.github/workflows/lint.yml

fix lint action error

---

Libplanet.Extensions.PluggedActionEvaluator/Libplanet.Extensions.PluggedActionEvaluator.csproj
Libplanet.Extensions.PluggedActionEvaluator/PluggedActionEvaluator.cs
NineChronicles.Headless.Executable.Tests/Commands/ActionCommandTest.cs
NineChronicles.Headless.Executable.Tests/Commands/TxCommandTest.cs
NineChronicles.Headless.Executable.sln
NineChronicles.Headless.Executable/Commands/ActionCommand.cs
NineChronicles.Headless.Tests/Action/ActionContext.cs
NineChronicles.Headless.Tests/GraphTypes/ActionQueryTest.cs
NineChronicles.Headless.Tests/GraphTypes/DelegatorTypeTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.ActionTxQuery.cs
NineChronicles.Headless.Tests/GraphTypes/States/Models/StakeStateTypeTest.cs
NineChronicles.Headless/BlockChainService.cs
NineChronicles.Headless/GraphTypes/ActionQuery.DevEx.cs
NineChronicles.Headless/GraphTypes/ActionQuery.cs
NineChronicles.Headless/GraphTypes/DelegatorType.cs
NineChronicles.Headless/GraphTypes/GuildType.cs
NineChronicles.Headless/GraphTypes/StateQuery.cs
NineChronicles.Headless/GraphTypes/States/StakeStateType.cs

https://github.com/planetarium/lib9c/pull/3138 의 변경사항을 반영합니다.
- Lib9c 범프
- 빌드 픽스
- 관련 RPC 쿼리 추가
- 관련 GQL 쿼리 추가 및 수정

Update for PoS Staking

---

NineChronicles.Headless.Tests/GraphTypes/SignScenarioTest.cs
NineChronicles.Headless.Tests/GraphTypes/StandaloneQueryTest.ActionTxQuery.cs
NineChronicles.Headless/GraphTypes/FixedFungibleAssetValueInputType.cs
NineChronicles.Headless/GraphTypes/StandaloneQuery.cs
NineChronicles.Headless/GraphTypes/TransactionHeadlessQuery.cs

https://github.com/planetarium/NineChronicles.Headless/issues/2675

Update default max gas price

---

NineChronicles.Headless/BlockChainService.cs

Applying dynamic unbonding period, update RPC query for non-guild-member.

Apply dynamic unbonding period

---

NineChronicles.Headless.Tests/BlockChainServiceTest.cs
NineChronicles.Headless/BlockChainService.cs

- resolve #2702 
- grpc GetState 관련 인터페이스에서 IValue를 압축해서 전달하도록 변경합니다. grpc Client쪽도 이에 맞춰 압축을 해제하는 변경이 필요합니다.

Compress IValue in get state

---

NineChronicles.Headless.Tests/MemoryCacheExtensionsTest.cs

캐싱된 시트 평탄화 작업으로 윈도우에서 줄바꿈문자 변경으로 인해 테스트가 깨지는걸 수정합니다.

Fix test in windows

---

NineChronicles.Headless/Middleware/CustomRateLimitMiddleware.cs

ensure jwt client doesn't get banned

---

NineChronicles.Headless.Executable.Tests/Commands/ChainCommandTest.cs
NineChronicles.Headless.Executable/Commands/ChainCommand.cs

Fix truncate command where block commit wasn't truncated properly.

Fix truncate command
